# -*- coding: utf-8 -*-
"""Bai08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHDsR4_iA7HpVWQsuqO4gik_uQ1oZvlK
"""

# ============================================================
# CELL 2 — HÀM SIMULATE & SOLVE DÙNG CHUNG CHO TẤT CẢ CÂU
# ============================================================

def simulate(params, shock_year=None, shock_pct=0.0):
    """
    Mô phỏng quỹ đạo kinh tế 2026-2035.

    params: vector 5*T gồm [I_K, I_D, I_AI, I_H, C]
    shock_year: năm xảy ra cú sốc (index 0=2026, 2=2028...)
    shock_pct:  tỷ lệ Y giảm do cú sốc (0.08 = giảm 8%)

    Trả về: dict các mảng quỹ đạo
    """
    IK  = params[0*T : 1*T]
    ID  = params[1*T : 2*T]
    IAI = params[2*T : 3*T]
    IH  = params[3*T : 4*T]
    C   = params[4*T : 5*T]

    K  = np.zeros(T+1); K[0]  = K0
    D  = np.zeros(T+1); D[0]  = D0
    AI = np.zeros(T+1); AI[0] = AI0
    H  = np.zeros(T+1); H[0]  = H0
    Y  = np.zeros(T)

    for t in range(T):
        Y[t] = (A_seq[t] * K[t]**alpha * L**beta_l *
                D[t]**gamma_d * AI[t]**delta_ai * H[t]**theta_h)
        if shock_year is not None and t == shock_year:
            Y[t] *= (1.0 - shock_pct)

        K[t+1]  = (1 - dK)  * K[t]  + IK[t]
        D[t+1]  = (1 - dD)  * D[t]  + ID[t]
        AI[t+1] = (1 - dAI) * AI[t] + IAI[t]
        H[t+1]  = H[t] + theta_H_eff * IH[t] - mu * H[t]

    return dict(K=K, D=D, AI=AI, H=H, Y=Y, C=C, IK=IK, ID=ID, IAI=IAI, IH=IH)


def solve_optimal(shock_year=None, shock_pct=0.0):
    """
    Giải bài toán tối ưu động bằng scipy SLSQP.
    Hàm mục tiêu: max Σ ρ^t * ln(C_t)
    Ràng buộc: C_t + I_K_t + I_D_t + I_AI_t + I_H_t <= Y_t
    """
    def neg_welfare(p):
        C = p[4*T : 5*T]
        return -sum(rho**t * np.log(max(C[t], 1e-6)) for t in range(T))

    def make_budget_con(tt):
        def con(p):
            d = simulate(p, shock_year, shock_pct)
            return (d['Y'][tt] - d['C'][tt]
                    - d['IK'][tt] - d['ID'][tt]
                    - d['IAI'][tt] - d['IH'][tt])
        return con

    constraints = [{'type': 'ineq', 'fun': make_budget_con(t)} for t in range(T)]

    bounds = (
        [(0, Y0 * 0.50)] * T +   # I_K
        [(0, 5.0)]        * T +   # I_D  (% GDP, max 5%)
        [(0, 20.0)]       * T +   # I_AI (nghìn DN, max 20)
        [(0, 5.0)]        * T +   # I_H  (% lao động)
        [(1.0, Y0)]       * T     # C
    )

    x0 = np.concatenate([
        np.ones(T) * Y0 * 0.25,
        np.ones(T) * 0.5,
        np.ones(T) * 5.0,
        np.ones(T) * 0.5,
        np.ones(T) * Y0 * 0.25,
    ])

    res = minimize(
        neg_welfare, x0,
        method='SLSQP',
        bounds=bounds,
        constraints=constraints,
        options={'maxiter': 3000, 'ftol': 1e-9, 'disp': False}
    )
    return res


def welfare_from_trajectory(IK, ID, IAI, IH,
                             shock_year=None, shock_pct=0.0):
    """
    Tính welfare từ quỹ đạo đầu tư cho trước.
    C_t = max(Y_t - tổng đầu tư, 1.0)
    """
    K=np.zeros(T+1); D=np.zeros(T+1)
    AI=np.zeros(T+1); H=np.zeros(T+1)
    K[0]=K0; D[0]=D0; AI[0]=AI0; H[0]=H0
    Y=np.zeros(T); C=np.zeros(T)

    for t in range(T):
        Y[t] = (A_seq[t] * K[t]**alpha * L**beta_l *
                D[t]**gamma_d * AI[t]**delta_ai * H[t]**theta_h)
        if shock_year is not None and t == shock_year:
            Y[t] *= (1.0 - shock_pct)

        I_tot = IK[t] + ID[t] + IAI[t] + IH[t]
        C[t]  = max(Y[t] - I_tot, 1.0)

        K[t+1]  = (1-dK)*K[t]  + IK[t]
        D[t+1]  = (1-dD)*D[t]  + ID[t]
        AI[t+1] = (1-dAI)*AI[t]+ IAI[t]
        H[t+1]  = H[t] + theta_H_eff*IH[t] - mu*H[t]

    W = sum(rho**t * np.log(max(C[t], 1e-6)) for t in range(T))
    return W, Y, C, K, D, AI, H


print("✅ Hàm simulate & solve đã sẵn sàng!")

# ============================================================
# CELL 3 — CÂU 8.3.1 & 8.3.2
# Giải bài toán tối ưu động (SLSQP)
# Vẽ quỹ đạo K, D, AI, H, Y, C từ 2026-2035
# ============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy.optimize import minimize

T = 10 # Represents the 10 years from 2026 to 2035

# Define model parameters and initial conditions (example values)
K0 = 1000.0
D0 = 10.0
AI0 = 10.0
H0 = 50.0
Y0 = 200.0  # Initial Output, used for bounds and x0

rho = 0.96 # Discount factor
L = 100.0 # Labor
A_seq = np.linspace(1.0, 1.0 + T * 0.015, T) # TFP sequence, assuming 1.5% annual growth

alpha = 0.3 # Elasticity of K
beta_l = 0.4 # Elasticity of L
gamma_d = 0.1 # Elasticity of D
delta_ai = 0.1 # Elasticity of AI
theta_h = 0.1 # Elasticity of H

dK = 0.1 # Depreciation rate of K
dD = 0.05 # Depreciation rate of D
dAI = 0.08 # Depreciation rate of AI
theta_H_eff = 1.0 # Efficiency of H investment
mu = 0.02 # Depreciation rate of H

YEARS = np.arange(2026, 2026 + T)
COLORS = {'K': '#4C72B0', 'D': '#55A868', 'AI': '#C44E52', 'H': '#8172B3', 'Y': '#937860', 'C': '#DA8BC3'}

print("=" * 65)
print("CÂU 8.3.1 — GIẢI TỐI ƯU ĐỘNG (SLSQP)")
print("=" * 65)

print("\n⏳ Đang tối ưu... (~30 giây)\n")
res_base = solve_optimal()

print(f"Trạng thái : {res_base.message}")
print(f"Welfare W* = {-res_base.fun:.4f}")

traj = simulate(res_base.x)
K_o, D_o, AI_o, H_o = traj['K'], traj['D'], traj['AI'], traj['H']
Y_o, C_o = traj['Y'], traj['C']
IK_o, ID_o, IAI_o, IH_o = traj['IK'], traj['ID'], traj['IAI'], traj['IH']

# Bảng kết quả
print("\n" + "=" * 65)
print("CÂU 8.3.2 — QUỸ ĐẠO TỐI ƯU 2026-2035")
print("=" * 65)

df_traj = pd.DataFrame({
    'Năm'      : YEARS,
    'Y (tỷ)'   : Y_o.round(1),
    'C (tỷ)'   : C_o.round(1),
    'K (ngh.tỷ)': K_o[:T].round(1),
    'D (%GDP)' : D_o[:T].round(2),
    'AI (ngh.DN)': AI_o[:T].round(1),
    'H (%LĐ)'  : H_o[:T].round(2),
    'I_K'      : IK_o.round(1),
    'I_D'      : ID_o.round(3),
    'I_AI'     : IAI_o.round(2),
    'I_H'      : IH_o.round(3),
})
print(df_traj.to_string(index=False))

# ── Vẽ biểu đồ quỹ đạo ────────────────────────────────────
fig = plt.figure(figsize=(16, 10), facecolor='#F4F6F9')
gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.4, wspace=0.35)

plot_cfg = [
    ('K (nghìn tỷ VND)',  K_o[:T], 'K',  (0,0)),
    ('D (% GDP)',          D_o[:T], 'D',  (0,1)),
    ('AI (nghìn DN số)',  AI_o[:T], 'AI', (0,2)),
    ('H (% lao động)',     H_o[:T], 'H',  (1,0)),
    ('Y – Sản lượng (tỷ)', Y_o,    'Y',  (1,1)),
    ('C – Tiêu dùng (tỷ)', C_o,    'C',  (1,2)),
]

for label, data, key, pos in plot_cfg:
    ax = fig.add_subplot(gs[pos[0], pos[1]])
    ax.plot(YEARS, data, marker='o', color=COLORS[key],
            linewidth=2.2, markersize=5)
    ax.fill_between(YEARS, data, alpha=0.12, color=COLORS[key])
    ax.set_title(label, fontsize=10, fontweight='bold', color=COLORS[key])
    ax.set_xlabel('Năm', fontsize=8)
    ax.tick_params(labelsize=8)
    ax.grid(alpha=0.3)
    ax.set_facecolor('#F4F6F9')

fig.suptitle("CÂU 8.3.2 — Quỹ đạo tối ưu liên thời gian 2026-2035\n"
             f"(Welfare W* = {-res_base.fun:.4f}, SLSQP, TFP +1.5%/năm)",
             fontsize=13, fontweight='bold', color='#1B4F72')
plt.show()

# Tỷ lệ I_AI / I_H theo thời gian
ratio = np.where(IH_o > 1e-6, IAI_o / IH_o, 0)
print(f"\n📊 Tỷ lệ I_AI / I_H theo năm:")
for t in range(T):
    print(f"   {YEARS[t]}: I_AI={IAI_o[t]:.2f}  I_H={IH_o[t]:.3f}  "
          f"Tỷ lệ={ratio[t]:.2f}")

# ============================================================
# CELL 4 — CÂU 8.3.3
# Cú sốc năm 2028: Y giảm 8% (như bão Yagi 2024)
# So sánh quỹ đạo có/không cú sốc
# ============================================================
print("=" * 65)
print("CÂU 8.3.3 — PHÂN TÍCH CÚ SỐC NĂM 2028 (Y GIẢM 8%)")
print("=" * 65)

# 2028 = t=2 (2026→t0, 2027→t1, 2028→t2)
print("\n⏳ Đang tối ưu kịch bản có cú sốc...\n")
res_shock = solve_optimal(shock_year=2, shock_pct=0.08)

traj_s = simulate(res_shock.x, shock_year=2, shock_pct=0.08)
Y_s, C_s   = traj_s['Y'], traj_s['C']
IK_s, ID_s = traj_s['IK'], traj_s['ID']
IAI_s, IH_s= traj_s['IAI'], traj_s['IH']
K_s, D_s, AI_s, H_s = traj_s['K'], traj_s['D'], traj_s['AI'], traj_s['H']

print(f"Welfare KHÔNG cú sốc : {-res_base.fun:.4f}")
print(f"Welfare CÓ cú sốc    : {-res_shock.fun:.4f}")
print(f"Thiệt hại welfare    : {-res_base.fun - (-res_shock.fun):.4f}")

# Bảng so sánh đầu tư trước và sau cú sốc
print(f"\n{'Năm':<6} {'Y_base':>10} {'Y_shock':>10} {'ΔY':>8} "
      f"{'IK_b':>8} {'IK_s':>8} {'IH_b':>8} {'IH_s':>8}")
print("─" * 70)
for t in range(T):
    dy = Y_s[t] - Y_o[t]
    print(f"{YEARS[t]:<6} {Y_o[t]:>10.1f} {Y_s[t]:>10.1f} {dy:>+8.1f} "
          f"{IK_o[t]:>8.1f} {IK_s[t]:>8.1f} "
          f"{IH_o[t]:>8.3f} {IH_s[t]:>8.3f}")

# ── Biểu đồ so sánh Y và C ────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5), facecolor='#F4F6F9')

for ax, (data_b, data_s, label) in zip(axes, [
    (Y_o, Y_s, 'Sản lượng Y (tỷ VND)'),
    (C_o, C_s, 'Tiêu dùng C (tỷ VND)'),
]):
    ax.plot(YEARS, data_b, 'o-', color='#1B4F72', lw=2,
            label='Không cú sốc')
    ax.plot(YEARS, data_s, 's--', color='#E74C3C', lw=2,
            label='Cú sốc 2028 (-8%)')
    ax.axvline(2028, color='#E74C3C', linestyle=':', lw=1.5, alpha=0.7)
    ax.annotate('Cú sốc\n2028', xy=(2028, min(data_s)*1.01),
                fontsize=8, color='#E74C3C', ha='center')
    ax.set_title(label, fontsize=11, fontweight='bold', color='#1B4F72')
    ax.set_xlabel('Năm', fontsize=9)
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)
    ax.set_facecolor('#F4F6F9')

plt.suptitle("CÂU 8.3.3 — Tác động cú sốc 2028 và điều chỉnh phân bổ",
             fontsize=13, fontweight='bold', color='#1B4F72')
plt.tight_layout()
plt.show()

# So sánh đầu tư trước/sau cú sốc
fig, axes = plt.subplots(1, 2, figsize=(14, 5), facecolor='#F4F6F9')
labels_inv = ['I_K', 'I_D', 'I_AI', 'I_H']
base_inv  = [IK_o, ID_o*1000, IAI_o*100, IH_o*1000]  # scale để dễ so sánh
shock_inv = [IK_s, ID_s*1000, IAI_s*100, IH_s*1000]

for ax, (b_inv, s_inv, lbl, col) in zip(
    axes,
    [(IK_o, IK_s, 'I_K (nghìn tỷ VND)', '#1B4F72'),
     (IH_o, IH_s, 'I_H (% lao động)',   '#D35400')]
):
    ax.plot(YEARS, b_inv, 'o-', color=col, lw=2, label='Không cú sốc')
    ax.plot(YEARS, s_inv, 's--', color='#E74C3C', lw=2, label='Cú sốc 2028')
    ax.axvline(2028, color='gray', ls=':', lw=1.2, alpha=0.6)
    ax.set_title(lbl, fontsize=11, fontweight='bold', color=col)
    ax.set_xlabel('Năm', fontsize=9)
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)
    ax.set_facecolor('#F4F6F9')

plt.suptitle("Điều chỉnh đầu tư sau cú sốc 2028",
             fontsize=12, fontweight='bold', color='#1B4F72')
plt.tight_layout()
plt.show()

# ============================================================
# CELL 5 — CÂU 8.3.4
# So sánh 2 chiến lược:
#   (i)  Trải đều   — mỗi năm đầu tư bằng nhau
#   (ii) Front-load — đầu tư mạnh 3 năm đầu rồi giảm dần
# Welfare tổng nào cao hơn? Vì sao?
# ============================================================
print("=" * 65)
print("CÂU 8.3.4 — SO SÁNH TRẢI ĐỀU vs FRONT-LOAD")
print("=" * 65)

# ── Chiến lược (i): Trải đều ───────────────────────────────
# Mỗi năm đầu tư cố định: 20% Y0 cho K, 0.5 cho D, 5 cho AI, 0.5 cho H
IK_even  = np.ones(T) * Y0 * 0.20
ID_even  = np.ones(T) * 0.5
IAI_even = np.ones(T) * 5.0
IH_even  = np.ones(T) * 0.5

W_even, Y_even, C_even, K_even, D_even, AI_even, H_even = \
    welfare_from_trajectory(IK_even, ID_even, IAI_even, IH_even)

# ── Chiến lược (ii): Front-load ────────────────────────────
# 3 năm đầu (2026-2028): đầu tư mạnh 35% Y0
# 7 năm sau (2029-2035): đầu tư thấp 10% Y0
IK_fl  = np.array([Y0*0.35]*3 + [Y0*0.10]*7)
ID_fl  = np.array([1.5]*3     + [0.2]*7)
IAI_fl = np.array([15.0]*3    + [3.0]*7)
IH_fl  = np.array([1.5]*3     + [0.2]*7)

W_fl, Y_fl, C_fl, K_fl, D_fl, AI_fl, H_fl = \
    welfare_from_trajectory(IK_fl, ID_fl, IAI_fl, IH_fl)

# ── Bảng so sánh chính ─────────────────────────────────────
print(f"\n{'Chiến lược':<20} {'Welfare':>12}   Nhận xét")
print("─" * 55)
print(f"{'(i)  Trải đều':<20} {W_even:>12.4f}   Baseline")
print(f"{'(ii) Front-load':<20} {W_fl:>12.4f}   "
      f"{'CAO HƠN ✅' if W_fl > W_even else 'THẤP HƠN'} "
      f"{abs(W_fl-W_even):.4f} điểm")

winner = "Front-load" if W_fl > W_even else "Trải đều"
print(f"\n► Chiến lược {winner} cho welfare cao hơn")
print(f"  Chênh lệch: {abs(W_fl - W_even):.4f} điểm welfare")

# ── Bảng Y và C từng năm ───────────────────────────────────
print(f"\n{'Năm':<6} {'Y_even':>10} {'Y_fl':>10}  "
      f"{'C_even':>10} {'C_fl':>10}  {'ΔC (fl-even)':>13}")
print("─" * 65)
for t in range(T):
    dc = C_fl[t] - C_even[t]
    print(f"{YEARS[t]:<6} {Y_even[t]:>10.1f} {Y_fl[t]:>10.1f}  "
          f"{C_even[t]:>10.1f} {C_fl[t]:>10.1f}  {dc:>+13.1f}")

# ── Vẽ biểu đồ so sánh ────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(14, 10), facecolor='#F4F6F9')
axes = axes.flatten()

# Panel 1: Quỹ đạo Y
axes[0].plot(YEARS, Y_even, 's--', color='#1E8449', lw=2, label='(i) Trải đều')
axes[0].plot(YEARS, Y_fl,   'o-',  color='#D35400', lw=2, label='(ii) Front-load')
axes[0].axvline(2028, color='gray', ls=':', lw=1.2, alpha=0.6)
axes[0].text(2028.1, min(Y_even)*1.005, '←3 năm\nđầu tư mạnh', fontsize=8, color='gray')
axes[0].set_title('Sản lượng Y (tỷ VND)', fontsize=11, fontweight='bold', color='#1B4F72')
axes[0].legend(fontsize=9); axes[0].grid(alpha=0.3)
axes[0].set_xlabel('Năm', fontsize=9)
axes[0].set_facecolor('#F4F6F9')

# Panel 2: Quỹ đạo C
axes[1].plot(YEARS, C_even, 's--', color='#1E8449', lw=2, label='(i) Trải đều')
axes[1].plot(YEARS, C_fl,   'o-',  color='#D35400', lw=2, label='(ii) Front-load')
axes[1].axvline(2028, color='gray', ls=':', lw=1.2, alpha=0.6)
axes[1].set_title('Tiêu dùng C (tỷ VND)', fontsize=11, fontweight='bold', color='#1B4F72')
axes[1].legend(fontsize=9); axes[1].grid(alpha=0.3)
axes[1].set_xlabel('Năm', fontsize=9)
axes[1].set_facecolor('#F4F6F9')

# Panel 3: Quỹ đạo K (vốn tích lũy)
axes[2].plot(YEARS, K_even[:T], 's--', color='#1E8449', lw=2, label='(i) Trải đều')
axes[2].plot(YEARS, K_fl[:T],   'o-',  color='#D35400', lw=2, label='(ii) Front-load')
axes[2].set_title('Vốn vật chất K (nghìn tỷ VND)', fontsize=11, fontweight='bold', color='#1B4F72')
axes[2].legend(fontsize=9); axes[2].grid(alpha=0.3)
axes[2].set_xlabel('Năm', fontsize=9)
axes[2].set_facecolor('#F4F6F9')

# Panel 4: Bar welfare so sánh
labels_w  = ['(i) Trải đều', '(ii) Front-load']
values_w  = [W_even, W_fl]
bar_cols  = ['#1E8449', '#D35400']
bars = axes[3].bar(labels_w, values_w, color=bar_cols,
                   edgecolor='white', width=0.4)
for bar, val in zip(bars, values_w):
    axes[3].text(bar.get_x() + bar.get_width()/2,
                 val + 0.02, f'{val:.4f}',
                 ha='center', fontsize=10, fontweight='bold')
axes[3].set_title('So sánh Welfare tổng\nW = Σ ρᵗ ln(Cₜ)',
                  fontsize=11, fontweight='bold', color='#1B4F72')
axes[3].set_ylabel('Welfare', fontsize=9)
axes[3].set_ylim(min(values_w)*0.998, max(values_w)*1.005)
axes[3].grid(axis='y', alpha=0.3)
axes[3].set_facecolor('#F4F6F9')

plt.suptitle("CÂU 8.3.4 — So sánh chiến lược Trải đều vs Front-load",
             fontsize=13, fontweight='bold', color='#1B4F72')
plt.tight_layout()
plt.show()

# ── Giải thích kinh tế ─────────────────────────────────────
print(f"\n💡 Giải thích kinh tế:")
print(f"   Front-load đầu tư mạnh 3 năm đầu → K, D, AI, H tích lũy nhanh")
print(f"   → Y các năm sau cao hơn → C các năm sau cao hơn")
print(f"   → Welfare tổng {'cao hơn' if W_fl > W_even else 'thấp hơn'} trải đều")
print(f"   Tuy nhiên 3 năm đầu C thấp hơn (hi sinh tiêu dùng hiện tại)")
print(f"   → Đánh đổi giữa tiêu dùng hiện tại và tăng trưởng tương lai")