# -*- coding: utf-8 -*-
"""Bai02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rlsDRhpPHBZgctgkvWzVQ93Zi2XBZWYJ
"""

# Cài PuLP (chỉ cần chạy 1 lần)
!pip install pulp -q

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from scipy.optimize import linprog
import pulp

print("✅ Thư viện sẵn sàng!")

# ═══════════════════════════════════════════════════════════════
# CÂU 2.4.1 — Giải bằng scipy.optimize.linprog
# Hàm mục tiêu: max Z = 0.85x1 + 1.20x2 + 0.95x3 + 1.35x4
# scipy chỉ MINIMIZE → đổi thành minimize -Z
# ═══════════════════════════════════════════════════════════════

# Hệ số hàm mục tiêu (đổi dấu vì scipy minimize)
c = [-0.85, -1.20, -0.95, -1.35]

# Ma trận ràng buộc A_ub @ x <= b_ub
# Ràng buộc 1: x1+x2+x3+x4 <= 100
# Ràng buộc 2: x1 >= 25  → -x1 <= -25
# Ràng buộc 3: x2 >= 15  → -x2 <= -15
# Ràng buộc 4: x3 >= 20  → -x3 <= -20
# Ràng buộc 5: x4 >= 10  → -x4 <= -10
# Ràng buộc 6: x2+x4 >= 0.35*(x1+x2+x3+x4)
#            → 0.35x1 - 0.65x2 + 0.35x3 - 0.65x4 <= 0

A_ub = [
    [ 1,     1,     1,     1   ],  # tổng ngân sách
    [-1,     0,     0,     0   ],  # x1 >= 25
    [ 0,    -1,     0,     0   ],  # x2 >= 15
    [ 0,     0,    -1,     0   ],  # x3 >= 20
    [ 0,     0,     0,    -1   ],  # x4 >= 10
    [ 0.35, -0.65,  0.35, -0.65],  # công nghệ chiến lược >= 35%
]
b_ub = [100, -25, -15, -20, -10, 0]

# Giới hạn biến: xi >= 0
bounds = [(0, None)] * 4

# Giải
res = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method='highs')

# In kết quả
labels = ['x₁ — Hạ tầng số',
          'x₂ — AI & Dữ liệu',
          'x₃ — Nhân lực số',
          'x₄ — R&D CN']

print("=" * 55)
print("CÂU 2.4.1 — KẾT QUẢ TỐI ƯU (scipy.linprog)")
print("=" * 55)
print(f"  Trạng thái: {res.message}")
print()
for lb, val in zip(labels, res.x):
    print(f"  {lb:22s} = {val:7.4f} nghìn tỷ VND")
print()
print(f"  Tổng đầu tư    = {res.x.sum():.4f} nghìn tỷ VND")
print(f"  Z* (GDP tăng)  = {-res.fun:.4f} nghìn tỷ VND")
print()

# Kiểm tra ràng buộc công nghệ chiến lược
x1,x2,x3,x4 = res.x
cn_ratio = (x2+x4)/(x1+x2+x3+x4)*100
print(f"  Kiểm tra: (x2+x4)/tổng = {cn_ratio:.1f}% "
      f"(yêu cầu ≥ 35%) {'✅' if cn_ratio >= 35 else '❌'}")

# ═══════════════════════════════════════════════════════════════
# CÂU 2.4.2 — Giải bằng PuLP, lấy Shadow Price (giá đối ngẫu)
# ═══════════════════════════════════════════════════════════════

model = pulp.LpProblem("Phan_bo_ngan_sach_so", pulp.LpMaximize)

# Biến quyết định
x1 = pulp.LpVariable("x1_HaTang",  lowBound=0)
x2 = pulp.LpVariable("x2_AI",      lowBound=0)
x3 = pulp.LpVariable("x3_NhanLuc", lowBound=0)
x4 = pulp.LpVariable("x4_RnD",     lowBound=0)

# Hàm mục tiêu
model += 0.85*x1 + 1.20*x2 + 0.95*x3 + 1.35*x4, "GDP_tang_them"

# Ràng buộc (đặt tên rõ ràng để xem shadow price)
model += x1 + x2 + x3 + x4 <= 100,              "R1_Ngan_sach_tong"
model += x1 >= 25,                               "R2_HaTang_toi_thieu"
model += x2 >= 15,                               "R3_AI_toi_thieu"
model += x3 >= 20,                               "R4_NhanLuc_toi_thieu"
model += x4 >= 10,                               "R5_RnD_toi_thieu"
model += x2 + x4 >= 0.35*(x1+x2+x3+x4),         "R6_CongNghe_ChienLuoc"

# Giải
model.solve(pulp.PULP_CBC_CMD(msg=False))

# Kết quả phân bổ
print("=" * 60)
print("CÂU 2.4.2 — KẾT QUẢ TỐI ƯU (PuLP)")
print("=" * 60)
sol = [x1.value(), x2.value(), x3.value(), x4.value()]
for lb, v in zip(labels, sol):
    print(f"  {lb:22s} = {v:7.4f} nghìn tỷ VND")
print()
print(f"  Tổng đầu tư    = {sum(sol):.4f} nghìn tỷ VND")
Z_base = pulp.value(model.objective)
print(f"  Z* (GDP tăng)  = {Z_base:.4f} nghìn tỷ VND")

# Shadow Price
print()
print("=" * 60)
print("SHADOW PRICE (Giá đối ngẫu) — Từng ràng buộc")
print("=" * 60)
ten_rang_buoc = {
    'R1_Ngan_sach_tong'     : 'Ngân sách tổng (≤100)',
    'R2_HaTang_toi_thieu'   : 'Hạ tầng tối thiểu (≥25)',
    'R3_AI_toi_thieu'       : 'AI tối thiểu (≥15)',
    'R4_NhanLuc_toi_thieu'  : 'Nhân lực tối thiểu (≥20)',
    'R5_RnD_toi_thieu'      : 'R&D tối thiểu (≥10)',
    'R6_CongNghe_ChienLuoc' : 'CN chiến lược (≥35%)',
}
sp_values = {}
for name, constraint in model.constraints.items():
    sp = constraint.pi
    sp_values[name] = sp
    ten = ten_rang_buoc.get(name, name)
    print(f"  {ten:35s}: {sp:+.4f}")

print()
sp_r1 = sp_values.get('R1_Ngan_sach_tong', 0)
print("─" * 60)
print("📌 GIẢI THÍCH SHADOW PRICE — Ràng buộc ngân sách tổng:")
print(f"   Shadow price = {sp_r1:.4f}")
print(f"   → Nếu tăng ngân sách thêm 1 nghìn tỷ VND,")
print(f"     GDP kỳ vọng tăng thêm {sp_r1:.4f} nghìn tỷ VND")
print(f"   → Đây là 'giá trị cận biên' của 1 đồng ngân sách công")
print(f"   → Hàm ý: chi phí cơ hội vốn công ≈ {sp_r1:.4f}")

# ═══════════════════════════════════════════════════════════════
# CÂU 2.4.3 — Phân tích độ nhạy: B tăng từ 100 → 140
# ═══════════════════════════════════════════════════════════════

def giai_LP(budget, x3_min=20):
    """Hàm giải LP với ngân sách B và ràng buộc x3 tùy chọn"""
    m = pulp.LpProblem("LP", pulp.LpMaximize)
    v1 = pulp.LpVariable("x1", lowBound=0)
    v2 = pulp.LpVariable("x2", lowBound=0)
    v3 = pulp.LpVariable("x3", lowBound=0)
    v4 = pulp.LpVariable("x4", lowBound=0)

    m += 0.85*v1 + 1.20*v2 + 0.95*v3 + 1.35*v4
    m += v1 + v2 + v3 + v4 <= budget
    m += v1 >= 25
    m += v2 >= 15
    m += v3 >= x3_min
    m += v4 >= 10
    m += v2 + v4 >= 0.35*(v1+v2+v3+v4)

    m.solve(pulp.PULP_CBC_CMD(msg=False))

    if pulp.LpStatus[m.status] == 'Optimal':
        return {
            'status' : 'Optimal',
            'Z'      : pulp.value(m.objective),
            'x1'     : v1.value(), 'x2': v2.value(),
            'x3'     : v3.value(), 'x4': v4.value()
        }
    return {'status': 'Infeasible', 'Z': None}

# Chạy với B từ 70 → 160 (để thấy toàn cảnh)
budgets  = list(range(70, 165, 5))
Z_list   = []
x_allocs = {'x1':[], 'x2':[], 'x3':[], 'x4':[]}

for B in budgets:
    r = giai_LP(B)
    Z_list.append(r['Z'])
    for k in x_allocs:
        x_allocs[k].append(r.get(k, 0))

# Bảng kết quả tại các mốc quan trọng
print("=" * 65)
print("CÂU 2.4.3 — PHÂN TÍCH ĐỘ NHẠY: Z*(B)")
print("=" * 65)
moc = [100, 110, 120, 130, 140]
print(f"  {'B':>6} | {'Z*':>10} | {'x1':>7} | {'x2':>7} | "
      f"{'x3':>7} | {'x4':>7} | {'ΔZ/ΔB':>8}")
print("  " + "-"*63)
Z_prev = None
for B in moc:
    r = giai_LP(B)
    dz = (r['Z'] - Z_prev) / 10 if Z_prev else 0
    print(f"  {B:>6} | {r['Z']:>10.4f} | {r['x1']:>7.2f} | "
          f"{r['x2']:>7.2f} | {r['x3']:>7.2f} | {r['x4']:>7.2f} | "
          f"{dz:>8.4f}")
    Z_prev = r['Z']

# ── Vẽ đồ thị ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Đồ thị 1: Đường cong Z*(B)
ax1 = axes[0]
ax1.plot(budgets, Z_list, 'o-', color='steelblue',
         linewidth=2.5, markersize=6)

# Đánh dấu 3 mốc đề bài yêu cầu
for B_mark, col in [(100,'tomato'), (120,'green'), (140,'purple')]:
    idx = budgets.index(B_mark)
    ax1.axvline(x=B_mark, color=col, linewidth=1.5,
                linestyle='--', alpha=0.7)
    ax1.scatter(B_mark, Z_list[idx], color=col,
                s=120, zorder=5)
    ax1.annotate(f'B={B_mark}\nZ*={Z_list[idx]:.2f}',
                 xy=(B_mark, Z_list[idx]),
                 xytext=(8, -25), textcoords='offset points',
                 fontsize=8.5, color=col, fontweight='bold')

ax1.set_title('Đường cong Z*(B) — GDP tối ưu theo ngân sách',
              fontsize=12, fontweight='bold')
ax1.set_xlabel('Ngân sách tổng B (nghìn tỷ VND)')
ax1.set_ylabel('Z* — GDP tăng thêm (nghìn tỷ VND)')
ax1.grid(alpha=0.3)

# Đồ thị 2: Phân bổ tối ưu theo B (stacked bar)
ax2 = axes[1]
b_plot   = list(range(80, 155, 10))
x1_plot  = [giai_LP(B)['x1'] for B in b_plot]
x2_plot  = [giai_LP(B)['x2'] for B in b_plot]
x3_plot  = [giai_LP(B)['x3'] for B in b_plot]
x4_plot  = [giai_LP(B)['x4'] for B in b_plot]

width = 6
p1 = ax2.bar(b_plot, x1_plot, width, label='x₁ Hạ tầng',
             color='#4C9BE8', edgecolor='white')
p2 = ax2.bar(b_plot, x2_plot, width, bottom=x1_plot,
             label='x₂ AI', color='#E87A4C', edgecolor='white')
p3 = ax2.bar(b_plot, x3_plot, width,
             bottom=[a+b for a,b in zip(x1_plot,x2_plot)],
             label='x₃ Nhân lực', color='#4CE882', edgecolor='white')
p4 = ax2.bar(b_plot, x4_plot, width,
             bottom=[a+b+c for a,b,c in zip(x1_plot,x2_plot,x3_plot)],
             label='x₄ R&D', color='#E84C4C', edgecolor='white')

ax2.set_title('Phân bổ tối ưu theo ngân sách B',
              fontsize=12, fontweight='bold')
ax2.set_xlabel('Ngân sách B (nghìn tỷ VND)')
ax2.set_ylabel('Phân bổ (nghìn tỷ VND)')
ax2.legend(fontsize=9, loc='upper left')
ax2.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('bai2_cau3_sensitivity.png', dpi=150, bbox_inches='tight')
plt.show()

# ═══════════════════════════════════════════════════════════════
# CÂU 2.4.4 — Thêm ràng buộc x3 >= 30 (ưu tiên nhân lực số)
# ═══════════════════════════════════════════════════════════════

r_new = giai_LP(budget=100, x3_min=30)

print("=" * 55)
print("CÂU 2.4.4 — THÊM RÀNG BUỘC x₃ ≥ 30")
print("=" * 55)
print(f"  Trạng thái: {r_new['status']}")
print()

if r_new['status'] == 'Optimal':
    sol_new = [r_new['x1'], r_new['x2'],
               r_new['x3'], r_new['x4']]
    Z_new = r_new['Z']

    # Bảng so sánh
    print(f"  {'Biến':22s} | {'Cũ (x3≥20)':>12} | {'Mới (x3≥30)':>12} | {'Thay đổi':>10}")
    print("  " + "-" * 62)
    for lb, v_old, v_new in zip(labels, sol, sol_new):
        delta = v_new - v_old
        sign  = '+' if delta >= 0 else ''
        print(f"  {lb:22s} | {v_old:>12.4f} | {v_new:>12.4f} | "
              f"{sign}{delta:>9.4f}")
    print("  " + "-" * 62)
    print(f"  {'Tổng':22s} | {sum(sol):>12.4f} | "
          f"{sum(sol_new):>12.4f} |")
    print()
    print(f"  Z* cũ  (x3 ≥ 20) = {Z_base:.4f} nghìn tỷ VND")
    print(f"  Z* mới (x3 ≥ 30) = {Z_new:.4f} nghìn tỷ VND")
    print(f"  Chênh lệch ΔZ    = {Z_new - Z_base:.4f} nghìn tỷ VND")
    print()
    print("─" * 55)
    print("📌 GIẢI THÍCH CHÍNH SÁCH:")
    print(f"   • Bài toán VẪN KHẢ THI ✅")
    print(f"   • Ưu tiên nhân lực (x3≥30) làm Z* giảm "
          f"{abs(Z_new-Z_base):.4f} nghìn tỷ VND")
    print(f"   • Đây là 'chi phí chính sách' của việc")
    print(f"     ưu tiên đào tạo kỹ sư AI thay vì R&D")
else:
    print("  ❌ Bài toán KHÔNG KHẢ THI!")
    print("  Lý do: tổng ràng buộc tối thiểu vượt ngân sách")
    tong_min = 25 + 15 + 30 + 10
    print(f"  Kiểm tra: x1≥25 + x2≥15 + x3≥30 + x4≥10 = {tong_min} > 100? "
          f"{'Không' if tong_min<=100 else 'Có'}")

# ═══════════════════════════════════════════════════════════════
# BIỂU ĐỒ TỔNG HỢP — So sánh 2 phương án
# ═══════════════════════════════════════════════════════════════

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

colors_4 = ['#4C9BE8','#E87A4C','#4CE882','#E84C4C']
short_lb  = ['Hạ tầng\nx₁','AI\nx₂','Nhân lực\nx₃','R&D\nx₄']

# ── Biểu đồ 1: Phân bổ tối ưu cơ sở (pie) ───────────────────
ax1 = axes[0]
wedges, texts, autotexts = ax1.pie(
    sol, labels=short_lb, autopct='%1.1f%%',
    colors=colors_4, startangle=90,
    wedgeprops={'edgecolor':'white','linewidth':2},
    pctdistance=0.75)
for at in autotexts: at.set_fontsize(9)
ax1.set_title(f'Phân bổ tối ưu (x₃≥20)\nZ* = {Z_base:.2f} nghìn tỷ',
              fontsize=11, fontweight='bold')

# ── Biểu đồ 2: Phân bổ khi ưu tiên nhân lực (pie) ───────────
ax2 = axes[1]
if r_new['status'] == 'Optimal':
    wedges2, texts2, autotexts2 = ax2.pie(
        sol_new, labels=short_lb, autopct='%1.1f%%',
        colors=colors_4, startangle=90,
        wedgeprops={'edgecolor':'white','linewidth':2},
        pctdistance=0.75)
    for at in autotexts2: at.set_fontsize(9)
    ax2.set_title(f'Ưu tiên nhân lực (x₃≥30)\nZ* = {Z_new:.2f} nghìn tỷ',
                  fontsize=11, fontweight='bold')

# ── Biểu đồ 3: So sánh Z* theo B + đánh dấu 2 kịch bản ─────
ax3 = axes[2]
budgets_fine = list(range(70, 165, 2))

# Replace None with np.nan to handle infeasible points
Z_base_list = []
Z_x3_30_list = []
for B in budgets_fine:
    res_base = giai_LP(B, x3_min=20)
    Z_base_list.append(res_base['Z'] if res_base['status'] == 'Optimal' else np.nan)

    res_x3_30 = giai_LP(B, x3_min=30)
    Z_x3_30_list.append(res_x3_30['Z'] if res_x3_30['status'] == 'Optimal' else np.nan)

ax3.plot(budgets_fine, Z_base_list,  '-', color='steelblue',
         linewidth=2.5, label='x₃ ≥ 20 (cơ sở)')
ax3.plot(budgets_fine, Z_x3_30_list, '--', color='tomato',
         linewidth=2.5, label='x₃ ≥ 30 (ưu tiên NL)')
ax3.fill_between(budgets_fine, Z_base_list, Z_x3_30_list,
                 alpha=0.15, color='orange',
                 label='Chi phí chính sách')

ax3.axvline(x=100, color='gray', linewidth=1.5, linestyle=':')
ax3.scatter([100], [Z_base], color='steelblue', s=100, zorder=5)
ax3.scatter([100], [Z_new],  color='tomato',    s=100, zorder=5)
ax3.annotate(f'ΔZ = {Z_new-Z_base:.2f}',
             xy=(100, (Z_base+Z_new)/2),
             xytext=(15, 0), textcoords='offset points',
             fontsize=9, color='darkorange', fontweight='bold')

ax3.set_title('So sánh Z*(B): 2 kịch bản ràng buộc',
              fontsize=11, fontweight='bold')
ax3.set_xlabel('Ngân sách B (nghìn tỷ VND)')
ax3.set_ylabel('Z* (nghìn tỷ VND)')
ax3.legend(fontsize=9)
ax3.grid(alpha=0.3)

plt.suptitle('Bài 2 — Phân bổ ngân sách tối ưu\nLP Quy hoạch tuyến tính',
             fontsize=13, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('bai2_tong_hop.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ HOÀN THÀNH BÀI 2 — Tất cả 4 câu!")