# -*- coding: utf-8 -*-
"""Bai09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168RdfJn6vYlD0qe1mXaVQL071NIRuRNr
"""

!pip install pulp cvxpy -q

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import cvxpy as cp

# ═══════════════════════════════════════════════════════════════
# ĐỌC FILE CSV
# ═══════════════════════════════════════════════════════════════
from google.colab import drive
drive.mount('/content/drive')

DRIVE_PATH = '/content/drive/MyDrive/'

try:
    df_all = pd.read_csv(DRIVE_PATH + 'vietnam_sectors_2024.csv')
    print("✅ Đọc file từ Drive thành công!")
except:
    print("⚠️ Dùng dữ liệu cứng từ đề bài")

# ═══════════════════════════════════════════════════════════════
# LỌC 8 NGÀNH (bỏ Khai khoáng id=4, Y tế id=10)
# ═══════════════════════════════════════════════════════════════
df = df_all[~df_all['sector_id'].isin([4, 10])].reset_index(drop=True)

ten_viet = [
    'Nông-Lâm-Thủy sản',
    'CN Chế biến-Chế tạo',
    'Xây dựng',
    'Bán buôn-Bán lẻ',
    'Tài chính-Ngân hàng',
    'Logistics-Vận tải',
    'CNTT-Truyền thông',
    'Giáo dục-Đào tạo',
]
df['sector_vi'] = ten_viet
N = len(df)   # = 8

print(f"Số ngành: {N}")
print(df[['sector_vi', 'labor_million', 'automation_risk_pct']].to_string(index=False))

# ═══════════════════════════════════════════════════════════════
# THAM SỐ 8 NGÀNH — Bảng 9.3 đề bài
# ═══════════════════════════════════════════════════════════════
# Lao động (triệu người)
L = df['labor_million'].values

# Rủi ro tự động hóa (%)
risk = df['automation_risk_pct'].values / 100.0  # đổi sang tỉ lệ

# Hệ số tạo việc làm mới từ AI (việc/tỷ VND)
a1 = np.array([8.5, 32.5, 12.8, 22.4, 45.8, 28.5, 62.5, 18.5])

# Hệ số tạo việc làm mới từ CĐS (việc/tỷ VND)
a2 = np.array([12.0, 18.5, 8.5, 15.2, 12.5, 16.8, 15.0, 22.0])

# Hệ số nâng cấp việc làm từ đào tạo (việc/tỷ VND)
b1 = np.array([45.0, 28.0, 35.0, 32.0, 22.0, 30.0, 20.0, 55.0])

# Hệ số dịch chuyển/thay thế từ AI (việc/tỷ VND)
c1 = np.array([5.2, 62.4, 18.5, 48.2, 72.5, 42.8, 32.5, 12.5])

# Hệ số năng lực đào tạo lại (việc/tỷ VND)
d1 = np.array([50.0, 32.0, 42.0, 38.0, 26.0, 36.0, 24.0, 62.0])

# In bảng tham số đầy đủ
print("\n=== BẢNG THAM SỐ 8 NGÀNH ===")
df_param = pd.DataFrame({
    'Ngành'      : ten_viet,
    'LĐ (tr)'    : L,
    'Risk (%)'   : (risk*100).astype(int),
    'a1'         : a1,
    'a2'         : a2,
    'b1'         : b1,
    'c1'         : c1,
    'd1'         : d1,
})
print(df_param.to_string(index=False))

# ═══════════════════════════════════════════════════════════════
# CÂU 9.4.1 — Tối đa hóa tổng NetJob
# Biến: x_AI[i], x_H[i] ≥ 0 (đầu tư AI và nhân lực mỗi ngành)
# Ràng buộc:
#   Σ(x_AI + x_H) ≤ 30.000 tỷ
#   NetJob[i] ≥ 0 ∀i
#   DisplacedJob[i] ≤ RetrainingCapacity[i] ∀i
# ═══════════════════════════════════════════════════════════════

x_AI = cp.Variable(N, nonneg=True, name='x_AI')
x_H  = cp.Variable(N, nonneg=True, name='x_H')

# Thành phần NetJob
NewJob      = cp.multiply(a1, x_AI)           # việc làm AI mới
UpgradeJob  = cp.multiply(b1, x_H)            # nâng cấp từ đào tạo
DisplacedJob = cp.multiply(cp.multiply(c1, risk), x_AI)  # bị thay thế
RetrainCap  = cp.multiply(d1, x_H)            # năng lực đào tạo lại

NetJob = NewJob + UpgradeJob - DisplacedJob

# Ràng buộc
constraints = [
    cp.sum(x_AI + x_H) <= 30000,   # ngân sách tổng
    NetJob >= 0,                    # không mất việc làm ròng
    DisplacedJob <= RetrainCap,     # đào tạo lại kịp thời
    x_AI >= 0,
    x_H  >= 0,
]

# Giải
prob = cp.Problem(cp.Maximize(cp.sum(NetJob)), constraints)
prob.solve(solver=cp.HIGHS)

status = prob.status
print("=" * 65)
print("CÂU 9.4.1 — KẾT QUẢ TỐI ƯU")
print(f"Trạng thái: {status}")
print("=" * 65)

if status in ['optimal', 'optimal_inaccurate']:
    x_AI_val = x_AI.value
    x_H_val  = x_H.value

    # Tính NetJob từng ngành
    NewJob_val      = a1 * x_AI_val
    UpgradeJob_val  = b1 * x_H_val
    DisplacedJob_val = c1 * risk * x_AI_val
    RetrainCap_val  = d1 * x_H_val
    NetJob_val      = NewJob_val + UpgradeJob_val - DisplacedJob_val

    # Bảng kết quả
    df_result = pd.DataFrame({
        'Ngành'         : ten_viet,
        'x_AI (tỷ)'     : x_AI_val.round(2),
        'x_H (tỷ)'      : x_H_val.round(2),
        'Tổng ĐT (tỷ)'  : (x_AI_val + x_H_val).round(2),
        'NewJob'         : NewJob_val.round(0).astype(int),
        'UpgradeJob'     : UpgradeJob_val.round(0).astype(int),
        'DisplacedJob'   : DisplacedJob_val.round(0).astype(int),
        'RetrainCap'     : RetrainCap_val.round(0).astype(int),
        'NetJob'         : NetJob_val.round(0).astype(int),
    })
    print(df_result.to_string(index=False))
    print(f"\n  Tổng đầu tư    : {(x_AI_val+x_H_val).sum():,.2f} tỷ VND")
    print(f"  Tổng NetJob    : {NetJob_val.sum():,.0f} việc làm")
    print(f"  Tỷ lệ AI/H     : {x_AI_val.sum():.0f} / {x_H_val.sum():.0f}")

    # Kiểm tra ràng buộc
    print("\n=== KIỂM TRA RÀNG BUỘC ===")
    all_ok = True
    for i, ten in enumerate(ten_viet):
        net_ok  = NetJob_val[i] >= -0.01
        retrain_ok = DisplacedJob_val[i] <= RetrainCap_val[i] + 0.01
        status_str = "✅" if (net_ok and retrain_ok) else "❌"
        if not (net_ok and retrain_ok):
            all_ok = False
        print(f"  {status_str} {ten:22s}: "
              f"NetJob={NetJob_val[i]:>8.0f} ≥ 0  |  "
              f"Displaced={DisplacedJob_val[i]:>6.0f} ≤ "
              f"Retrain={RetrainCap_val[i]:>6.0f}")
    print(f"\n  {'✅ Tất cả ràng buộc thỏa mãn!' if all_ok else '❌ Có ràng buộc vi phạm!'}")

    # Vẽ biểu đồ phân bổ và NetJob
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # Biểu đồ 1: Phân bổ x_AI và x_H
    ax1 = axes[0]
    x_pos = np.arange(N)
    w     = 0.35
    b1_bar = ax1.bar(x_pos - w/2, x_AI_val, w,
                     label='x_AI', color='#C44CE8',
                     edgecolor='white', linewidth=1.2)
    b2_bar = ax1.bar(x_pos + w/2, x_H_val,  w,
                     label='x_H',  color='#4C9BE8',
                     edgecolor='white', linewidth=1.2)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(
        [t.replace('-', '\n') for t in ten_viet],
        fontsize=8)
    ax1.set_title('Phân bổ đầu tư tối ưu\nx_AI và x_H theo ngành',
                  fontsize=11, fontweight='bold')
    ax1.set_ylabel('Đầu tư (tỷ VND)')
    ax1.legend(); ax1.grid(axis='y', alpha=0.3)

    # Biểu đồ 2: NetJob breakdown
    ax2 = axes[1]
    ax2.bar(x_pos, NewJob_val + UpgradeJob_val,
            label='Tạo việc mới + Nâng cấp',
            color='#4CE882', edgecolor='white', linewidth=1.2)
    ax2.bar(x_pos, -DisplacedJob_val,
            label='Mất việc (Displaced)',
            color='#E84C4C', edgecolor='white', linewidth=1.2)
    ax2.plot(x_pos, NetJob_val, 'ko--',
             linewidth=2, markersize=8, label='NetJob ròng',
             zorder=5)
    ax2.axhline(y=0, color='gray', linewidth=1.5)
    for i, v in enumerate(NetJob_val):
        ax2.annotate(f'{v:,.0f}',
                     xy=(i, v + 50),
                     ha='center', fontsize=8,
                     fontweight='bold', color='navy')
    ax2.set_xticks(x_pos)
    ax2.set_xticklabels(
        [t.replace('-', '\n') for t in ten_viet],
        fontsize=8)
    ax2.set_title('Phân rã NetJob từng ngành\n'
                  'Tạo mới vs Mất việc vs Ròng',
                  fontsize=11, fontweight='bold')
    ax2.set_ylabel('Số việc làm')
    ax2.legend(fontsize=9); ax2.grid(axis='y', alpha=0.3)

    plt.suptitle('Bài 9 — Tác động AI tới Thị trường Lao động Việt Nam',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig('bai9_cau1_optimal.png', dpi=150, bbox_inches='tight')
    plt.show()

# ═══════════════════════════════════════════════════════════════
# CÂU 9.4.2 — Ngưỡng x_H tối thiểu cho ngành 2 (CN chế biến)
# để NetJob₂ ≥ 0 khi x_AI₂ tối đa
# ═══════════════════════════════════════════════════════════════
print("=" * 65)
print("CÂU 9.4.2 — NGƯỠNG ĐÀO TẠO TỐI THIỂU NGÀNH 2")
print("(CN Chế biến-Chế tạo — Rủi ro TĐH cao nhất: 42%)")
print("=" * 65)

i = 1   # index ngành 2 (0-based)

# Giải tích: NetJob₂ ≥ 0
# a1[i]·x_AI + b1[i]·x_H - c1[i]·risk[i]·x_AI ≥ 0
# (a1[i] - c1[i]·risk[i])·x_AI + b1[i]·x_H ≥ 0
net_coeff_AI = a1[i] - c1[i]*risk[i]
print(f"\n  Hệ số ròng của x_AI trong NetJob₂:")
print(f"  a1={a1[i]} - c1={c1[i]} × risk={risk[i]:.2f} "
      f"= {net_coeff_AI:.3f}")

if net_coeff_AI >= 0:
    print(f"  → x_AI tự tạo ra NetJob dương → "
          f"x_H tối thiểu = 0")
else:
    print(f"  → x_AI gây mất việc ròng "
          f"→ cần x_H bù đắp")

# Quét x_AI_2 từ 0 → 5000 tỷ
x_AI2_range = np.linspace(0, 5000, 200)
xH_min_list = []

for x_ai2 in x_AI2_range:
    # NetJob₂ ≥ 0:
    # a1·x_ai + b1·x_h - c1·risk·x_ai ≥ 0
    # x_h ≥ (c1·risk - a1)·x_ai / b1
    xH_min = max(0, (c1[i]*risk[i] - a1[i]) * x_ai2 / b1[i])
    xH_min_list.append(xH_min)

# Thêm ràng buộc Displaced ≤ RetrainCap
# c1·risk·x_ai ≤ d1·x_h → x_h ≥ c1·risk·x_ai / d1
xH_retrain_list = [
    c1[i]*risk[i]*x_ai2 / d1[i]
    for x_ai2 in x_AI2_range
]
xH_binding = [max(a, b) for a, b in
              zip(xH_min_list, xH_retrain_list)]

# Điểm khi x_AI₂ = tối đa trong kịch bản cơ sở
x_AI2_opt = x_AI_val[i]
xH2_min   = max(
    (c1[i]*risk[i] - a1[i]) * x_AI2_opt / b1[i],
    c1[i]*risk[i]*x_AI2_opt / d1[i],
    0
)
print(f"\n  Khi x_AI₂ = {x_AI2_opt:.2f} tỷ (từ câu 9.4.1):")
print(f"  x_H₂ tối thiểu (NetJob≥0)      = {(c1[i]*risk[i]-a1[i])*x_AI2_opt/b1[i]:.2f} tỷ")
print(f"  x_H₂ tối thiểu (Retrain đủ)    = {c1[i]*risk[i]*x_AI2_opt/d1[i]:.2f} tỷ")
print(f"  ⟹ x_H₂ ràng buộc chặt nhất    = {xH2_min:.2f} tỷ")
print(f"  x_H₂ trong nghiệm tối ưu       = {x_H_val[i]:.2f} tỷ "
      f"{'✅' if x_H_val[i] >= xH2_min-0.01 else '❌'}")

# Vẽ đồ thị
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(x_AI2_range, xH_min_list,
        color='#4C9BE8', linewidth=2.5,
        label='x_H₂ min (NetJob ≥ 0)')
ax.plot(x_AI2_range, xH_retrain_list,
        color='#E87A4C', linewidth=2.5, linestyle='--',
        label='x_H₂ min (Retrain đủ)')
ax.plot(x_AI2_range, xH_binding,
        color='#E84C4C', linewidth=2.5, linestyle='-.',
        label='x_H₂ ràng buộc chặt nhất')

ax.axvline(x=x_AI2_opt, color='purple',
           linewidth=2, linestyle=':',
           label=f'x_AI₂ tối ưu = {x_AI2_opt:.0f} tỷ')
ax.scatter([x_AI2_opt], [xH2_min],
           color='red', s=150, zorder=5,
           label=f'Ngưỡng x_H₂ = {xH2_min:.1f} tỷ')

ax.set_title('Ngưỡng đầu tư đào tạo tối thiểu — Ngành CN Chế biến\n'
             'để NetJob₂ ≥ 0 theo mức đầu tư AI',
             fontsize=12, fontweight='bold')
ax.set_xlabel('x_AI₂ (tỷ VND)')
ax.set_ylabel('x_H₂ tối thiểu (tỷ VND)')
ax.legend(fontsize=9); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('bai9_cau2_threshold.png', dpi=150, bbox_inches='tight')
plt.show()

# ═══════════════════════════════════════════════════════════════
# CÂU 9.4.3 — Tác động nhóm dễ tổn thương: ngành 1, 3, 4
# (Nông-Lâm-Thủy sản, Xây dựng, Bán buôn-Bán lẻ)
# ═══════════════════════════════════════════════════════════════
print("=" * 65)
print("CÂU 9.4.3 — TÁC ĐỘNG TỚI NHÓM LAO ĐỘNG DỄ TỔN THƯƠNG")
print("Ngành 1 (Nông-Lâm), Ngành 3 (Xây dựng), Ngành 4 (BB-BL)")
print("=" * 65)

vulnerable_idx = [0, 2, 3]   # index 0-based: ngành 1,3,4

print("\n=== PHÂN TÍCH CHI TIẾT NHÓM DỄ TỔN THƯƠNG ===")
print(f"  {'Ngành':22s} | {'LĐ (tr)':>8} | {'Risk':>6} | "
      f"{'Displaced':>10} | {'Retrain':>10} | {'NetJob':>10}")
print("  " + "─" * 75)

tong_LĐ       = 0
tong_displaced = 0
tong_retrain   = 0
tong_netjob    = 0

for i in vulnerable_idx:
    displaced = DisplacedJob_val[i]
    retrain   = RetrainCap_val[i]
    netjob    = NetJob_val[i]
    tong_LĐ        += L[i]
    tong_displaced += displaced
    tong_retrain   += retrain
    tong_netjob    += netjob
    print(f"  {ten_viet[i]:22s} | {L[i]:>8.2f} | "
          f"{risk[i]*100:>5.0f}% | {displaced:>10.0f} | "
          f"{retrain:>10.0f} | {netjob:>10.0f}")
print("  " + "─" * 75)
print(f"  {'TỔNG':22s} | {tong_LĐ:>8.2f} | {'':>6} | "
      f"{tong_displaced:>10.0f} | {tong_retrain:>10.0f} | "
      f"{tong_netjob:>10.0f}")

# Vẽ Sankey đơn giản bằng matplotlib
fig, axes = plt.subplots(1, 2, figsize=(14, 7))

# Biểu đồ 1: Luồng dịch chuyển lao động (Sankey đơn giản)
ax1 = axes[0]
ax1.set_xlim(0, 10); ax1.set_ylim(0, 10)
ax1.axis('off')
ax1.set_title('Luồng dịch chuyển lao động\nNhóm dễ tổn thương',
              fontsize=12, fontweight='bold')

# Màu ngành
mau_ng = ['#4CE882', '#E8D84C', '#4C9BE8']
ten_ng = ['Nông-Lâm-\nThủy sản',
          'Xây dựng',
          'Bán buôn-\nBán lẻ']

# Khối bên trái: Lao động hiện tại
y_positions = [7.5, 5.0, 2.5]
for k, (i, y_pos) in enumerate(zip(vulnerable_idx, y_positions)):
    width_box = 1.5
    height_box = L[i] / max(L[vulnerable_idx]) * 1.8
    rect = plt.Rectangle((0.5, y_pos - height_box/2),
                          width_box, height_box,
                          color=mau_ng[k], alpha=0.8,
                          linewidth=2, edgecolor='white')
    ax1.add_patch(rect)
    ax1.text(1.25, y_pos, f'{ten_ng[k]}\n{L[i]:.1f}M LĐ',
             ha='center', va='center', fontsize=8.5,
             fontweight='bold', color='white')

# Mũi tên và khối kết quả
resultados = [
    ('Đào tạo lại\n→ Việc mới',  '#4CE882', 0.6),
    ('Giữ nguyên\n(Upgrade)',    '#4C9BE8', 0.3),
    ('Mất việc\n(Displaced)',    '#E84C4C', 0.1),
]
y_result = [7.5, 5.0, 2.5]
for k, (label, color, fraction) in enumerate(resultados):
    # Mũi tên
    ax1.annotate('', xy=(7.5, y_result[k]),
                 xytext=(2.0, y_result[k]),
                 arrowprops=dict(arrowstyle='->', color='gray',
                                 lw=2))
    # Khối kết quả
    h = fraction * 2.5
    rect2 = plt.Rectangle((7.5, y_result[k] - h/2),
                           1.5, h, color=color, alpha=0.8,
                           linewidth=2, edgecolor='white')
    ax1.add_patch(rect2)
    ax1.text(8.25, y_result[k], label,
             ha='center', va='center', fontsize=8,
             fontweight='bold', color='white')

# Biểu đồ 2: Stacked bar nhóm dễ tổn thương
ax2 = axes[1]
x_v = np.arange(len(vulnerable_idx))
new_v  = [NewJob_val[i]     for i in vulnerable_idx]
upg_v  = [UpgradeJob_val[i] for i in vulnerable_idx]
dis_v  = [DisplacedJob_val[i] for i in vulnerable_idx]
net_v  = [NetJob_val[i]     for i in vulnerable_idx]

ax2.bar(x_v, new_v,  label='Việc làm AI mới',
        color='#C44CE8', edgecolor='white', linewidth=1.2)
ax2.bar(x_v, upg_v,  bottom=new_v,
        label='Nâng cấp (Upgrade)',
        color='#4C9BE8', edgecolor='white', linewidth=1.2)
ax2.bar(x_v, [-d for d in dis_v],
        label='Mất việc (Displaced)',
        color='#E84C4C', edgecolor='white', linewidth=1.2,
        alpha=0.8)

# Đường NetJob
ax2.plot(x_v, net_v, 'ko--', linewidth=2.5,
         markersize=10, label='NetJob ròng', zorder=5)
for i, v in enumerate(net_v):
    ax2.annotate(f'{v:,.0f}',
                 xy=(i, v + 20),
                 ha='center', fontsize=9.5,
                 fontweight='bold', color='navy')

ax2.axhline(y=0, color='black', linewidth=1.5)
ax2.set_xticks(x_v)
ax2.set_xticklabels(ten_ng, fontsize=10)
ax2.set_title('Tác động tới nhóm dễ tổn thương\n'
              'Tạo mới vs Mất việc vs NetJob',
              fontsize=12, fontweight='bold')
ax2.set_ylabel('Số việc làm')
ax2.legend(fontsize=9); ax2.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('bai9_cau3_vulnerable.png', dpi=150, bbox_inches='tight')
plt.show()

# ═══════════════════════════════════════════════════════════════
# CÂU 9.4.4 — Thêm ràng buộc: DisplacedJob[i] ≤ 5% × L[i] triệu
# L[i] tính bằng triệu người → đổi sang người: × 1.000.000
# c1 tính bằng việc/tỷ VND
# ═══════════════════════════════════════════════════════════════
print("=" * 65)
print("CÂU 9.4.4 — RÀNG BUỘC KHÔNG MẤT QUÁ 5% LAO ĐỘNG")
print("DisplacedJob[i] ≤ 0.05 × L[i] × 1.000.000")
print("=" * 65)

x_AI2 = cp.Variable(N, nonneg=True)
x_H2  = cp.Variable(N, nonneg=True)

NewJob2      = cp.multiply(a1, x_AI2)
UpgradeJob2  = cp.multiply(b1, x_H2)
DisplacedJob2 = cp.multiply(cp.multiply(c1, risk), x_AI2)
RetrainCap2  = cp.multiply(d1, x_H2)
NetJob2      = NewJob2 + UpgradeJob2 - DisplacedJob2

# Ràng buộc gốc
constraints2 = [
    cp.sum(x_AI2 + x_H2) <= 30000,
    NetJob2 >= 0,
    DisplacedJob2 <= RetrainCap2,
    x_AI2 >= 0,
    x_H2  >= 0,
]

# ★ Ràng buộc mới: DisplacedJob[i] ≤ 5% × L[i] × 1.000.000
# c1[i] × risk[i] × x_AI[i] ≤ 0.05 × L[i] × 1.000.000
L_nguoi = L * 1e6   # đổi triệu → người
for i_ng in range(N):
    constraints2.append(
        c1[i_ng] * risk[i_ng] * x_AI2[i_ng]
        <= 0.05 * L_nguoi[i_ng]
    )

prob2 = cp.Problem(cp.Maximize(cp.sum(NetJob2)), constraints2)
prob2.solve(solver=cp.HIGHS)

status2 = prob2.status
print(f"\nTrạng thái: {status2}")

if status2 in ['optimal', 'optimal_inaccurate']:
    x_AI2_val = x_AI2.value
    x_H2_val  = x_H2.value
    displaced2 = c1 * risk * x_AI2_val
    netjob2    = a1*x_AI2_val + b1*x_H2_val - displaced2

    print(f"\n✅ Bài toán VẪN KHẢ THI với ràng buộc 5%!")

    # So sánh với câu 9.4.1
    print("\n=== SO SÁNH: Không ràng buộc 5% vs Có ràng buộc 5% ===")
    print(f"  {'Ngành':22s} | {'NetJob gốc':>12} | "
          f"{'NetJob mới':>12} | {'Displaced gốc':>14} | "
          f"{'Displaced mới':>14} | {'5% L':>10}")
    print("  " + "─" * 90)
    for i in range(N):
        limit = 0.05 * L_nguoi[i]
        print(f"  {ten_viet[i]:22s} | "
              f"{NetJob_val[i]:>12.0f} | "
              f"{netjob2[i]:>12.0f} | "
              f"{DisplacedJob_val[i]:>14.0f} | "
              f"{displaced2[i]:>14.0f} | "
              f"{limit:>10.0f}")

    print(f"\n  Tổng NetJob gốc  = {NetJob_val.sum():>12,.0f}")
    print(f"  Tổng NetJob mới  = {netjob2.sum():>12,.0f}")
    delta = netjob2.sum() - NetJob_val.sum()
    print(f"  Thay đổi ΔNetJob = {delta:>12,.0f} "
          f"({'tăng ↑' if delta > 0 else 'giảm ↓'})")
    print(f"\n  📌 Chi phí của ràng buộc bảo vệ lao động:")
    print(f"     Giảm {abs(delta):,.0f} việc làm ròng "
          f"({abs(delta/NetJob_val.sum()*100):.1f}%)")
else:
    print(f"\n❌ Bài toán KHÔNG KHẢ THI với ràng buộc 5%!")
    print("  Kiểm tra ngành có L nhỏ + c1×risk cao:")
    for i in range(N):
        limit = 0.05 * L_nguoi[i]
        max_xAI = limit / (c1[i]*risk[i]) if c1[i]*risk[i] > 0 else np.inf
        print(f"  {ten_viet[i]:22s}: x_AI ≤ {max_xAI:,.0f} tỷ "
              f"(limit {limit:,.0f} việc)")

# ═══════════════════════════════════════════════════════════════
# BIỂU ĐỒ TỔNG HỢP
# ═══════════════════════════════════════════════════════════════
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Bài 9 — Tác động AI tới Thị trường Lao động Việt Nam\n'
             'Mô hình NetJob tối ưu — Ngân sách 30.000 tỷ VND',
             fontsize=14, fontweight='bold')

mau_ng = ['#E84C4C','#E87A4C','#E8C44C','#4CE882',
          '#4C9BE8','#4CE8D8','#C44CE8','#E84C88']

# Biểu đồ 1: Phân bổ đầu tư tối ưu
ax1 = axes[0, 0]
x_pos = np.arange(N)
w_bar = 0.35
ax1.bar(x_pos - w_bar/2, x_AI_val, w_bar,
        label='x_AI', color='#C44CE8',
        edgecolor='white', linewidth=1.2)
ax1.bar(x_pos + w_bar/2, x_H_val, w_bar,
        label='x_H', color='#4C9BE8',
        edgecolor='white', linewidth=1.2)
ax1.set_xticks(x_pos)
ax1.set_xticklabels([t.split('-')[0] for t in ten_viet],
                    fontsize=8.5, rotation=15)
ax1.set_title('Phân bổ đầu tư tối ưu\nx_AI vs x_H',
              fontsize=11, fontweight='bold')
ax1.set_ylabel('Đầu tư (tỷ VND)')
ax1.legend(); ax1.grid(axis='y', alpha=0.3)

# Biểu đồ 2: NetJob từng ngành
ax2 = axes[0, 1]
colors_bar = ['#4CE882' if v >= 0 else '#E84C4C'
              for v in NetJob_val]
bars2 = ax2.bar(x_pos, NetJob_val, color=colors_bar,
                edgecolor='white', linewidth=1.2)
for bar, val in zip(bars2, NetJob_val):
    ypos = val + 20 if val >= 0 else val - 80
    ax2.text(bar.get_x() + bar.get_width()/2, ypos,
             f'{val:,.0f}', ha='center', fontsize=8,
             fontweight='bold')
ax2.axhline(y=0, color='black', linewidth=1.5)
ax2.set_xticks(x_pos)
ax2.set_xticklabels([t.split('-')[0] for t in ten_viet],
                    fontsize=8.5, rotation=15)
ax2.set_title('NetJob ròng từng ngành',
              fontsize=11, fontweight='bold')
ax2.set_ylabel('Số việc làm')
ax2.grid(axis='y', alpha=0.3)

# Biểu đồ 3: Tỷ lệ AI/H đầu tư theo ngành
ax3 = axes[1, 0]
ratio_AIH = np.where(x_H_val > 0.1,
                     x_AI_val / x_H_val, 0)
colors_r = ['#E84C4C' if r > 2 else
            '#E8D84C' if r > 1 else '#4CE882'
            for r in ratio_AIH]
bars3 = ax3.bar(x_pos, ratio_AIH, color=colors_r,
                edgecolor='white', linewidth=1.2)
ax3.axhline(y=1, color='gray', linewidth=1.5,
            linestyle='--', alpha=0.7,
            label='AI = H (tỷ lệ = 1)')
for bar, val in zip(bars3, ratio_AIH):
    ax3.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.03,
             f'{val:.2f}', ha='center', fontsize=8.5,
             fontweight='bold')
ax3.set_xticks(x_pos)
ax3.set_xticklabels([t.split('-')[0] for t in ten_viet],
                    fontsize=8.5, rotation=15)
ax3.set_title('Tỷ lệ đầu tư AI/Nhân lực\ntheo ngành',
              fontsize=11, fontweight='bold')
ax3.set_ylabel('x_AI / x_H')
ax3.legend(); ax3.grid(axis='y', alpha=0.3)

# Biểu đồ 4: So sánh có/không ràng buộc 5%
ax4 = axes[1, 1]
if status2 in ['optimal', 'optimal_inaccurate']:
    ax4.bar(x_pos - w_bar/2, NetJob_val, w_bar,
            label='Không ràng buộc 5%',
            color='#4C9BE8', edgecolor='white', alpha=0.8)
    ax4.bar(x_pos + w_bar/2, netjob2, w_bar,
            label='Có ràng buộc 5%',
            color='#E87A4C', edgecolor='white', alpha=0.8)
    ax4.axhline(y=0, color='black', linewidth=1.5)
    ax4.set_title('So sánh NetJob\nCó/Không ràng buộc 5% lao động',
                  fontsize=11, fontweight='bold')
else:
    ax4.text(0.5, 0.5,
             'Câu 9.4.4:\nKhông khả thi\nvới ràng buộc 5%',
             ha='center', va='center',
             transform=ax4.transAxes,
             fontsize=14, color='#E84C4C',
             fontweight='bold')
    ax4.set_title('So sánh NetJob\nCó/Không ràng buộc 5%',
                  fontsize=11, fontweight='bold')
ax4.set_xticks(x_pos)
ax4.set_xticklabels([t.split('-')[0] for t in ten_viet],
                    fontsize=8.5, rotation=15)
ax4.set_ylabel('Số việc làm')
ax4.legend(); ax4.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('bai9_tong_hop.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ HOÀN THÀNH BÀI 9 — Tất cả 4 câu!")
print(f"  9.4.1: Tổng NetJob = {NetJob_val.sum():,.0f} việc làm")
print(f"  9.4.2: x_H₂ ngưỡng = {xH2_min:.1f} tỷ VND")
print(f"  9.4.3: {len(vulnerable_idx)} ngành dễ tổn thương phân tích")
print(f"  9.4.4: {status2}")