# -*- coding: utf-8 -*-
"""Bai03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YAYIX2UgjFp8UCWumL1g6KvnFokxwkf
"""

# ============================================================
# CELL 1 — IMPORT & MOUNT GOOGLE DRIVE
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from matplotlib.gridspec import GridSpec
import warnings
warnings.filterwarnings("ignore")

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# ✏️ Chỉnh đường dẫn đến file CSV của bạn
FILE_PATH = "/content/drive/MyDrive/vietnam_sectors_2024.csv"

# Cấu hình màu sắc dùng chung
COLORS = {
    "primary":  "#1B4F72",
    "accent":   "#E74C3C",
    "green":    "#1E8449",
    "orange":   "#D35400",
    "light_bg": "#F4F6F9",
    "grid":     "#DDE3ED",
}

# Tên tiếng Việt 10 ngành (đúng thứ tự file CSV)
SECTOR_NAMES_VI = [
    "Nông-Lâm-Thủy sản",
    "CN Chế biến-Chế tạo",
    "Xây dựng",
    "Khai khoáng",
    "Bán buôn-Bán lẻ",
    "Tài chính-Ngân hàng",
    "Logistics-Vận tải",
    "CNTT-TT",
    "Giáo dục-Đào tạo",
    "Y tế",
]

print("✅ Import & Mount Drive xong!")

# ============================================================
# CELL 2 — ĐỌC DỮ LIỆU TỪ FILE CSV
# ============================================================
df = pd.read_csv(FILE_PATH)
df["sector_name_vi"] = SECTOR_NAMES_VI

# Khai báo cột tương ứng công thức đề bài:
# a1=Tăng trưởng | a2=Năng suất | a3=Lan tỏa
# a4=Xuất khẩu  | a5=Việc làm  | a6=AI Readiness | a7=Rủi ro (xấu)
COLS_GOOD = [
    "growth_rate_2024_pct",   # a1
    "gdp_share_2024_pct",     # a2
    "spillover_coef_0_1",     # a3
    "export_billion_USD",     # a4
    "labor_million",          # a5
    "ai_readiness_0_100",     # a6
]
COL_BAD = "automation_risk_pct"   # a7 — sẽ đảo dấu khi chuẩn hóa

print("✅ Đọc dữ liệu thành công!")
print(f"   Shape: {df.shape} ({df.shape[0]} ngành × {df.shape[1]} cột)\n")
print(df[["sector_name_vi"] + COLS_GOOD + [COL_BAD]].to_string(index=False))

# ============================================================
# CELL 3 — CÂU 3.4.1
# Chuẩn hóa min-max 7 cột (đảo dấu cột Risk)
# In ra ma trận đã chuẩn hóa + vẽ heatmap
# ============================================================

def norm_good(series):
    """Chỉ tiêu tốt: càng cao càng tốt → chuẩn hóa thông thường."""
    return (series - series.min()) / (series.max() - series.min())

def norm_bad(series):
    """Chỉ tiêu xấu: càng thấp càng tốt → đảo dấu trước khi chuẩn hóa."""
    return (series.max() - series) / (series.max() - series.min())

# Chuẩn hóa
Xg = df[COLS_GOOD].apply(norm_good)   # 6 cột tốt
Xb = norm_bad(df[COL_BAD])            # 1 cột xấu đã đảo

# Ghép thành ma trận hiển thị
norm_matrix = Xg.copy()
norm_matrix["risk_inv"] = Xb
norm_matrix.index   = SECTOR_NAMES_VI
norm_matrix.columns = [
    "Tăng trưởng", "Năng suất", "Lan tỏa",
    "Xuất khẩu", "Việc làm", "AI Readiness", "Rủi ro (inv)"
]

print("=" * 65)
print("CÂU 3.4.1 — MA TRẬN CHUẨN HÓA MIN-MAX")
print("=" * 65)
print("\nGiá trị ∈ [0, 1]  |  Cột 'Rủi ro (inv)' đã được đảo dấu\n")
print(norm_matrix.round(4).to_string())

# ── Heatmap ────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 5), facecolor=COLORS["light_bg"])
sns.heatmap(
    norm_matrix.T,
    annot=True, fmt=".2f", cmap="YlOrRd",
    linewidths=0.5, linecolor="white", ax=ax,
    cbar_kws={"shrink": 0.7, "label": "Giá trị chuẩn hóa"},
    annot_kws={"size": 9},
)
ax.set_title("CÂU 3.4.1 — Ma trận chuẩn hóa Min-Max (giá trị ∈ [0,1])",
             fontsize=13, fontweight="bold", pad=12, color=COLORS["primary"])
ax.tick_params(axis="x", labelsize=9, rotation=30)
ax.tick_params(axis="y", labelsize=10)
plt.tight_layout()
plt.show()

# ============================================================
# CELL 4 — CÂU 3.4.2
# Tính Priority với trọng số mặc định
# Xếp hạng 10 ngành theo Priority giảm dần + biểu đồ cột
# ============================================================

# Trọng số mặc định theo đề bài
# a1    a2    a3    a4    a5    a6    a7
W_DEFAULT = np.array([0.15, 0.15, 0.20, 0.15, 0.10, 0.20, 0.15])

def calc_priority(Xg_arr, Xb_arr, weights):
    """
    Priority_i = a1*x1 + a2*x2 + a3*x3 + a4*x4 + a5*x5 + a6*x6 + a7*risk_inv
    (risk đã đảo dấu trong Xb_arr nên tất cả đều cộng)
    """
    w_good = weights[:6]
    w_bad  = weights[6]
    return (Xg_arr * w_good).sum(axis=1) + w_bad * Xb_arr

# Tính & gán vào df
priority_default      = calc_priority(Xg.values, Xb.values, W_DEFAULT)
df["Priority_default"] = priority_default

# Bảng xếp hạng
result_default = (
    df[["sector_name_vi", "Priority_default"]]
    .sort_values("Priority_default", ascending=False)
    .reset_index(drop=True)
)
result_default.index += 1
result_default.columns = ["Ngành", "Chỉ số Priority"]

print("=" * 65)
print("CÂU 3.4.2 — XẾP HẠNG 10 NGÀNH (Trọng số mặc định)")
print("=" * 65)
print(f"\nTrọng số: a1=0.15 | a2=0.15 | a3=0.20 | a4=0.15 | a5=0.10 | a6=0.20 | a7=0.15\n")
print(result_default.round(4).to_string())
print(f"\n► Top-1: {result_default.iloc[0]['Ngành']}")
print(f"► Top-2: {result_default.iloc[1]['Ngành']}")
print(f"► Top-3: {result_default.iloc[2]['Ngành']}")

# ── Biểu đồ cột nằm ngang ──────────────────────────────────
sorted_idx  = np.argsort(-priority_default)
sorted_p    = priority_default[sorted_idx]
sorted_name = [SECTOR_NAMES_VI[i] for i in sorted_idx]
bar_colors  = [COLORS["accent"] if i < 3 else COLORS["primary"] for i in range(10)]

fig, ax = plt.subplots(figsize=(10, 6), facecolor=COLORS["light_bg"])
bars = ax.barh(range(10), sorted_p[::-1],
               color=bar_colors[::-1], edgecolor="white", height=0.65)
ax.set_yticks(range(10))
ax.set_yticklabels(sorted_name[::-1], fontsize=9.5)
ax.set_xlabel("Chỉ số Priority", fontsize=10)
ax.set_title("CÂU 3.4.2 — Xếp hạng 10 ngành theo Priority\n(Đỏ = Top-3)",
             fontsize=12, fontweight="bold", color=COLORS["primary"])
ax.axvline(sorted_p[2], color=COLORS["accent"],
           linestyle="--", linewidth=1.3, alpha=0.8)
ax.text(sorted_p[2] + 0.005, -0.8, "Ngưỡng Top-3",
        color=COLORS["accent"], fontsize=8.5)
for bar, val in zip(bars[::-1], sorted_p):
    ax.text(val + 0.005, bar.get_y() + bar.get_height()/2,
            f"{val:.3f}", va="center", fontsize=8.5, color=COLORS["primary"])
ax.set_facecolor(COLORS["light_bg"])
plt.tight_layout()
plt.show()

# ============================================================
# CELL 5 — CÂU 3.4.3
# Thay đổi a6 từ 0.05 → 0.40 (bước 0.05), chuẩn hóa lại tổng = 1
# Xem top-3 có thay đổi không + vẽ heatmap và bump chart
# ============================================================

a6_range         = np.round(np.arange(0.05, 0.41, 0.05), 2)
sensitivity_matrix = []   # lưu priority score theo từng mức a6
top3_records       = []   # lưu top-3 theo từng mức a6

for a6_val in a6_range:
    # Giữ a7 (risk) = 0.15 cố định
    # Phần còn lại cho a1..a5 = 1 - a6 - 0.15, co giãn tỷ lệ
    remaining = 1.0 - a6_val - 0.15
    base_5    = np.array([0.15, 0.15, 0.20, 0.15, 0.10])
    scale     = remaining / base_5.sum()
    w_new     = np.append(base_5 * scale, [a6_val, 0.15])

    p = calc_priority(Xg.values, Xb.values, w_new)
    sensitivity_matrix.append(p)

    ranked = np.argsort(-p)[:3]
    top3_records.append({
        "a6":    a6_val,
        "Top-1": SECTOR_NAMES_VI[ranked[0]],
        "Top-2": SECTOR_NAMES_VI[ranked[1]],
        "Top-3": SECTOR_NAMES_VI[ranked[2]],
    })

sens_df = pd.DataFrame(sensitivity_matrix,
                       index=[f"a6={v:.2f}" for v in a6_range],
                       columns=SECTOR_NAMES_VI)
top3_df = pd.DataFrame(top3_records)

print("=" * 65)
print("CÂU 3.4.3 — PHÂN TÍCH ĐỘ NHẠY TRỌNG SỐ AI READINESS (a₆)")
print("=" * 65)
print("\nTop-3 ngành theo từng mức a₆:\n")
print(top3_df.to_string(index=False))

# Kiểm tra top-3 có thay đổi không
top3_set = set()
for rec in top3_records:
    top3_set.update([rec["Top-1"], rec["Top-2"], rec["Top-3"]])
print(f"\n► Các ngành từng xuất hiện trong top-3: {', '.join(top3_set)}")

# ── Heatmap Priority Score ─────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(18, 5), facecolor=COLORS["light_bg"])

sns.heatmap(
    sens_df,
    annot=True, fmt=".3f", cmap="coolwarm",
    linewidths=0.4, linecolor="white", ax=axes[0],
    cbar_kws={"shrink": 0.8, "label": "Priority Score"},
    annot_kws={"size": 8},
)
axes[0].set_title("Heatmap — Priority Score theo mức a₆",
                  fontsize=12, fontweight="bold", color=COLORS["primary"])
axes[0].set_xlabel("Ngành", fontsize=9)
axes[0].set_ylabel("Mức a₆", fontsize=9)
axes[0].tick_params(axis="x", labelsize=8, rotation=35)

# ── Bump chart — biến động xếp hạng ───────────────────────
all_ranks = {name: [] for name in SECTOR_NAMES_VI}
for row in sensitivity_matrix:
    for rank, idx in enumerate(np.argsort(-np.array(row)), 1):
        all_ranks[SECTOR_NAMES_VI[idx]].append(rank)

palette   = [COLORS["accent"], COLORS["primary"], COLORS["green"],
             COLORS["orange"], "#8E44AD", "#2E86C1"]
color_map = {name: palette[i % len(palette)]
             for i, name in enumerate(top3_set)}

for name in top3_set:
    axes[1].plot(a6_range, all_ranks[name], marker="o", linewidth=2.2,
                 label=name[:18], color=color_map[name], markersize=6)

axes[1].invert_yaxis()
axes[1].set_yticks(range(1, 11))
axes[1].yaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x, _: f"#{int(x)}"))
axes[1].set_xlabel("Trọng số a₆ (AI Readiness)", fontsize=9)
axes[1].set_ylabel("Xếp hạng (thấp = tốt hơn)", fontsize=9)
axes[1].set_title("Bump Chart — Biến động xếp hạng khi thay đổi a₆",
                  fontsize=12, fontweight="bold", color=COLORS["primary"])
axes[1].legend(fontsize=8.5, loc="lower right", framealpha=0.85)
axes[1].set_facecolor(COLORS["light_bg"])
axes[1].grid(axis="y", color=COLORS["grid"], linewidth=0.7)

plt.suptitle("CÂU 3.4.3 — Phân tích độ nhạy trọng số AI Readiness (a₆)",
             fontsize=13, fontweight="bold", color=COLORS["primary"], y=1.02)
plt.tight_layout()
plt.show()

# ============================================================
# CELL 6 — CÂU 3.4.4
# So sánh "Định hướng Tăng trưởng" vs "Định hướng Bao trùm"
# In top-3 mỗi định hướng + vẽ biểu đồ grouped bar
# ============================================================

# Định hướng Tăng trưởng: ưu tiên a1(growth), a2(productivity), a4(export)
#        a1    a2    a3    a4    a5    a6    a7
W_GROWTH    = np.array([0.30, 0.25, 0.05, 0.25, 0.05, 0.05, 0.05])

# Định hướng Bao trùm: ưu tiên a5(employment), a3(spillover), a7(risk↓)
#        a1    a2    a3    a4    a5    a6    a7
W_INCLUSIVE = np.array([0.05, 0.05, 0.25, 0.05, 0.30, 0.05, 0.25])

p_growth    = calc_priority(Xg.values, Xb.values, W_GROWTH)
p_inclusive = calc_priority(Xg.values, Xb.values, W_INCLUSIVE)

print("=" * 65)
print("CÂU 3.4.4 — SO SÁNH HAI ĐỊNH HƯỚNG CHÍNH SÁCH")
print("=" * 65)

print("\n📈 Định hướng TĂNG TRƯỞNG")
print("   Trọng số: a1=0.30 | a2=0.25 | a3=0.05 | a4=0.25 | a5=0.05 | a6=0.05 | a7=0.05")
for i, idx in enumerate(np.argsort(-p_growth)[:3], 1):
    print(f"   Top-{i}: {SECTOR_NAMES_VI[idx]:<25}  Score = {p_growth[idx]:.4f}")

print("\n🤝 Định hướng BAO TRÙM")
print("   Trọng số: a1=0.05 | a2=0.05 | a3=0.25 | a4=0.05 | a5=0.30 | a6=0.05 | a7=0.25")
for i, idx in enumerate(np.argsort(-p_inclusive)[:3], 1):
    print(f"   Top-{i}: {SECTOR_NAMES_VI[idx]:<25}  Score = {p_inclusive[idx]:.4f}")

# ── Grouped bar chart ──────────────────────────────────────
sort_order = np.argsort(-p_growth)   # sắp theo điểm Tăng trưởng
x     = np.arange(10)
w_bar = 0.35

fig, ax = plt.subplots(figsize=(14, 6), facecolor=COLORS["light_bg"])
ax.bar(x - w_bar/2, p_growth[sort_order],
       width=w_bar, label="📈 Tăng trưởng",
       color=COLORS["primary"], edgecolor="white")
ax.bar(x + w_bar/2, p_inclusive[sort_order],
       width=w_bar, label="🤝 Bao trùm",
       color=COLORS["orange"], edgecolor="white", alpha=0.85)

ax.set_xticks(x)
ax.set_xticklabels(
    [SECTOR_NAMES_VI[i][:15] for i in sort_order],
    rotation=38, ha="right", fontsize=8.5
)
ax.set_ylabel("Chỉ số Priority", fontsize=10)
ax.set_title("CÂU 3.4.4 — So sánh hai định hướng chính sách\n"
             "G = Top-3 Tăng trưởng  |  B = Top-3 Bao trùm",
             fontsize=12, fontweight="bold", color=COLORS["primary"])
ax.legend(fontsize=10, framealpha=0.9)
ax.set_facecolor(COLORS["light_bg"])
ax.grid(axis="y", color=COLORS["grid"], linewidth=0.7, alpha=0.7)

# Đánh dấu G / B lên đỉnh cột
top3_g = set(np.argsort(-p_growth)[:3])
top3_i = set(np.argsort(-p_inclusive)[:3])
for pos, orig_idx in enumerate(sort_order):
    if orig_idx in top3_g:
        ax.annotate("G",
                    xy=(pos - w_bar/2, p_growth[orig_idx]),
                    xytext=(0, 5), textcoords="offset points",
                    ha="center", fontsize=9,
                    color=COLORS["primary"], fontweight="bold")
    if orig_idx in top3_i:
        ax.annotate("B",
                    xy=(pos + w_bar/2, p_inclusive[orig_idx]),
                    xytext=(0, 5), textcoords="offset points",
                    ha="center", fontsize=9,
                    color=COLORS["orange"], fontweight="bold")

plt.tight_layout()
plt.show()