# -*- coding: utf-8 -*-
"""Bai05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqVUOF5o6MjQmxrn1WlsHk2DyAHNONbo
"""

!pip install pulp -q

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pulp

print("✅ Thư viện sẵn sàng!")

# ═══════════════════════════════════════════════════════════════
# DỮ LIỆU 15 DỰ ÁN — đầy đủ theo bảng 5.2
# ═══════════════════════════════════════════════════════════════
du_an = {
    'P1' : {'ten': 'TTDL Quốc gia Hòa Lạc',    'linh_vuc': 'Ha_tang',      'C': 12000, 'C1': 8500,  'C2': 3500,  'B': 21500},
    'P2' : {'ten': 'TTDL Quốc gia phía Nam',    'linh_vuc': 'Ha_tang',      'C': 11500, 'C1': 7500,  'C2': 4000,  'B': 20800},
    'P3' : {'ten': 'Hệ thống 5G toàn quốc',     'linh_vuc': 'Ha_tang',      'C': 18000, 'C1': 12000, 'C2': 6000,  'B': 32500},
    'P4' : {'ten': 'VNeID 2.0',                 'linh_vuc': 'Chinh_phu_so', 'C': 4500,  'C1': 3500,  'C2': 1000,  'B': 9200 },
    'P5' : {'ten': 'Cổng DVCQG v3',             'linh_vuc': 'Chinh_phu_so', 'C': 3200,  'C1': 2500,  'C2': 700,   'B': 6800 },
    'P6' : {'ten': 'Y tế số quốc gia',          'linh_vuc': 'Khac',         'C': 5800,  'C1': 4000,  'C2': 1800,  'B': 11400},
    'P7' : {'ten': 'Giáo dục số K-12',          'linh_vuc': 'Khac',         'C': 6500,  'C1': 4500,  'C2': 2000,  'B': 12200},
    'P8' : {'ten': 'TT AI QG + Supercomputing', 'linh_vuc': 'AI_ban_dan',   'C': 15000, 'C1': 9000,  'C2': 6000,  'B': 28500},
    'P9' : {'ten': 'Sandbox tài chính số',      'linh_vuc': 'Khac',         'C': 2500,  'C1': 1800,  'C2': 700,   'B': 5800 },
    'P10': {'ten': 'Logistics thông minh',      'linh_vuc': 'Khac',         'C': 7200,  'C1': 5000,  'C2': 2200,  'B': 13800},
    'P11': {'ten': 'Nông nghiệp số ĐBSCL',     'linh_vuc': 'Khac',         'C': 4800,  'C1': 3500,  'C2': 1300,  'B': 8500 },
    'P12': {'ten': 'Đào tạo 50k kỹ sư AI',     'linh_vuc': 'Khac',         'C': 8500,  'C1': 5500,  'C2': 3000,  'B': 16200},
    'P13': {'ten': 'KCN bán dẫn BN-BG',        'linh_vuc': 'AI_ban_dan',   'C': 20000, 'C1': 13000, 'C2': 7000,  'B': 35000},
    'P14': {'ten': 'An ninh mạng (SOC)',        'linh_vuc': 'Khac',         'C': 3800,  'C1': 2800,  'C2': 1000,  'B': 7500 },
    'P15': {'ten': 'Open Data Quốc gia',        'linh_vuc': 'Khac',         'C': 1500,  'C1': 1200,  'C2': 300,   'B': 3800 },
}

P  = list(du_an.keys())                        # ['P1',...,'P15']
C  = {p: du_an[p]['C']  for p in P}            # chi phí tổng
C1 = {p: du_an[p]['C1'] for p in P}            # chi phí năm 1-2
C2 = {p: du_an[p]['C2'] for p in P}            # chi phí năm 3-5 (chỉ hiển thị)
B  = {p: du_an[p]['B']  for p in P}            # lợi ích NPV

# Xác suất hoàn thành đúng tiến độ (dùng cho câu 5.4.4)
xac_suat = {p: (0.85 if du_an[p]['linh_vuc'] == 'Ha_tang'
           else 0.75 if du_an[p]['linh_vuc'] == 'Chinh_phu_so'
           else 0.65 if du_an[p]['linh_vuc'] == 'AI_ban_dan'
           else 0.80)
           for p in P}

# In bảng dữ liệu đầy đủ
df_da = pd.DataFrame({
    'Tên dự án'  : [du_an[p]['ten']      for p in P],
    'Lĩnh vực'   : [du_an[p]['linh_vuc'] for p in P],
    'C tổng'     : [C[p]  for p in P],
    'C năm 1-2'  : [C1[p] for p in P],
    'C năm 3-5'  : [C2[p] for p in P],
    'NPV'        : [B[p]  for p in P],
    'B/C'        : [round(B[p]/C[p], 2) for p in P],
    'p (rủi ro)' : [xac_suat[p] for p in P],
}, index=P)

print("=== DANH MỤC 15 DỰ ÁN ===")
print(df_da.to_string())

# ═══════════════════════════════════════════════════════════════
# CÂU 5.4.1 — Giải bằng PuLP CBC
# Đúng theo mô hình 5.3: chỉ có C1, C2, C3, C4, C5, C6, C7
# ═══════════════════════════════════════════════════════════════

def giai_MIP(ngan_sach=80000, ngan_sach_12=40000,
             bat_buoc_P1_P2=False,
             dung_ky_vong=False,
             verbose=True):
    """
    Tham số:
        ngan_sach      : ngân sách tổng 5 năm (C1 trong đề)
        ngan_sach_12   : ngân sách năm 1-2    (C2 trong đề)
        bat_buoc_P1_P2 : True → bắt buộc chọn cả P1 và P2
        dung_ky_vong   : True → dùng E[Z]=Σpᵢ·Bᵢ·yᵢ thay vì Σ Bᵢ·yᵢ
    """
    m = pulp.LpProblem("VN_MIP_DuAn", pulp.LpMaximize)

    # Biến nhị phân yᵢ ∈ {0,1}
    y = pulp.LpVariable.dicts("y", P, cat='Binary')

    # ── Hàm mục tiêu ─────────────────────────────────────────
    if dung_ky_vong:
        # Câu 5.4.4: E[Z] = Σ pᵢ · Bᵢ · yᵢ
        m += pulp.lpSum(xac_suat[p] * B[p] * y[p] for p in P), "E_Z"
    else:
        # Câu 5.4.1/5.4.2/5.4.3: max Σ Bᵢ · yᵢ
        m += pulp.lpSum(B[p] * y[p] for p in P), "Tong_NPV"

    # ── Ràng buộc theo đúng mô hình 5.3 ─────────────────────

    # (C1) Ngân sách tổng 5 năm
    m += pulp.lpSum(C[p] * y[p] for p in P) <= ngan_sach, \
         "C1_ngan_sach_tong"

    # (C2) Ngân sách năm 1-2
    m += pulp.lpSum(C1[p] * y[p] for p in P) <= ngan_sach_12, \
         "C2_ngan_sach_nam12"

    # (C3) Loại trừ: chỉ chọn 1 trong P1/P2
    if bat_buoc_P1_P2:
        # Câu 5.4.3: bỏ C3, bắt buộc cả P1 và P2
        m += y['P1'] == 1, "BatBuoc_P1"
        m += y['P2'] == 1, "BatBuoc_P2"
    else:
        m += y['P1'] + y['P2'] <= 1, "C3_loai_tru_TTDL"

    # (C4) Tiên quyết: y₈ ≤ y₁₂
    m += y['P8'] <= y['P12'], "C4_P8_can_P12"

    # (C5) Tiên quyết: y₁₃ ≤ y₁₂
    m += y['P13'] <= y['P12'], "C5_P13_can_P12"

    # (C6) Cân đối lĩnh vực
    m += y['P4'] + y['P5'] >= 1, "C6a_chinh_phu_so"   # ít nhất 1 CP số
    m += y['P14'] == 1,          "C6b_an_ninh_bat_buoc" # P14 bắt buộc

    # (C7) Số lượng dự án: 7 ≤ Σyᵢ ≤ 11
    m += pulp.lpSum(y[p] for p in P) >= 7,  "C7a_toi_thieu_7"
    m += pulp.lpSum(y[p] for p in P) <= 11, "C7b_toi_da_11"

    # Giải
    m.solve(pulp.PULP_CBC_CMD(msg=False))
    status = pulp.LpStatus[m.status]

    if status != 'Optimal':
        if verbose:
            print(f"  ❌ Trạng thái: {status} — Không có nghiệm tối ưu!")
        return None

    chon    = [p for p in P if y[p].value() > 0.5]
    Z       = pulp.value(m.objective)
    tong_C  = sum(C[p]  for p in chon)
    tong_C1 = sum(C1[p] for p in chon)

    if verbose:
        print(f"  ✅ Trạng thái       : {status}")
        print(f"  Số dự án chọn      : {len(chon)}")
        print(f"  Dự án được chọn    : {', '.join(chon)}")
        print(f"  Tổng chi phí       : {tong_C:>10,} tỷ  (≤ {ngan_sach:,})")
        print(f"  Chi phí năm 1-2    : {tong_C1:>10,} tỷ  (≤ {ngan_sach_12:,})")
        print(f"  Z* / E[Z*]         : {Z:>10,.0f} tỷ VND")
        print(f"  NPV biên (Z*/C)    : {Z/tong_C:.4f}")

    return {
        'status' : status,
        'chon'   : chon,
        'Z'      : Z,
        'C_used' : tong_C,
        'C1_used': tong_C1,
    }

# ── Chạy câu 5.4.1 ───────────────────────────────────────────
print("=" * 60)
print("CÂU 5.4.1 — KẾT QUẢ TỐI ƯU CƠ SỞ")
print("Ngân sách tổng: 80.000 tỷ | Năm 1-2: 40.000 tỷ")
print("=" * 60)

r1 = giai_MIP(ngan_sach=80000, ngan_sach_12=40000)

# Bảng chi tiết
print("\n=== BẢNG CHI TIẾT DỰ ÁN ĐƯỢC CHỌN ===")
print(f"  {'Mã':>4} | {'Tên dự án':35s} | {'Lĩnh vực':12s} | "
      f"{'C (tỷ)':>8} | {'NPV (tỷ)':>9} | {'B/C':>5}")
print("  " + "─" * 80)
for p in r1['chon']:
    print(f"  {p:>4} | {du_an[p]['ten']:35s} | "
          f"{du_an[p]['linh_vuc']:12s} | "
          f"{C[p]:>8,} | {B[p]:>9,} | {B[p]/C[p]:>5.2f}")
print("  " + "─" * 80)
print(f"  {'TỔNG':>4} | {'':35s} | {'':12s} | "
      f"{r1['C_used']:>8,} | {r1['Z']:>9,.0f} | "
      f"{r1['Z']/r1['C_used']:>5.2f}")

# Kiểm tra tất cả ràng buộc
print("\n=== KIỂM TRA RÀNG BUỘC ===")
chon = r1['chon']
checks = [
    ("C1 NS tổng",    r1['C_used'] <= 80000,
     f"{r1['C_used']:,} ≤ 80,000"),
    ("C2 NS năm 1-2", r1['C1_used'] <= 40000,
     f"{r1['C1_used']:,} ≤ 40,000"),
    ("C3 P1/P2",      not('P1' in chon and 'P2' in chon),
     f"P1={'✓' if 'P1' in chon else '✗'}, P2={'✓' if 'P2' in chon else '✗'}"),
    ("C4 P8≤P12",     not('P8' in chon and 'P12' not in chon),
     f"P8={'✓' if 'P8' in chon else '✗'}, P12={'✓' if 'P12' in chon else '✗'}"),
    ("C5 P13≤P12",    not('P13' in chon and 'P12' not in chon),
     f"P13={'✓' if 'P13' in chon else '✗'}, P12={'✓' if 'P12' in chon else '✗'}"),
    ("C6a CP số",     'P4' in chon or 'P5' in chon,
     f"P4={'✓' if 'P4' in chon else '✗'}, P5={'✓' if 'P5' in chon else '✗'}"),
    ("C6b AN mạng",   'P14' in chon,
     f"P14={'✓' if 'P14' in chon else '✗'}"),
    ("C7 số DA",      7 <= len(chon) <= 11,
     f"7 ≤ {len(chon)} ≤ 11"),
]
for ten, ok, mo_ta in checks:
    print(f"  {'✅' if ok else '❌'} {ten:15s}: {mo_ta}")

# ═══════════════════════════════════════════════════════════════
# CÂU 5.4.2 — Nới ngân sách lên 100.000 tỷ
# ═══════════════════════════════════════════════════════════════
print("=" * 60)
print("CÂU 5.4.2 — NÂNG NGÂN SÁCH LÊN 100.000 TỶ")
print("=" * 60)

r2 = giai_MIP(ngan_sach=100000, ngan_sach_12=50000)

# So sánh
print("\n=== SO SÁNH HAI KỊCH BẢN ===")
print(f"  {'Tiêu chí':25s} | {'80.000 tỷ':>12} | {'100.000 tỷ':>12}")
print("  " + "─" * 53)
print(f"  {'Số dự án':25s} | {len(r1['chon']):>12} | {len(r2['chon']):>12}")
print(f"  {'Tổng NPV Z* (tỷ)':25s} | {r1['Z']:>12,.0f} | {r2['Z']:>12,.0f}")
print(f"  {'Tổng chi phí (tỷ)':25s} | {r1['C_used']:>12,} | {r2['C_used']:>12,}")
print(f"  {'NPV biên (Z*/C)':25s} | {r1['Z']/r1['C_used']:>12.4f} | "
      f"{r2['Z']/r2['C_used']:>12.4f}")

them_vao = set(r2['chon']) - set(r1['chon'])
bo_ra    = set(r1['chon']) - set(r2['chon'])
print(f"\n  Dự án THÊM khi nới ngân sách: "
      f"{', '.join(sorted(them_vao)) if them_vao else 'Không có'}")
for p in sorted(them_vao):
    print(f"    + {p}: {du_an[p]['ten']} "
          f"| C={C[p]:,} | NPV={B[p]:,}")
print(f"\n  Dự án BỎ khi nới ngân sách  : "
      f"{', '.join(sorted(bo_ra)) if bo_ra else 'Không có'}")

# ═══════════════════════════════════════════════════════════════
# CÂU 5.4.3 — Quốc hội yêu cầu cả P1 và P2
# ═══════════════════════════════════════════════════════════════
print("=" * 60)
print("CÂU 5.4.3 — BẮT BUỘC CẢ P1 VÀ P2 (redundancy)")
print("=" * 60)

# Kiểm tra lý thuyết trước
tong_bat_buoc = C1['P1'] + C1['P2']
print(f"\n  Chỉ riêng P1+P2 đã tốn năm 1-2: "
      f"{tong_bat_buoc:,} tỷ / 40,000 tỷ "
      f"({'OK' if tong_bat_buoc <= 40000 else 'VƯỢT'})")

r3 = giai_MIP(
    ngan_sach=80000,
    ngan_sach_12=40000,
    bat_buoc_P1_P2=True
)

if r3:
    delta_Z = r3['Z'] - r1['Z']
    print(f"\n=== SO SÁNH VỚI CƠ SỞ ===")
    print(f"  Z* cơ sở  (P1 hoặc P2) = {r1['Z']:>12,.0f} tỷ VND")
    print(f"  Z* mới    (P1 và P2)   = {r3['Z']:>12,.0f} tỷ VND")
    print(f"  Thay đổi ΔZ*           = {delta_Z:>12,.0f} tỷ VND")
    print(f"  Tỷ lệ thay đổi         = {delta_Z/r1['Z']*100:.2f}%")
    print(f"\n  📌 Kết luận: Bài toán VẪN KHẢ THI ✅")
    print(f"  Việc bắt buộc cả 2 TTDL làm Z* "
          f"{'giảm' if delta_Z < 0 else 'tăng'} "
          f"{abs(delta_Z):,.0f} tỷ ({abs(delta_Z/r1['Z']*100):.2f}%)")
    print(f"  Vì phải bỏ bớt dự án NPV cao hơn để đủ ngân sách")
else:
    print(f"\n  ❌ Kết luận: Bài toán KHÔNG KHẢ THI!")

# ═══════════════════════════════════════════════════════════════
# CÂU 5.4.4 — E[Z] = Σ pᵢ · Bᵢ · yᵢ
# ═══════════════════════════════════════════════════════════════
print("=" * 60)
print("CÂU 5.4.4 — TỐI ĐA HÓA NPV KỲ VỌNG (có trọng số rủi ro)")
print("=" * 60)

# Bảng xác suất
print("\n  Xác suất theo loại dự án:")
print("  Hạ tầng = 0.85 | Chính phủ số = 0.75 | "
      "AI/Bán dẫn = 0.65 | Còn lại = 0.80")

print("\n  NPV gốc vs NPV kỳ vọng từng dự án:")
print(f"  {'Mã':>4} | {'Tên':35s} | {'p':>5} | "
      f"{'B gốc':>8} | {'p×B':>9}")
print("  " + "─" * 68)
for p in P:
    pB = xac_suat[p] * B[p]
    print(f"  {p:>4} | {du_an[p]['ten']:35s} | "
          f"{xac_suat[p]:>5.2f} | {B[p]:>8,} | {pB:>9,.0f}")

# Giải với NPV kỳ vọng
r4 = giai_MIP(
    ngan_sach=80000,
    ngan_sach_12=40000,
    dung_ky_vong=True
)

# So sánh danh sách dự án
print(f"\n=== SO SÁNH KẾT QUẢ ===")
print(f"  {'':25s} | {'NPV gốc':>14} | {'NPV kỳ vọng':>14}")
print("  " + "─" * 58)
print(f"  {'Dự án chọn':25s} | "
      f"{str(sorted(r1['chon'])):>14} |")
print(f"  {'':25s} | "
      f"{'':>14} | {str(sorted(r4['chon'])):>14}")
print(f"  {'Số dự án':25s} | {len(r1['chon']):>14} | {len(r4['chon']):>14}")
print(f"  {'Z*':25s} | {r1['Z']:>14,.0f} | {r4['Z']:>14,.0f}")

khac = set(r4['chon']) ^ set(r1['chon'])
print(f"\n  Dự án khác nhau giữa 2 kịch bản: "
      f"{', '.join(sorted(khac)) if khac else 'Giống hệt nhau ✅'}")

# ═══════════════════════════════════════════════════════════════
# BIỂU ĐỒ TỔNG HỢP
# ═══════════════════════════════════════════════════════════════
fig, axes = plt.subplots(2, 2, figsize=(16, 11))
fig.suptitle('Bài 5 — MIP Lựa chọn dự án Chuyển đổi số Quốc gia',
             fontsize=14, fontweight='bold')

mau = {'Ha_tang':'#4C9BE8', 'Chinh_phu_so':'#E87A4C',
       'AI_ban_dan':'#C44CE8', 'Khac':'#4CE882'}

# ── Biểu đồ 1: NPV vs Chi phí ────────────────────────────────
ax1 = axes[0, 0]
chon_set = set(r1['chon'])
for p in P:
    c_mau = mau[du_an[p]['linh_vuc']]
    size  = 220 if p in chon_set else 70
    alpha = 1.0 if p in chon_set else 0.35
    mk    = 'o' if p in chon_set else '^'
    ax1.scatter(C[p], B[p], c=c_mau, s=size, marker=mk,
                alpha=alpha, edgecolors='white', linewidth=1.5, zorder=3)
    if p in chon_set:
        ax1.annotate(p, (C[p], B[p]),
                     xytext=(5, 5), textcoords='offset points',
                     fontsize=8.5, fontweight='bold', color='navy')

# Legend lĩnh vực
for lv, c_mau in mau.items():
    ax1.scatter([], [], c=c_mau, s=80, label=lv.replace('_',' '))
ax1.scatter([], [], c='gray', s=220, marker='o', label='Được chọn')
ax1.scatter([], [], c='gray', s=70,  marker='^', alpha=0.4,
            label='Không chọn')
ax1.set_xlabel('Chi phí tổng (tỷ VND)'); ax1.set_ylabel('NPV (tỷ VND)')
ax1.set_title('NPV vs Chi phí\n(Kịch bản cơ sở 80.000 tỷ)',
              fontsize=11, fontweight='bold')
ax1.legend(fontsize=8, loc='upper left'); ax1.grid(alpha=0.3)

# ── Biểu đồ 2: So sánh Z* 3 kịch bản ───────────────────────
ax2 = axes[0, 1]
kb_names = ['Cơ sở\n80.000 tỷ',
            'Nới NS\n100.000 tỷ',
            'Bắt buộc\nP1+P2']
Z_vals = [r1['Z'], r2['Z'],
          r3['Z'] if r3 else 0]
n_da   = [len(r1['chon']), len(r2['chon']),
          len(r3['chon']) if r3 else 0]
mau_kb = ['#4C9BE8', '#4CE882', '#E87A4C']

bars = ax2.bar(kb_names, Z_vals, color=mau_kb,
               edgecolor='white', linewidth=1.5, width=0.5)
for bar, z, n in zip(bars, Z_vals, n_da):
    if z > 0:
        ax2.text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + 300,
                 f'{z:,.0f} tỷ\n({n} DA)',
                 ha='center', fontsize=9.5, fontweight='bold')
ax2.set_title('So sánh Z* theo kịch bản', fontsize=11, fontweight='bold')
ax2.set_ylabel('Z* NPV (tỷ VND)'); ax2.grid(axis='y', alpha=0.3)
ax2.yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'{x:,.0f}'))

# ── Biểu đồ 3: NPV gốc vs NPV kỳ vọng ──────────────────────
ax3 = axes[1, 0]
x_pos = range(len(P))
B_list  = [B[p] for p in P]
pB_list = [xac_suat[p]*B[p] for p in P]
mau_chon = ['#E84C4C' if p in set(r1['chon']) else '#AAAAAA' for p in P]

ax3.bar([x-0.2 for x in x_pos], B_list,  0.35,
        label='NPV gốc',     color='#4C9BE8', alpha=0.8)
ax3.bar([x+0.2 for x in x_pos], pB_list, 0.35,
        label='NPV kỳ vọng', color='#E87A4C', alpha=0.8)
ax3.set_xticks(list(x_pos))
ax3.set_xticklabels(P, fontsize=9)
ax3.set_title('NPV gốc vs NPV kỳ vọng (có rủi ro)',
              fontsize=11, fontweight='bold')
ax3.set_ylabel('NPV (tỷ VND)'); ax3.legend(); ax3.grid(axis='y', alpha=0.3)

# ── Biểu đồ 4: Ma trận chọn 4 kịch bản ─────────────────────
ax4 = axes[1, 1]
kich_ban = {
    'Cơ sở\n(80K)'    : r1,
    'Nới NS\n(100K)'  : r2,
    'P1+P2\nbắt buộc' : r3,
    'NPV\nkỳ vọng'    : r4,
}
matrix = np.array([
    [1 if (r and p in r['chon']) else 0
     for r in kich_ban.values()]
    for p in P
], dtype=float)

im = ax4.imshow(matrix.T, cmap='RdYlGn', aspect='auto', vmin=0, vmax=1)
ax4.set_xticks(range(len(P)));     ax4.set_xticklabels(P, fontsize=8.5)
ax4.set_yticks(range(len(kich_ban))); ax4.set_yticklabels(list(kich_ban.keys()), fontsize=9)
for i in range(len(P)):
    for j, r in enumerate(kich_ban.values()):
        val = r and p in r['chon']
        p   = P[i]
        val = bool(r and p in r['chon'])
        ax4.text(i, j, '✓' if val else '✗',
                 ha='center', va='center', fontsize=10,
                 color='darkgreen' if val else '#CC4444',
                 fontweight='bold')
ax4.set_title('Ma trận chọn dự án\ntheo 4 kịch bản',
              fontsize=11, fontweight='bold')
ax4.set_xlabel('Dự án')

plt.tight_layout()
plt.savefig('bai5_MIP_tong_hop.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ HOÀN THÀNH BÀI 5 — Tất cả 4 câu!")
print(f"  5.4.1: Z* = {r1['Z']:,.0f} tỷ | {len(r1['chon'])} dự án")
print(f"  5.4.2: Z* = {r2['Z']:,.0f} tỷ | {len(r2['chon'])} dự án")
print(f"  5.4.3: {'Khả thi ✅' if r3 else 'Không khả thi ❌'}"
      + (f" | Z* = {r3['Z']:,.0f} tỷ" if r3 else ""))
print(f"  5.4.4: E[Z*] = {r4['Z']:,.0f} tỷ | {len(r4['chon'])} dự án")