# -*- coding: utf-8 -*-
"""Bai04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195HOsS6IMy19mYHlhQYhX7fomPcpGfBT
"""

# CELL 1 — IMPORT & MOUNT GOOGLE DRIVE
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import pulp
import cvxpy as cp
import warnings
warnings.filterwarnings("ignore")

from google.colab import drive
drive.mount('/content/drive')

# ✏️ Chỉnh đường dẫn cho đúng
FILE_PATH = "/content/drive/MyDrive/vietnam_regions_2024.csv"

# ── Hằng số dùng chung ─────────────────────────────────────
REGIONS = ['NMM', 'RRD', 'NCC', 'CH', 'SE', 'MD']
REGION_NAMES_VI = [
    "Trung du MN Bắc",
    "Đồng bằng sông Hồng",
    "Bắc TB + DH Trung Bộ",
    "Tây Nguyên",
    "Đông Nam Bộ",
    "Đồng bằng sông CL",
]
ITEMS      = ['I', 'D', 'AI', 'H']
ITEM_NAMES = ['Hạ tầng số (I)', 'CĐS DN (D)', 'Năng lực AI', 'Nhân lực số (H)']

NR, NJ = 6, 4   # 6 vùng × 4 hạng mục = 24 biến

# Hệ số tác động biên β_{j,r} theo đề bài
BETA = {
    ('NMM','I'):1.15,('NMM','D'):0.85,('NMM','AI'):0.55,('NMM','H'):1.30,
    ('RRD','I'):0.95,('RRD','D'):1.25,('RRD','AI'):1.40,('RRD','H'):1.05,
    ('NCC','I'):1.05,('NCC','D'):0.95,('NCC','AI'):0.85,('NCC','H'):1.15,
    ('CH', 'I'):1.20,('CH', 'D'):0.75,('CH', 'AI'):0.45,('CH', 'H'):1.35,
    ('SE', 'I'):0.90,('SE', 'D'):1.30,('SE', 'AI'):1.55,('SE', 'H'):1.00,
    ('MD', 'I'):1.10,('MD', 'D'):0.85,('MD', 'AI'):0.65,('MD', 'H'):1.25,
}

# Dạng ma trận numpy (6×4) — dùng cho CVXPY
BETA_MAT = np.array([
    [BETA[(r,j)] for j in ITEMS] for r in REGIONS
])

# Chỉ số số hóa ban đầu D₀ từ file CSV (cột digital_index_0_100)
D0 = np.array([38, 78, 55, 32, 82, 48])   # NMM, RRD, NCC, CH, SE, MD

# Tham số ràng buộc công bằng C5
# ⚠️ Ghi chú quan trọng:
# Đề bài dùng lambda=0.7 nhưng gây infeasible vì:
#   Tây Nguyên (D0=32) cần đầu tư xD >= 12.700 tỷ để đạt 70% mức của
#   Đông Nam Bộ (D0=82), trong khi trần vùng chỉ 12.000 tỷ (C3).
# → Điều chỉnh lambda=0.65 (65%) để bài toán có nghiệm khả thi,
#   vẫn đảm bảo ý nghĩa công bằng vùng miền.
GAMMA  = 0.002
LAMBDA = 0.65

COLORS = {
    "primary":  "#1B4F72",
    "accent":   "#E74C3C",
    "green":    "#1E8449",
    "orange":   "#D35400",
    "light_bg": "#F4F6F9",
}

print("✅ Import & Mount Drive xong!")
print(f"   Beta matrix shape : {BETA_MAT.shape}")
print(f"   D0 các vùng       : {dict(zip(REGIONS, D0))}")
print(f"   lambda (C5)       : {LAMBDA}  ← điều chỉnh từ 0.7 để feasible")

df_raw = pd.read_csv(FILE_PATH)
df_raw["region_name_vi"] = REGION_NAMES_VI

print("✅ Đọc dữ liệu thành công!")
print(f"   Shape: {df_raw.shape}\n")
cols_show = ["region_name_vi", "digital_index_0_100",
             "ai_readiness_0_100", "trained_labor_pct", "grdp_per_capita_million_VND"]
print(df_raw[cols_show].to_string(index=False))

# ============================================================
# CELL 3 — CÂU 4.4.1: Cài đặt & giải bằng PuLP (solver CBC)
# In ra ma trận phân bổ 6×4 và Z*
# ============================================================
print("=" * 65)
print("CÂU 4.4.1 — GIẢI BẰNG PuLP (CBC solver)")
print("=" * 65)

# ── Khởi tạo bài toán ──────────────────────────────────────
mdl = pulp.LpProblem("VN_Digital_Budget", pulp.LpMaximize)

# Biến quyết định x[r][j] >= 0
x = pulp.LpVariable.dicts('x', (REGIONS, ITEMS), lowBound=0)

# ── Hàm mục tiêu: max GDP gain ─────────────────────────────
mdl += pulp.lpSum(
    BETA[(r,j)] * x[r][j]
    for r in REGIONS for j in ITEMS
), "Z_GDP_gain"

# ── C1: Ngân sách tổng ≤ 50.000 ────────────────────────────
mdl += pulp.lpSum(
    x[r][j] for r in REGIONS for j in ITEMS
) <= 50000, "C1_total"

# ── C2: Sàn ngân sách mỗi vùng ≥ 5.000 ────────────────────
for r, name in zip(REGIONS, REGION_NAMES_VI):
    mdl += pulp.lpSum(x[r][j] for j in ITEMS) >= 5000, f"C2_floor_{r}"

# ── C3: Trần ngân sách mỗi vùng ≤ 12.000 ──────────────────
for r in REGIONS:
    mdl += pulp.lpSum(x[r][j] for j in ITEMS) <= 12000, f"C3_ceil_{r}"

# ── C4: Sàn nhân lực số tổng ≥ 12.000 ─────────────────────
mdl += pulp.lpSum(x[r]['H'] for r in REGIONS) >= 12000, "C4_human"

# ── C5: Công bằng số hóa vùng miền (biến phụ M = Dmax) ────
# Mỗi vùng phải đạt ít nhất LAMBDA*Dmax sau đầu tư
M_var = pulp.LpVariable('M_Dmax', lowBound=0)
D0_dict = dict(zip(REGIONS, D0))
for r in REGIONS:
    # C5a: D0[r] + γ*xD[r] ≤ M  (M là giá trị lớn nhất)
    mdl += D0_dict[r] + GAMMA * x[r]['D'] <= M_var, f"C5a_{r}"
    # C5b: D0[r] + γ*xD[r] ≥ λ*M  (mỗi vùng đạt ít nhất λ*M)
    mdl += D0_dict[r] + GAMMA * x[r]['D'] >= LAMBDA * M_var, f"C5b_{r}"

# ── Giải ───────────────────────────────────────────────────
mdl.solve(pulp.PULP_CBC_CMD(msg=False))

# ── Kết quả ────────────────────────────────────────────────
Z_pulp   = pulp.value(mdl.objective)
status   = pulp.LpStatus[mdl.status]

print(f"\nTrạng thái  : {status}")
print(f"Z* GDP gain : {Z_pulp:>12,.2f}  tỷ VND")

# Ma trận phân bổ 6×4
alloc_pulp = np.array([
    [pulp.value(x[r][j]) for j in ITEMS]
    for r in REGIONS
])
df_pulp = pd.DataFrame(alloc_pulp, index=REGION_NAMES_VI, columns=ITEM_NAMES)
df_pulp["TỔNG"] = df_pulp.sum(axis=1)

print(f"\nMa trận phân bổ tối ưu x_{{j,r}} (tỷ VND):\n")
print(df_pulp.round(0).to_string())
print(f"\nKiểm tra tổng toàn bộ: {df_pulp['TỔNG'].sum():,.0f} / 50.000 tỷ")

# Kiểm tra C5
M_val = pulp.value(M_var)
print(f"\nKiểm tra C5 (λ={LAMBDA}, Dmax={M_val:.1f}):")
for r, name in zip(REGIONS, REGION_NAMES_VI):
    d_r = D0_dict[r] + GAMMA * pulp.value(x[r]['D'])
    ok  = "✅" if d_r >= LAMBDA * M_val - 0.01 else "❌"
    print(f"  {name:<25}: D_sau = {d_r:.1f}  ≥  λ*Dmax = {LAMBDA*M_val:.1f}  {ok}")

# ============================================================
# CELL 4 — CÂU 4.4.2: Cài đặt lại bằng CVXPY, so sánh PuLP
# ============================================================
print("=" * 65)
print("CÂU 4.4.2 — GIẢI BẰNG CVXPY")
print("=" * 65)

# Biến quyết định: ma trận X (6×4), mỗi phần tử >= 0
X_cv = cp.Variable((NR, NJ), nonneg=True)

# Biến phụ M cho C5
M_cv = cp.Variable(nonneg=True)

# ── Hàm mục tiêu ───────────────────────────────────────────
objective_cv = cp.Maximize(cp.sum(cp.multiply(BETA_MAT, X_cv)))

# ── Ràng buộc ──────────────────────────────────────────────
cons = []

# C1
cons.append(cp.sum(X_cv) <= 50000)

# C2 & C3: Sàn và trần từng vùng
for r in range(NR):
    cons.append(cp.sum(X_cv[r, :]) >= 5000)
    cons.append(cp.sum(X_cv[r, :]) <= 12000)

# C4: Sàn nhân lực (cột index 3 = H)
cons.append(cp.sum(X_cv[:, 3]) >= 12000)

# C5: Công bằng số hóa (cột index 1 = D)
for r in range(NR):
    d_r = D0[r] + GAMMA * X_cv[r, 1]
    cons.append(d_r <= M_cv)           # C5a
    cons.append(d_r >= LAMBDA * M_cv)  # C5b

# ── Giải ───────────────────────────────────────────────────
prob_cv = cp.Problem(objective_cv, cons)
prob_cv.solve(solver=cp.GLPK, verbose=False)

# Nếu GLPK không có thì dùng SCS
if prob_cv.status not in ["optimal", "optimal_inaccurate"]:
    prob_cv.solve(solver=cp.SCS, verbose=False)

Z_cvxpy    = prob_cv.value
alloc_cvxpy = X_cv.value

print(f"\nTrạng thái  : {prob_cv.status}")
print(f"Z* GDP gain : {Z_cvxpy:>12,.2f}  tỷ VND")

df_cvxpy = pd.DataFrame(alloc_cvxpy, index=REGION_NAMES_VI, columns=ITEM_NAMES)
df_cvxpy["TỔNG"] = df_cvxpy.sum(axis=1)
print(f"\nMa trận phân bổ tối ưu (CVXPY):\n")
print(df_cvxpy.round(0).to_string())

# ── So sánh PuLP vs CVXPY ──────────────────────────────────
diff_Z   = abs(Z_pulp - Z_cvxpy)
diff_max = np.abs(alloc_pulp - alloc_cvxpy).max()

print("\n" + "─" * 55)
print("SO SÁNH KẾT QUẢ PuLP vs CVXPY")
print("─" * 55)
print(f"  Z* PuLP              = {Z_pulp:>12,.2f}  tỷ VND")
print(f"  Z* CVXPY             = {Z_cvxpy:>12,.2f}  tỷ VND")
print(f"  Chênh lệch Z*        = {diff_Z:>12,.4f}  tỷ VND")
print(f"  Sai số ma trận (max) = {diff_max:>12,.4f}  tỷ VND")
if diff_Z < 1:
    print("\n  ✅ Hai phương pháp cho kết quả GIỐNG NHAU (sai số < 1 tỷ)")
else:
    print("\n  ⚠️  Hai phương pháp có chênh lệch — kiểm tra lại solver")

# ============================================================
# CELL 5 — CÂU 4.4.3: Heatmap phân bổ tối ưu
# Vùng nào nhận nhiều nhất? Hạng mục nào ưu tiên?
# ============================================================
print("=" * 65)
print("CÂU 4.4.3 — HEATMAP PHÂN BỔ TỐI ƯU")
print("=" * 65)

# Dùng kết quả PuLP (không có cột TỔNG để vẽ heatmap)
df_heat = pd.DataFrame(alloc_pulp, index=REGION_NAMES_VI, columns=ITEM_NAMES)

fig, axes = plt.subplots(1, 2, figsize=(16, 5), facecolor="#F4F6F9")

# ── Heatmap 1: Giá trị tuyệt đối (tỷ VND) ─────────────────
sns.heatmap(
    df_heat,
    annot=True, fmt=".0f", cmap="Blues",
    linewidths=0.5, linecolor="white", ax=axes[0],
    cbar_kws={"label": "Tỷ VND"},
    annot_kws={"size": 11},
)
axes[0].set_title("Phân bổ tối ưu tuyệt đối (tỷ VND)",
                  fontsize=12, fontweight="bold", color="#1B4F72")
axes[0].tick_params(axis="x", rotation=20, labelsize=9)
axes[0].tick_params(axis="y", rotation=0, labelsize=9)

# ── Heatmap 2: Tỷ trọng % trong từng vùng ─────────────────
df_pct = df_heat.div(df_heat.sum(axis=1), axis=0) * 100

sns.heatmap(
    df_pct,
    annot=True, fmt=".1f", cmap="YlOrRd",
    linewidths=0.5, linecolor="white", ax=axes[1],
    cbar_kws={"label": "% trong vùng"},
    annot_kws={"size": 11},
)
axes[1].set_title("Cơ cấu hạng mục trong từng vùng (%)",
                  fontsize=12, fontweight="bold", color="#1B4F72")
axes[1].tick_params(axis="x", rotation=20, labelsize=9)
axes[1].tick_params(axis="y", rotation=0, labelsize=9)

plt.suptitle("CÂU 4.4.3 — Heatmap phân bổ ngân sách số tối ưu theo vùng-hạng mục",
             fontsize=13, fontweight="bold", color="#1B4F72", y=1.02)
plt.tight_layout()
plt.show()

# ── Nhận xét tóm tắt ───────────────────────────────────────
tong_vung     = df_heat.sum(axis=1).sort_values(ascending=False)
uu_tien_vung  = df_heat.idxmax(axis=1)

print("\n📊 Tổng ngân sách mỗi vùng & hạng mục ưu tiên:")
print(f"{'Vùng':<28} {'Tổng (tỷ)':>10}   Ưu tiên")
print("─" * 58)
for vung in tong_vung.index:
    print(f"  {vung:<26} {tong_vung[vung]:>10,.0f}   {uu_tien_vung[vung]}")

print(f"\n► Vùng nhận nhiều nhất : {tong_vung.index[0]}  ({tong_vung.iloc[0]:,.0f} tỷ)")
print(f"► Vùng nhận ít nhất    : {tong_vung.index[-1]}  ({tong_vung.iloc[-1]:,.0f} tỷ)")

# ============================================================
# CELL 6 — CÂU 4.4.4: So sánh có/không có ràng buộc C5
# Tính chi phí kinh tế của công bằng vùng miền
# ============================================================
print("=" * 65)
print("CÂU 4.4.4 — CHI PHÍ KINH TẾ CỦA CÔNG BẰNG VÙNG MIỀN")
print("=" * 65)

# ── Mô hình KHÔNG có C5 (bỏ ràng buộc công bằng) ──────────
mdl2 = pulp.LpProblem("VN_Budget_NoC5", pulp.LpMaximize)
x2   = pulp.LpVariable.dicts('x2', (REGIONS, ITEMS), lowBound=0)

mdl2 += pulp.lpSum(BETA[(r,j)] * x2[r][j]
                   for r in REGIONS for j in ITEMS)

# C1, C2, C3, C4 giữ nguyên — BỎ C5
mdl2 += pulp.lpSum(x2[r][j] for r in REGIONS for j in ITEMS) <= 50000

for r in REGIONS:
    mdl2 += pulp.lpSum(x2[r][j] for j in ITEMS) >= 5000
    mdl2 += pulp.lpSum(x2[r][j] for j in ITEMS) <= 12000

mdl2 += pulp.lpSum(x2[r]['H'] for r in REGIONS) >= 12000

mdl2.solve(pulp.PULP_CBC_CMD(msg=False))

Z_no_c5    = pulp.value(mdl2.objective)
alloc_no_c5 = np.array([
    [pulp.value(x2[r][j]) for j in ITEMS]
    for r in REGIONS
])

# ── Tính chi phí kinh tế ───────────────────────────────────
equity_cost   = Z_no_c5 - Z_pulp
equity_pct    = equity_cost / Z_no_c5 * 100

print(f"\n  Z* CÓ C5  (có công bằng)  = {Z_pulp:>12,.2f}  tỷ VND")
print(f"  Z* BỎ C5  (không C5)      = {Z_no_c5:>12,.2f}  tỷ VND")
print(f"\n  💸 Chi phí kinh tế công bằng = {equity_cost:>10,.2f}  tỷ VND GDP gain")
print(f"     Tương đương {equity_pct:.2f}% tổng GDP gain bị hi sinh")
print(f"     để đảm bảo mọi vùng đạt ≥ {LAMBDA*100:.0f}% mức số hóa cao nhất")

# ── Bảng so sánh hai phương án ─────────────────────────────
df_c5    = pd.DataFrame(alloc_pulp,  index=REGION_NAMES_VI, columns=ITEM_NAMES)
df_no_c5 = pd.DataFrame(alloc_no_c5, index=REGION_NAMES_VI, columns=ITEM_NAMES)
df_c5["TỔNG"]    = df_c5.sum(axis=1)
df_no_c5["TỔNG"] = df_no_c5.sum(axis=1)

print(f"\n─── Phân bổ CÓ C5 (Z* = {Z_pulp:,.0f} tỷ) ─────────────────")
print(df_c5.round(0).to_string())

print(f"\n─── Phân bổ BỎ C5 (Z* = {Z_no_c5:,.0f} tỷ) ─────────────────")
print(df_no_c5.round(0).to_string())

# ── Vẽ biểu đồ 3 panel ────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5), facecolor="#F4F6F9")

# Panel 1: Heatmap CÓ C5
sns.heatmap(df_c5.drop(columns="TỔNG"),
            annot=True, fmt=".0f", cmap="Blues",
            linewidths=0.5, linecolor="white", ax=axes[0],
            cbar_kws={"label": "Tỷ VND"}, annot_kws={"size": 9})
axes[0].set_title(f"CÓ ràng buộc C5\nZ* = {Z_pulp:,.0f} tỷ VND",
                  fontsize=11, fontweight="bold", color="#1B4F72")
axes[0].tick_params(axis="x", rotation=25, labelsize=8)
axes[0].tick_params(axis="y", rotation=0,  labelsize=8)

# Panel 2: Heatmap BỎ C5
sns.heatmap(df_no_c5.drop(columns="TỔNG"),
            annot=True, fmt=".0f", cmap="Oranges",
            linewidths=0.5, linecolor="white", ax=axes[1],
            cbar_kws={"label": "Tỷ VND"}, annot_kws={"size": 9})
axes[1].set_title(f"BỎ ràng buộc C5\nZ* = {Z_no_c5:,.0f} tỷ VND",
                  fontsize=11, fontweight="bold", color="#D35400")
axes[1].tick_params(axis="x", rotation=25, labelsize=8)
axes[1].tick_params(axis="y", rotation=0,  labelsize=8)

# Panel 3: Heatmap chênh lệch Δ = BỎ_C5 - CÓ_C5
df_diff = df_no_c5.drop(columns="TỔNG") - df_c5.drop(columns="TỔNG")
sns.heatmap(df_diff,
            annot=True, fmt=".0f", cmap="RdYlGn", center=0,
            linewidths=0.5, linecolor="white", ax=axes[2],
            cbar_kws={"label": "Δ tỷ VND"}, annot_kws={"size": 9})
axes[2].set_title(f"Chênh lệch (Bỏ C5 − Có C5)\n"
                  f"Chi phí công bằng = {equity_cost:,.0f} tỷ ({equity_pct:.1f}%)",
                  fontsize=11, fontweight="bold", color="#922B21")
axes[2].tick_params(axis="x", rotation=25, labelsize=8)
axes[2].tick_params(axis="y", rotation=0,  labelsize=8)

plt.suptitle("CÂU 4.4.4 — Chi phí kinh tế của ràng buộc công bằng vùng miền (C5)",
             fontsize=13, fontweight="bold", color="#1B4F72", y=1.02)
plt.tight_layout()
plt.show()

# ── Phân tích vùng bị ảnh hưởng nhiều nhất ────────────────
delta_tong = (df_no_c5["TỔNG"] - df_c5["TỔNG"]).sort_values()
print("\n📊 Thay đổi ngân sách mỗi vùng khi BỎ C5 (tỷ VND):")
print(f"{'Vùng':<28} {'Thay đổi':>10}   Ý nghĩa")
print("─" * 65)
for vung, val in delta_tong.items():
    arrow = "▲ được thêm" if val > 0 else "▼ bị cắt   "
    print(f"  {vung:<26} {val:>+10,.0f}   {arrow}")
print("\n  (Khi BỎ C5: vốn tập trung về vùng có β_AI cao nhất → SE và RRD)")