# -*- coding: utf-8 -*-
"""Bai07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUnZFl8TzqfyqLCCx2gI0x9bkudult0t
"""

# ============================================================
# CELL 1 — IMPORT & MOUNT GOOGLE DRIVE
# ============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
import warnings
warnings.filterwarnings("ignore")

from google.colab import drive
drive.mount('/content/drive')

# ── Tham số từ đề bài 7 ────────────────────────────────────
NR, NJ = 6, 4   # 6 vùng × 4 hạng mục = 24 biến

REGION_NAMES = [
    "Trung du MN Bắc",
    "Đồng bằng sông Hồng",
    "Bắc TB + DHMT",
    "Tây Nguyên",
    "Đông Nam Bộ",
    "Đồng bằng sông CL",
]
ITEM_NAMES = ['Hạ tầng (I)', 'CĐS DN (D)', 'AI', 'Nhân lực (H)']

# Beta matrix (6×4) — từ Bài 4
BETA_MAT = np.array([
    [1.15, 0.85, 0.55, 1.30],  # NMM
    [0.95, 1.25, 1.40, 1.05],  # RRD
    [1.05, 0.95, 0.85, 1.15],  # NCC
    [1.20, 0.75, 0.45, 1.35],  # CH
    [0.90, 1.30, 1.55, 1.00],  # SE
    [1.10, 0.85, 0.65, 1.25],  # MD
])

# Tham số bổ sung bài 7 (Bảng 7.3)
E   = np.array([0.42, 0.55, 0.48, 0.32, 0.62, 0.38])  # phát thải
RHO = np.array([0.18, 0.45, 0.28, 0.12, 0.52, 0.22])  # rủi ro AI
SIG = np.array([0.32, 0.28, 0.30, 0.35, 0.25, 0.30])  # giảm rủi ro/H

# Ràng buộc (C1-C4, bỏ C5 cho bài toán đa mục tiêu)
BUDGET_TOTAL = 50000   # C1: tổng ≤ 50.000
FLOOR_REGION = 5000    # C2: sàn mỗi vùng ≥ 5.000
CEIL_REGION  = 12000   # C3: trần mỗi vùng ≤ 12.000
FLOOR_H      = 12000   # C4: sàn nhân lực H ≥ 12.000

COLORS = {
    "primary":  "#1B4F72",
    "accent":   "#E74C3C",
    "green":    "#1E8449",
    "orange":   "#D35400",
    "light_bg": "#F4F6F9",
}

print("✅ Import xong!")
print(f"   Số biến quyết định : {NR * NJ} (6 vùng × 4 hạng mục)")
print(f"   Số hàm mục tiêu    : 4 (GDP, Bao trùm, Môi trường, An ninh)")
print(f"   Số ràng buộc       : 14 (C1×1 + C2×6 + C3×6 + C4×1)")

# ============================================================
# CELL 2 — CÂU 7.4.1
# Định nghĩa VietnamDigitalProblem kế thừa ElementwiseProblem
# Chạy NSGA-II: pop_size=100, n_gen=200
# ============================================================
from pymoo.core.problem import ElementwiseProblem
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.optimize import minimize as pymoo_minimize
from pymoo.termination import get_termination

print("=" * 65)
print("CÂU 7.4.1 — NSGA-II TỐI ƯU ĐA MỤC TIÊU")
print("=" * 65)

class VietnamDigitalProblem(ElementwiseProblem):
    def __init__(self):
        super().__init__(
            n_var=24,
            n_obj=4,
            n_ieq_constr=14,
            xl=np.zeros(24),
            xu=np.ones(24) * 12000,
        )
        self.beta = BETA_MAT
        self.e    = E
        self.rho  = RHO
        self.sig  = SIG

    def _evaluate(self, x, out, *args, **kwargs):
        X = x.reshape(NR, NJ)

        f1 = -(self.beta * X).sum()
        sums = X.sum(axis=1)
        f2 = np.abs(sums - sums.mean()).mean()
        f3 = (self.e * (X[:,0] + X[:,2])).sum()
        f4 = (self.rho * X[:,2]).sum() - (self.sig * X[:,3]).sum()

        out['F'] = [f1, f2, f3, f4]

        g = []
        g.append(X.sum() - BUDGET_TOTAL)
        for r in range(NR):
            g.append(FLOOR_REGION - X[r,:].sum())
        for r in range(NR):
            g.append(X[r,:].sum() - CEIL_REGION)
        g.append(FLOOR_H - X[:,3].sum())
        out['G'] = g

# ── Chạy NSGA-II ───────────────────────────────────────────
problem     = VietnamDigitalProblem()
algorithm   = NSGA2(pop_size=100)
termination = get_termination("n_gen", 200)

print("\n⏳ Đang chạy NSGA-II (pop=100, gen=200)... khoảng 1-2 phút\n")

result = pymoo_minimize(
    problem,
    algorithm,
    termination,
    seed=42,
    verbose=False,   # ← tắt bảng log
)

print("✅ NSGA-II hoàn tất!")
print(f"   Số nghiệm trong tập Pareto : {len(result.F)}")
print(f"   f1 GDP gain tốt nhất       : {-result.F[:,0].min():>12,.2f}  tỷ VND")
print(f"   f2 bất bình đẳng nhỏ nhất  : {result.F[:,1].min():>12,.2f}")
print(f"   f3 phát thải nhỏ nhất      : {result.F[:,2].min():>12,.2f}")
print(f"   f4 rủi ro nhỏ nhất         : {result.F[:,3].min():>12,.2f}")

# ============================================================
# CELL 3 — CÂU 7.4.2
# Vẽ scatter 3D (f1, f2, f3) và parallel coordinates 4 mục tiêu
# ============================================================
print("=" * 65)
print("CÂU 7.4.2 — TRỰC QUAN HÓA TẬP PARETO")
print("=" * 65)

F = result.F.copy()
# Đổi f1 về GDP gain dương để dễ đọc
GDP_gain = -F[:, 0]
Inequality = F[:, 1]
Emission   = F[:, 2]
Security   = F[:, 3]

fig = plt.figure(figsize=(18, 7), facecolor=COLORS["light_bg"])

# ── Panel 1: Scatter 3D (f1, f2, f3) ───────────────────────
ax3d = fig.add_subplot(121, projection='3d')
sc = ax3d.scatter(
    GDP_gain, Inequality, Emission,
    c=Security, cmap='RdYlGn_r',
    s=30, alpha=0.75, edgecolors='none'
)
cbar = fig.colorbar(sc, ax=ax3d, shrink=0.5, pad=0.1)
cbar.set_label('f4: Rủi ro an ninh', fontsize=9)
ax3d.set_xlabel('f1: GDP gain (tỷ)', fontsize=9, labelpad=8)
ax3d.set_ylabel('f2: Bất bình đẳng', fontsize=9, labelpad=8)
ax3d.set_zlabel('f3: Phát thải',      fontsize=9, labelpad=8)
ax3d.set_title('Đường biên Pareto 3D\n(màu = rủi ro an ninh f4)',
               fontsize=11, fontweight='bold', color=COLORS["primary"])
ax3d.view_init(elev=25, azim=45)

# ── Panel 2: Parallel Coordinates 4 mục tiêu ───────────────
ax_pc = fig.add_subplot(122)

# Chuẩn hóa [0,1] để vẽ
def norm_col(arr): return (arr - arr.min()) / (arr.max() - arr.min() + 1e-12)

F_norm = np.column_stack([
    norm_col(GDP_gain),   # f1: càng cao càng tốt
    norm_col(Inequality), # f2: càng thấp càng tốt
    norm_col(Emission),   # f3: càng thấp càng tốt
    norm_col(Security),   # f4: càng thấp càng tốt
])

# Màu theo GDP gain
colors_pc = cm.RdYlGn(norm_col(GDP_gain))

for i in range(len(F_norm)):
    ax_pc.plot(range(4), F_norm[i], color=colors_pc[i], alpha=0.25, linewidth=0.8)

ax_pc.set_xticks(range(4))
ax_pc.set_xticklabels([
    'f1: GDP gain\n(↑ tốt hơn)',
    'f2: Bất bình\nđẳng (↓ tốt)',
    'f3: Phát thải\n(↓ tốt)',
    'f4: Rủi ro\nan ninh (↓ tốt)',
], fontsize=9)
ax_pc.set_ylabel('Giá trị chuẩn hóa [0,1]', fontsize=9)
ax_pc.set_title('Biểu đồ song song (Parallel Coordinates)\n4 mục tiêu trên toàn tập Pareto',
                fontsize=11, fontweight='bold', color=COLORS["primary"])
ax_pc.set_ylim(-0.05, 1.05)
ax_pc.grid(axis='y', alpha=0.3)

# Thêm colorbar GDP
sm = plt.cm.ScalarMappable(cmap='RdYlGn',
     norm=plt.Normalize(GDP_gain.min(), GDP_gain.max()))
sm.set_array([])
cbar2 = fig.colorbar(sm, ax=ax_pc, shrink=0.6)
cbar2.set_label('f1: GDP gain', fontsize=9)

plt.suptitle("CÂU 7.4.2 — Tập nghiệm Pareto: đánh đổi giữa 4 mục tiêu",
             fontsize=13, fontweight='bold', color=COLORS["primary"], y=1.01)
plt.tight_layout()
plt.show()

# Thống kê tập Pareto
print(f"\n📊 Thống kê tập Pareto ({len(F)} nghiệm):")
print(f"{'Mục tiêu':<30} {'Min':>12} {'Max':>12} {'Mean':>12}")
print("─" * 70)
print(f"{'f1 GDP gain (tỷ VND)':<30} {GDP_gain.min():>12,.1f} {GDP_gain.max():>12,.1f} {GDP_gain.mean():>12,.1f}")
print(f"{'f2 Bất bình đẳng (MAD)':<30} {Inequality.min():>12,.1f} {Inequality.max():>12,.1f} {Inequality.mean():>12,.1f}")
print(f"{'f3 Phát thải':<30} {Emission.min():>12,.1f} {Emission.max():>12,.1f} {Emission.mean():>12,.1f}")
print(f"{'f4 Rủi ro an ninh ròng':<30} {Security.min():>12,.1f} {Security.max():>12,.1f} {Security.mean():>12,.1f}")

# ============================================================
# CELL 4 — CÂU 7.4.3
# Áp dụng TOPSIS lên tập Pareto
# Trọng số: f1=0.40, f2=0.25, f3=0.20, f4=0.15
# ============================================================
print("=" * 65)
print("CÂU 7.4.3 — TOPSIS CHỌN NGHIỆM THỎA HIỆP")
print("=" * 65)

# Trọng số ưu tiên chính sách theo đề bài
W_TOPSIS = np.array([0.40, 0.25, 0.20, 0.15])

# is_benefit: f1 (GDP) càng cao càng tốt → True
#             f2,f3,f4 càng thấp càng tốt → False
IS_BENEFIT = [True, False, False, False]

def topsis(F_matrix, weights, is_benefit):
    """
    TOPSIS chuẩn cho tập nghiệm Pareto.
    F_matrix: (n_solutions, n_objectives)
    Trả về: mảng C* và index nghiệm tốt nhất
    """
    n = F_matrix.shape[0]
    # Chuẩn hóa vector
    norms = np.sqrt((F_matrix**2).sum(axis=0))
    norms[norms == 0] = 1e-12
    R = F_matrix / norms
    V = R * weights  # nhân trọng số

    # Lý tưởng dương & âm
    A_star = np.array([
        V[:, j].max() if is_benefit[j] else V[:, j].min()
        for j in range(len(weights))
    ])
    A_neg = np.array([
        V[:, j].min() if is_benefit[j] else V[:, j].max()
        for j in range(len(weights))
    ])

    # Khoảng cách Euclide
    S_star = np.sqrt(((V - A_star)**2).sum(axis=1))
    S_neg  = np.sqrt(((V - A_neg )**2).sum(axis=1))

    # Hệ số gần gũi
    C_star = S_neg / (S_star + S_neg + 1e-12)
    best   = np.argmax(C_star)
    return C_star, best

# Ma trận F với f1 đổi dấu về dương (GDP gain)
F_topsis = np.column_stack([GDP_gain, Inequality, Emission, Security])

C_star, best_idx = topsis(F_topsis, W_TOPSIS, IS_BENEFIT)

# Kết quả nghiệm thỏa hiệp
x_compromise = result.X[best_idx]
X_compromise = x_compromise.reshape(NR, NJ)

print(f"\nNghiệm thỏa hiệp tại index {best_idx}")
print(f"Hệ số gần gũi C* = {C_star[best_idx]:.4f}\n")
print(f"{'Mục tiêu':<30} {'Giá trị':>15}")
print("─" * 50)
print(f"{'f1 GDP gain (tỷ VND)':<30} {GDP_gain[best_idx]:>15,.2f}")
print(f"{'f2 Bất bình đẳng':<30} {Inequality[best_idx]:>15,.2f}")
print(f"{'f3 Phát thải':<30} {Emission[best_idx]:>15,.2f}")
print(f"{'f4 Rủi ro an ninh':<30} {Security[best_idx]:>15,.2f}")

# Phân bổ tối ưu thỏa hiệp
df_comp = pd.DataFrame(
    X_compromise,
    index=REGION_NAMES,
    columns=ITEM_NAMES
)
df_comp["TỔNG"] = df_comp.sum(axis=1)
print(f"\nPhân bổ ngân sách nghiệm thỏa hiệp (tỷ VND):\n")
print(df_comp.round(0).to_string())

# ── Vẽ vị trí nghiệm thỏa hiệp trên Pareto 3D ─────────────
fig = plt.figure(figsize=(10, 7), facecolor=COLORS["light_bg"])
ax  = fig.add_subplot(111, projection='3d')

# Toàn bộ tập Pareto
ax.scatter(GDP_gain, Inequality, Emission,
           c=COLORS["primary"], s=15, alpha=0.4, label='Tập Pareto')

# Đánh dấu nghiệm thỏa hiệp
ax.scatter(GDP_gain[best_idx], Inequality[best_idx], Emission[best_idx],
           c=COLORS["accent"], s=200, marker='*', zorder=5, label='Nghiệm thỏa hiệp')

# Nghiệm GDP cao nhất
top_gdp = np.argmax(GDP_gain)
ax.scatter(GDP_gain[top_gdp], Inequality[top_gdp], Emission[top_gdp],
           c=COLORS["orange"], s=150, marker='^', zorder=5, label='GDP cao nhất')

ax.set_xlabel('f1: GDP gain', fontsize=9, labelpad=8)
ax.set_ylabel('f2: Bất bình đẳng', fontsize=9, labelpad=8)
ax.set_zlabel('f3: Phát thải', fontsize=9, labelpad=8)
ax.set_title("CÂU 7.4.3 — Nghiệm thỏa hiệp TOPSIS\ntrên đường biên Pareto 3D",
             fontsize=11, fontweight='bold', color=COLORS["primary"])
ax.legend(fontsize=9)
ax.view_init(elev=25, azim=45)
plt.tight_layout()
plt.show()

# ============================================================
# CELL 5 — CÂU 7.4.4
# Phân tích chi phí cơ hội: nghiệm GDP cao nhất hi sinh
# bao nhiêu % về bao trùm và môi trường so với thỏa hiệp?
# ============================================================
print("=" * 65)
print("CÂU 7.4.4 — CHI PHÍ CƠ HỘI CỦA CÁC MỤC TIÊU")
print("=" * 65)

# ── 3 nghiệm đặc biệt để so sánh ──────────────────────────
top_gdp   = np.argmax(GDP_gain)    # Nghiệm GDP cao nhất
top_eq    = np.argmin(Inequality)  # Nghiệm bình đẳng nhất
top_env   = np.argmin(Emission)    # Nghiệm xanh nhất
top_sec   = np.argmin(Security)    # Nghiệm an ninh tốt nhất

nghiem = {
    "⭐ Thỏa hiệp (TOPSIS)": best_idx,
    "📈 GDP cao nhất"       : top_gdp,
    "🤝 Bình đẳng nhất"     : top_eq,
    "🌿 Phát thải thấp nhất": top_env,
    "🔒 An ninh tốt nhất"   : top_sec,
}

# Bảng so sánh
rows = []
for label, idx in nghiem.items():
    rows.append({
        "Nghiệm"             : label,
        "f1 GDP gain (tỷ)"   : round(GDP_gain[idx], 1),
        "f2 Bất bình đẳng"   : round(Inequality[idx], 1),
        "f3 Phát thải"       : round(Emission[idx], 1),
        "f4 Rủi ro"          : round(Security[idx], 1),
        "C* TOPSIS"          : round(C_star[idx], 4),
    })

df_compare = pd.DataFrame(rows).set_index("Nghiệm")
print("\nBảng so sánh 5 nghiệm đặc biệt:\n")
print(df_compare.to_string())

# ── Chi phí cơ hội của nghiệm GDP cao nhất ────────────────
gdp_best_val = GDP_gain[top_gdp]
gdp_comp_val = GDP_gain[best_idx]
eq_best_val  = Inequality[top_gdp]
eq_comp_val  = Inequality[best_idx]
em_best_val  = Emission[top_gdp]
em_comp_val  = Emission[best_idx]

print(f"\n📊 Chi phí cơ hội khi chọn nghiệm GDP cao nhất so với thỏa hiệp:")
print(f"   GDP gain được thêm  : +{gdp_best_val - gdp_comp_val:>10,.2f} tỷ VND "
      f"(+{(gdp_best_val/gdp_comp_val-1)*100:.2f}%)")
print(f"   Bất bình đẳng tăng  : +{eq_best_val - eq_comp_val:>10,.2f}         "
      f"(+{(eq_best_val/eq_comp_val-1)*100:.2f}%)")
print(f"   Phát thải tăng      : +{em_best_val - em_comp_val:>10,.2f}         "
      f"(+{(em_best_val/em_comp_val-1)*100:.2f}%)")

# ── Biểu đồ radar (spider chart) so sánh ────────────────

categories = ['GDP gain', 'Bình đẳng\n(đảo)', 'Môi trường\n(đảo)', 'An ninh\n(đảo)']
N = 4
angles = np.linspace(0, 2*np.pi, N, endpoint=False).tolist()
angles += angles[:1]  # đóng vòng

# Chuẩn hóa: f1 cao=tốt, f2/f3/f4 thấp=tốt → đảo f2/f3/f4
def radar_score(idx):
    return [
        norm_col(GDP_gain)[idx],
        1 - norm_col(Inequality)[idx],
        1 - norm_col(Emission)[idx],
        1 - norm_col(Security)[idx],
    ]

fig, ax = plt.subplots(figsize=(8, 8),
                       subplot_kw=dict(polar=True),
                       facecolor=COLORS["light_bg"])

plot_nghiem = {
    "Thỏa hiệp": (best_idx, COLORS["accent"],   '-',  2.5),
    "GDP max"  : (top_gdp,  COLORS["primary"],  '--', 1.5),
    "Bình đẳng": (top_eq,   COLORS["green"],    ':',  1.5),
    "Xanh"     : (top_env,  COLORS["orange"],   '-.', 1.5),
}

for label, (idx, color, ls, lw) in plot_nghiem.items():
    vals = radar_score(idx) + radar_score(idx)[:1]
    ax.plot(angles, vals, color=color, linestyle=ls,
            linewidth=lw, label=label)
    ax.fill(angles, vals, color=color, alpha=0.08)

ax.set_xticks(angles[:-1])
ax.set_xticklabels(categories, fontsize=11)
ax.set_ylim(0, 1)
ax.set_yticks([0.25, 0.5, 0.75, 1.0])
ax.set_yticklabels(['0.25','0.50','0.75','1.00'], fontsize=7)
ax.set_title("CÂU 7.4.4 — Radar chart: đánh đổi giữa các nghiệm\n"
             "(giá trị chuẩn hóa, càng xa tâm càng tốt)",
             fontsize=12, fontweight='bold',
             color=COLORS["primary"], pad=20)
ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.15), fontsize=10)
plt.tight_layout()
plt.show()

print("\n💡 Kết luận chi phí cơ hội:")
print(f"   Khi chọn nghiệm GDP cao nhất thay vì thỏa hiệp:")
print(f"   → Được thêm GDP nhưng hi sinh bình đẳng và môi trường")
print(f"   → Nghiệm TOPSIS cân bằng cả 4 mục tiêu theo trọng số")
print(f"      (0.40 GDP | 0.25 bao trùm | 0.20 môi trường | 0.15 an ninh)")