# -*- coding: utf-8 -*-
"""Bai06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16BGyEv6h5IuNrybIZYJ8X6wVzE_XQk3I
"""

from google.colab import drive
drive.mount('/content/drive')

# Sau khi mount xong, đọc file từ Drive
# ⚠️ Sửa đường dẫn nếu bạn để file trong thư mục khác
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

DRIVE_PATH = '/content/drive/MyDrive/'  # thay bằng đường dẫn thực tế

try:
    df = pd.read_csv(DRIVE_PATH + 'vietnam_regions_2024.csv')
    print("✅ Đọc file từ Drive thành công!")
except:
    print("❌ Không tìm thấy file trong Drive!")
    print("   Kiểm tra lại đường dẫn DRIVE_PATH")


ten_viet = [
    'TDMN phía Bắc',
    'ĐB sông Hồng',
    'BTB + DH Trung Bộ',
    'Tây Nguyên',
    'Đông Nam Bộ',
    'ĐB sông Cửu Long'
]
df['region_vi'] = ten_viet

# 8 tiêu chí theo đúng đề bài Bảng 6.3
criteria = [
    'grdp_per_capita_million_VND',   # C1 — GRDP/người  → benefit
    'fdi_registered_billion_USD',    # C2 — FDI          → benefit
    'digital_index_0_100',           # C3 — Digital Index→ benefit
    'ai_readiness_0_100',            # C4 — AI Readiness → benefit
    'trained_labor_pct',             # C5 — LĐ qua ĐT   → benefit
    'rd_intensity_pct',              # C6 — R&D/GRDP     → benefit
    'internet_penetration_pct',      # C7 — Internet     → benefit
    'gini_coef',                     # C8 — Gini         → cost
]

ten_tieu_chi = [
    'GRDP/người', 'FDI', 'Digital\nIndex',
    'AI\nReadiness', 'LĐ qua ĐT', 'R&D/GRDP',
    'Internet', 'Gini'
]

# True = benefit (cao tốt), False = cost (thấp tốt)
is_benefit = [True, True, True, True, True, True, True, False]

X       = df[criteria].values.astype(float)
regions = df['region_vi'].values

# In bảng dữ liệu gốc
print("\n=== MA TRẬN QUYẾT ĐỊNH GỐC ===")
df_show = df[['region_vi'] + criteria].copy()
df_show.columns = ['Vùng'] + ten_tieu_chi
print(df_show.to_string(index=False))
print(f"\nKích thước: {X.shape[0]} vùng × {X.shape[1]} tiêu chí")

# ═══════════════════════════════════════════════════════════════
# HÀM TOPSIS — cài đặt từ đầu bằng numpy
# ═══════════════════════════════════════════════════════════════
def topsis(X, weights, is_benefit, verbose=False):
    """
    X          : ma trận quyết định (n_alt × n_crit)
    weights    : trọng số (tổng = 1)
    is_benefit : list bool
    """
    weights = np.array(weights)

    # Bước 1: Chuẩn hóa vector
    # r_ij = x_ij / sqrt(Σ x_ij²)
    norm_factor = np.sqrt((X**2).sum(axis=0))
    R = X / norm_factor

    if verbose:
        print("  Bước 1 — Ma trận chuẩn hóa R:")
        df_r = pd.DataFrame(R.round(4), index=regions,
                            columns=ten_tieu_chi)
        print(df_r.to_string())

    # Bước 2: Ma trận chuẩn hóa có trọng số
    # v_ij = w_j × r_ij
    V = R * weights

    if verbose:
        print("\n  Bước 2 — Ma trận có trọng số V:")
        df_v = pd.DataFrame(V.round(4), index=regions,
                            columns=ten_tieu_chi)
        print(df_v.to_string())

    # Bước 3: Lời giải lý tưởng dương A* và âm A-
    A_star = np.where(is_benefit, V.max(axis=0), V.min(axis=0))
    A_neg  = np.where(is_benefit, V.min(axis=0), V.max(axis=0))

    if verbose:
        print(f"\n  Bước 3 — A* (lý tưởng dương): "
              f"{A_star.round(4)}")
        print(f"           A- (lý tưởng âm)  : "
              f"{A_neg.round(4)}")

    # Bước 4: Khoảng cách Euclide
    S_star = np.sqrt(((V - A_star)**2).sum(axis=1))
    S_neg  = np.sqrt(((V - A_neg )**2).sum(axis=1))

    if verbose:
        print(f"\n  Bước 4 — S* : {S_star.round(4)}")
        print(f"           S- : {S_neg.round(4)}")

    # Bước 5: Hệ số gần gũi tương đối C*
    C_star = S_neg / (S_star + S_neg)

    return {
        'C_star' : C_star,
        'S_star' : S_star,
        'S_neg'  : S_neg,
        'V'      : V,
        'A_star' : A_star,
        'A_neg'  : A_neg,
        'rank'   : np.argsort(C_star)[::-1]
    }


# ── Câu 6.4.1 ────────────────────────────────────────────────
w_expert = np.array([0.10, 0.10, 0.15, 0.20, 0.15, 0.15, 0.05, 0.10])
print(f"Tổng trọng số chuyên gia = {w_expert.sum():.2f} ✅\n")

res1 = topsis(X, w_expert, is_benefit, verbose=True)

# Bảng kết quả
print("\n" + "=" * 65)
print("CÂU 6.4.1 — KẾT QUẢ TOPSIS TRỌNG SỐ CHUYÊN GIA")
print("w = [0.10, 0.10, 0.15, 0.20, 0.15, 0.15, 0.05, 0.10]")
print("=" * 65)
df_res1 = pd.DataFrame({
    'Vùng'    : regions,
    'S*'      : res1['S_star'].round(4),
    'S-'      : res1['S_neg'].round(4),
    'C* (điểm TOPSIS)': res1['C_star'].round(4),
    'Xếp hạng': [np.where(res1['rank']==i)[0][0]+1
                 for i in range(len(regions))]
}).sort_values('Xếp hạng').reset_index(drop=True)
print(df_res1.to_string(index=False))

print(f"\n🥇 Ưu tiên số 1: {regions[res1['rank'][0]]} "
      f"(C* = {res1['C_star'][res1['rank'][0]]:.4f})")
print(f"🥈 Ưu tiên số 2: {regions[res1['rank'][1]]} "
      f"(C* = {res1['C_star'][res1['rank'][1]]:.4f})")
print(f"🥉 Ưu tiên số 3: {regions[res1['rank'][2]]} "
      f"(C* = {res1['C_star'][res1['rank'][2]]:.4f})")

# Vẽ đồ thị
fig, ax = plt.subplots(figsize=(10, 5))
sorted_regions = [regions[i] for i in res1['rank']]
sorted_scores  = [res1['C_star'][i] for i in res1['rank']]
colors = ['#E84C4C','#E87A4C','#E8C44C',
          '#4CE882','#4C9BE8','#9B4CE8']

bars = ax.barh(sorted_regions[::-1], sorted_scores[::-1],
               color=colors[::-1], edgecolor='white', linewidth=1.5)
for bar, val in zip(bars, sorted_scores[::-1]):
    ax.text(bar.get_width() + 0.005,
            bar.get_y() + bar.get_height()/2,
            f'{val:.4f}', va='center', fontsize=10.5,
            fontweight='bold', color='navy')

ax.axvline(x=0.5, color='gray', linewidth=1.5,
           linestyle='--', alpha=0.6, label='C* = 0.5')
ax.set_title('TOPSIS — Xếp hạng 6 vùng ưu tiên AI\n'
             'Trọng số chuyên gia', fontsize=13, fontweight='bold')
ax.set_xlabel('Hệ số gần gũi C*')
ax.legend(); ax.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig('bai6_cau1_TOPSIS_expert.png', dpi=150, bbox_inches='tight')
plt.show()

# ═══════════════════════════════════════════════════════════════
# CÂU 6.4.2 — Trọng số ENTROPY (khách quan)
# ═══════════════════════════════════════════════════════════════
def entropy_weights(X):
    """
    Tính trọng số khách quan bằng phương pháp Entropy
    Bước 1: Chuẩn hóa P_ij = x_ij / Σx_ij
    Bước 2: Tính entropy E_j = -k × Σ P_ij × ln(P_ij)
    Bước 3: Độ phân kỳ d_j = 1 - E_j
    Bước 4: Trọng số w_j = d_j / Σd_j
    """
    # Bước 1: Chuẩn hóa theo cột
    P = X / X.sum(axis=0)

    # Bước 2: Entropy (thêm 1e-12 để tránh log(0))
    k = 1.0 / np.log(len(X))
    E = -k * np.nansum(P * np.log(P + 1e-12), axis=0)

    # Bước 3: Độ phân kỳ
    d = 1 - E

    # Bước 4: Trọng số
    w = d / d.sum()
    return w, E, d


w_entropy, E_vals, d_vals = entropy_weights(X)

# Bảng so sánh trọng số
print("=" * 65)
print("CÂU 6.4.2 — TRỌNG SỐ ENTROPY (khách quan)")
print("=" * 65)
df_weights = pd.DataFrame({
    'Tiêu chí'         : ten_tieu_chi,
    'Entropy E_j'      : E_vals.round(4),
    'Phân kỳ d_j'      : d_vals.round(4),
    'w Entropy'        : w_entropy.round(4),
    'w Chuyên gia'     : w_expert.round(4),
    'Chênh lệch'       : (w_entropy - w_expert).round(4),
})
print(df_weights.to_string(index=False))
print(f"\nTổng w Entropy = {w_entropy.sum():.4f} ✅")

# Giải TOPSIS với trọng số Entropy
res2 = topsis(X, w_entropy, is_benefit)

# Bảng so sánh xếp hạng
print("\n=== SO SÁNH XẾP HẠNG: CHUYÊN GIA vs ENTROPY ===")
rank1 = [np.where(res1['rank']==i)[0][0]+1 for i in range(6)]
rank2 = [np.where(res2['rank']==i)[0][0]+1 for i in range(6)]

df_compare = pd.DataFrame({
    'Vùng'             : regions,
    'C* Chuyên gia'    : res1['C_star'].round(4),
    'Hạng CG'          : rank1,
    'C* Entropy'       : res2['C_star'].round(4),
    'Hạng EN'          : rank2,
    'Thay đổi hạng'    : [rank2[i]-rank1[i] for i in range(6)]
})
df_compare = df_compare.sort_values('Hạng CG').reset_index(drop=True)
print(df_compare.to_string(index=False))

# Vẽ so sánh
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Biểu đồ 1: So sánh trọng số
ax1 = axes[0]
x_pos = np.arange(len(ten_tieu_chi))
width = 0.35
ax1.bar(x_pos - width/2, w_expert,  width, label='Chuyên gia',
        color='#4C9BE8', edgecolor='white', linewidth=1.2)
ax1.bar(x_pos + width/2, w_entropy, width, label='Entropy',
        color='#E87A4C', edgecolor='white', linewidth=1.2)
ax1.set_xticks(x_pos)
ax1.set_xticklabels(ten_tieu_chi, fontsize=9)
ax1.set_title('So sánh trọng số\nChuyên gia vs Entropy',
              fontsize=11, fontweight='bold')
ax1.set_ylabel('Trọng số')
ax1.legend(); ax1.grid(axis='y', alpha=0.3)

# Biểu đồ 2: So sánh điểm C*
ax2 = axes[1]
x_pos2 = np.arange(len(regions))
ax2.bar(x_pos2 - width/2, res1['C_star'], width,
        label='Chuyên gia', color='#4C9BE8',
        edgecolor='white', linewidth=1.2)
ax2.bar(x_pos2 + width/2, res2['C_star'], width,
        label='Entropy', color='#E87A4C',
        edgecolor='white', linewidth=1.2)
ax2.set_xticks(x_pos2)
ax2.set_xticklabels([r.replace(' ', '\n') for r in regions],
                    fontsize=8)
ax2.set_title('So sánh điểm C*\nChuyên gia vs Entropy',
              fontsize=11, fontweight='bold')
ax2.set_ylabel('Hệ số gần gũi C*')
ax2.legend(); ax2.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('bai6_cau2_entropy.png', dpi=150, bbox_inches='tight')
plt.show()

# ═══════════════════════════════════════════════════════════════
# CÂU 6.4.3 — Phân tích độ nhạy: w_AI (index 3) từ 0.10→0.40
# ═══════════════════════════════════════════════════════════════
w_AI_range = np.arange(0.10, 0.45, 0.05)

# idx=3 là AI Readiness trong danh sách criteria
AI_idx = 3

rank_matrix  = []
score_matrix = []

for w_AI in w_AI_range:
    # Tính lại trọng số các tiêu chí còn lại (giữ tỷ lệ)
    w_new = w_expert.copy().astype(float)
    delta = w_AI - w_expert[AI_idx]        # phần tăng/giảm
    # Phân bổ delta cho các tiêu chí còn lại theo tỷ lệ
    other_idx = [i for i in range(len(w_expert)) if i != AI_idx]
    total_other = w_expert[other_idx].sum()
    for i in other_idx:
        w_new[i] = w_expert[i] - delta * (w_expert[i]/total_other)
    w_new[AI_idx] = w_AI

    # Đảm bảo không âm
    w_new = np.clip(w_new, 0.01, None)
    w_new = w_new / w_new.sum()           # chuẩn hóa lại = 1

    res = topsis(X, w_new, is_benefit)
    rank_matrix.append(res['rank'].argsort() + 1)  # hạng từng vùng
    score_matrix.append(res['C_star'])

rank_matrix  = np.array(rank_matrix)   # shape (8, 6)
score_matrix = np.array(score_matrix)

# Bảng top-3 theo từng mức w_AI
print("=" * 65)
print("CÂU 6.4.3 — ĐỘ NHẠY: TOP-3 THEO w_AI")
print("=" * 65)
print(f"  {'w_AI':>6} | {'#1':22s} | {'#2':22s} | {'#3':22s}")
print("  " + "─" * 75)
for i, w_AI in enumerate(w_AI_range):
    top3 = np.argsort(score_matrix[i])[::-1][:3]
    marker = " ←" if abs(w_AI - 0.20) < 0.001 else ""
    print(f"  {w_AI:>6.2f} | {regions[top3[0]]:22s} | "
          f"{regions[top3[1]]:22s} | {regions[top3[2]]}{marker}")

# Vẽ biểu đồ độ nhạy
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Đồ thị 1: Điểm C* theo w_AI
ax1 = axes[0]
mau_vung = ['#E84C4C','#4C9BE8','#4CE882',
            '#E8D84C','#C44CE8','#E87A4C']
for v in range(len(regions)):
    ax1.plot(w_AI_range, score_matrix[:, v],
             marker='o', linewidth=2.5, markersize=7,
             color=mau_vung[v], label=regions[v])

ax1.axvline(x=0.20, color='gray', linewidth=1.5,
            linestyle='--', alpha=0.7, label='w_AI=0.20 (gốc)')
ax1.set_title('Điểm C* theo trọng số w_AI\n(AI Readiness)',
              fontsize=12, fontweight='bold')
ax1.set_xlabel('Trọng số w_AI')
ax1.set_ylabel('Hệ số gần gũi C*')
ax1.legend(fontsize=8, loc='upper left')
ax1.grid(alpha=0.3)

# Đồ thị 2: Hạng theo w_AI (heatmap)
ax2 = axes[1]
region_short = ['TDMN\nBắc', 'ĐB\nsHồng', 'BTB+\nDHTB',
                'Tây\nNguyên', 'ĐNB', 'ĐB\nsCửu Long']
sns.heatmap(rank_matrix.T,
            annot=True, fmt='d', cmap='RdYlGn_r',
            xticklabels=[f'{w:.2f}' for w in w_AI_range],
            yticklabels=region_short,
            linewidths=0.5, ax=ax2,
            vmin=1, vmax=6,
            annot_kws={'size': 10, 'weight': 'bold'})
ax2.set_title('Hạng xếp theo w_AI\n(1=tốt nhất, 6=kém nhất)',
              fontsize=12, fontweight='bold')
ax2.set_xlabel('Trọng số w_AI')
ax2.set_ylabel('Vùng')

plt.tight_layout()
plt.savefig('bai6_cau3_sensitivity.png', dpi=150, bbox_inches='tight')
plt.show()

# Kết luận ổn định
print("\n📊 NHẬN XÉT ĐỘ NHẠY:")
for v in range(len(regions)):
    hangs = rank_matrix[:, v]
    if hangs.max() - hangs.min() == 0:
        print(f"  {regions[v]:25s}: Hạng {hangs[0]} — "
              f"RẤT ỔN ĐỊNH ✅✅")
    elif hangs.max() - hangs.min() <= 1:
        print(f"  {regions[v]:25s}: Hạng {hangs.min()}–{hangs.max()} — "
              f"ỔN ĐỊNH ✅")
    else:
        print(f"  {regions[v]:25s}: Hạng {hangs.min()}–{hangs.max()} — "
              f"BIẾN ĐỘNG ⚠️")

# ═══════════════════════════════════════════════════════════════
# CÂU 6.4.4 — AHP đơn giản (so sánh cặp)
# ═══════════════════════════════════════════════════════════════
def ahp_weights(pairwise_matrix):
    """
    Tính trọng số AHP từ ma trận so sánh cặp
    Bước 1: Chuẩn hóa cột
    Bước 2: Tính trung bình hàng = trọng số ưu tiên
    Bước 3: Kiểm tra CR (Consistency Ratio)
    """
    A = np.array(pairwise_matrix, dtype=float)
    n = A.shape[0]

    # Bước 1: Chuẩn hóa
    col_sum = A.sum(axis=0)
    A_norm  = A / col_sum

    # Bước 2: Trọng số = trung bình hàng
    w = A_norm.mean(axis=1)

    # Bước 3: CR
    Aw     = A @ w
    lambda_max = (Aw / w).mean()
    CI     = (lambda_max - n) / (n - 1)
    # RI bảng Saaty
    RI_table = {1:0, 2:0, 3:0.58, 4:0.90, 5:1.12,
                6:1.24, 7:1.32, 8:1.41}
    RI = RI_table.get(n, 1.45)
    CR = CI / RI if RI > 0 else 0

    return w, lambda_max, CI, CR


# Ma trận so sánh cặp 8 tiêu chí
# Thang Saaty: 1=bằng nhau, 3=hơi quan trọng hơn,
#              5=quan trọng hơn, 7=rất quan trọng hơn, 9=tuyệt đối
# Ở đây dùng ma trận 8×8 phù hợp với trọng số chuyên gia
pairwise = [
    # GR  FDI  DI  AIR  LĐ  R&D  INT  Gini
    [1,   1,   1,  0.5, 1,   1,   2,   1  ],  # GRDP/người
    [1,   1,   1,  0.5, 1,   1,   2,   1  ],  # FDI
    [1,   1,   1,  0.75,1,   1,   3,   1.5],  # Digital Index
    [2,   2,  1.33,1,  1.33,1.33, 4,   2  ],  # AI Readiness ← cao nhất
    [1,   1,   1,  0.75,1,   1,   3,   1.5],  # LĐ qua ĐT
    [1,   1,   1,  0.75,1,   1,   3,   1.5],  # R&D/GRDP
    [0.5, 0.5,0.33,0.25,0.33,0.33,1,  0.5 ],  # Internet
    [1,   1,  0.67,0.5, 0.67,0.67,2,   1  ],  # Gini
]

w_ahp, lambda_max, CI, CR = ahp_weights(pairwise)

print("=" * 65)
print("CÂU 6.4.4 — TRỌNG SỐ AHP")
print("=" * 65)
print(f"\n  λ_max = {lambda_max:.4f}")
print(f"  CI    = {CI:.4f}")
print(f"  CR    = {CR:.4f}  "
      f"{'✅ CR < 0.10 — Nhất quán!' if CR < 0.1 else '⚠️ CR ≥ 0.10 — Cần điều chỉnh'}")

# Bảng so sánh 3 bộ trọng số
print("\n=== SO SÁNH 3 BỘ TRỌNG SỐ ===")
df_w = pd.DataFrame({
    'Tiêu chí'   : ten_tieu_chi,
    'Chuyên gia' : w_expert.round(4),
    'Entropy'    : w_entropy.round(4),
    'AHP'        : w_ahp.round(4),
})
print(df_w.to_string(index=False))

# TOPSIS với trọng số AHP
res4 = topsis(X, w_ahp, is_benefit)

# So sánh xếp hạng 3 phương pháp
print("\n=== XẾP HẠNG 6 VÙNG THEO 3 PHƯƠNG PHÁP ===")
rank_cg = [np.where(res1['rank']==i)[0][0]+1 for i in range(6)]
rank_en = [np.where(res2['rank']==i)[0][0]+1 for i in range(6)]
rank_ah = [np.where(res4['rank']==i)[0][0]+1 for i in range(6)]

df_rank3 = pd.DataFrame({
    'Vùng'           : regions,
    'C* Chuyên gia'  : res1['C_star'].round(4),
    'Hạng CG'        : rank_cg,
    'C* Entropy'     : res2['C_star'].round(4),
    'Hạng EN'        : rank_en,
    'C* AHP'         : res4['C_star'].round(4),
    'Hạng AHP'       : rank_ah,
}).sort_values('Hạng CG').reset_index(drop=True)
print(df_rank3.to_string(index=False))

# ═══════════════════════════════════════════════════════════════
# BIỂU ĐỒ TỔNG HỢP
# ═══════════════════════════════════════════════════════════════
fig, axes = plt.subplots(2, 2, figsize=(16, 11))
fig.suptitle('Bài 6 — TOPSIS Xếp hạng 6 vùng ưu tiên AI\n'
             'Việt Nam 2024', fontsize=14, fontweight='bold')

mau_vung = ['#E84C4C','#4C9BE8','#4CE882',
            '#E8D84C','#C44CE8','#E87A4C']

# Biểu đồ 1: C* so sánh 3 phương pháp
ax1 = axes[0, 0]
x   = np.arange(len(regions))
w   = 0.25
ax1.bar(x-w,   res1['C_star'], w, label='Chuyên gia',
        color='#4C9BE8', edgecolor='white')
ax1.bar(x,     res2['C_star'], w, label='Entropy',
        color='#E87A4C', edgecolor='white')
ax1.bar(x+w,   res4['C_star'], w, label='AHP',
        color='#4CE882', edgecolor='white')
ax1.set_xticks(x)
ax1.set_xticklabels([r.split()[0] for r in regions],
                    fontsize=9)
ax1.axhline(y=0.5, color='gray', linewidth=1,
            linestyle='--', alpha=0.6)
ax1.set_title('So sánh điểm C*\ntheo 3 bộ trọng số',
              fontsize=11, fontweight='bold')
ax1.set_ylabel('Hệ số gần gũi C*')
ax1.legend(fontsize=9); ax1.grid(axis='y', alpha=0.3)

# Biểu đồ 2: Radar chart vùng top-2
ax2 = axes[0, 1]
top1_idx = res1['rank'][0]
top2_idx = res1['rank'][1]
angles = np.linspace(0, 2*np.pi, len(criteria), endpoint=False)
angles = np.concatenate([angles, [angles[0]]])

# Chuẩn hóa dữ liệu về [0,1] để vẽ radar
X_norm01 = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
for v_idx, (label, color) in enumerate(
    [(regions[top1_idx], '#E84C4C'),
     (regions[top2_idx], '#4C9BE8')]):
    vals = np.concatenate([X_norm01[v_idx if v_idx==top1_idx
                           else top2_idx],
                           [X_norm01[v_idx if v_idx==top1_idx
                            else top2_idx][0]]])
    ax2.plot(angles, vals, 'o-', linewidth=2,
             color=color, label=label)
    ax2.fill(angles, vals, alpha=0.12, color=color)

ax2.set_xticks(angles[:-1])
ax2.set_xticklabels(ten_tieu_chi, size=8)
ax2.set_ylim(0, 1)
ax2.set_title('Radar: Top-2 vùng ưu tiên',
              fontsize=11, fontweight='bold')
ax2.legend(fontsize=8, loc='upper right')

# Biểu đồ 3: Trọng số 3 phương pháp
ax3 = axes[1, 0]
x3  = np.arange(len(ten_tieu_chi))
ax3.plot(x3, w_expert,  'o-', linewidth=2.5, markersize=8,
         color='#4C9BE8', label='Chuyên gia')
ax3.plot(x3, w_entropy, 's-', linewidth=2.5, markersize=8,
         color='#E87A4C', label='Entropy')
ax3.plot(x3, w_ahp,     '^-', linewidth=2.5, markersize=8,
         color='#4CE882', label='AHP')
ax3.set_xticks(x3)
ax3.set_xticklabels(ten_tieu_chi, fontsize=9)
ax3.set_title('So sánh trọng số\n3 phương pháp',
              fontsize=11, fontweight='bold')
ax3.set_ylabel('Trọng số')
ax3.legend(fontsize=9); ax3.grid(alpha=0.3)

# Biểu đồ 4: Heatmap xếp hạng 3 phương pháp
ax4 = axes[1, 1]
rank_heat = np.array([rank_cg, rank_en, rank_ah])
sns.heatmap(rank_heat,
            annot=True, fmt='d', cmap='RdYlGn_r',
            xticklabels=[r.split()[0] for r in regions],
            yticklabels=['Chuyên gia','Entropy','AHP'],
            linewidths=0.8, ax=ax4,
            vmin=1, vmax=6,
            annot_kws={'size': 12, 'weight': 'bold'})
ax4.set_title('Heatmap xếp hạng\n3 phương pháp trọng số',
              fontsize=11, fontweight='bold')
ax4.set_xlabel('Vùng kinh tế')

plt.tight_layout()
plt.savefig('bai6_tong_hop.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ HOÀN THÀNH BÀI 6 — Tất cả 4 câu!")
print(f"  6.4.1 Chuyên gia: #1 = {regions[res1['rank'][0]]}")
print(f"  6.4.2 Entropy   : #1 = {regions[res2['rank'][0]]}")
print(f"  6.4.3 Độ nhạy   : Xem heatmap hạng theo w_AI")
print(f"  6.4.4 AHP       : #1 = {regions[res4['rank'][0]]}, "
      f"CR = {CR:.4f}")