# -*- coding: utf-8 -*-
"""Bai01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ogcLKB8gSjKN9zfRi7oAF09nA4bs7fft
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# ═══════════════════════════════════════════════════════════════
# ĐỌC FILE CSV
# ═══════════════════════════════════════════════════════════════
df = pd.read_csv('/content/drive/MyDrive/vietnam_macro_2020_2025.csv')

# Lấy Y và D trực tiếp từ file CSV
years = df['year'].values
Y     = df['GDP_trillion_VND'].values
D     = df['digital_economy_share_GDP_pct'].values   # cột có sẵn trong CSV

# Các biến KHÔNG có trong CSV → lấy từ bảng số liệu đề bài (Bảng 1.3)
K   = np.array([16500, 17800, 19600, 21300, 23500, 25900])  # vốn tích lũy (nghìn tỷ)
L   = np.array([53.6,  50.5,  51.7,  52.4,  52.9,  53.4 ]) # lao động (triệu người)
AI  = np.array([55.6,  60.2,  65.4,  67.0,  73.8,  80.1 ]) # nghìn DN số
H   = np.array([24.1,  26.1,  26.2,  27.0,  28.4,  29.2 ]) # lao động qua đào tạo (%)

# Hệ số đề xuất (Mục 1.2)
alpha = 0.33   # vốn vật chất K
beta  = 0.42   # lao động L
gamma = 0.10   # số hóa D
delta = 0.08   # AI
theta = 0.07   # nhân lực số H
# Kiểm tra tổng = 1 (lợi suất không đổi theo quy mô)
print(f"Tổng hệ số α+β+γ+δ+θ = {alpha+beta+gamma+delta+theta:.2f}  ✅")

# In bảng dữ liệu đầu vào
df_input = pd.DataFrame({
    'Năm': years, 'Y (GDP)': Y, 'K (vốn)': K,
    'L (LĐ)': L, 'D (KTS%)': D, 'AI (nghìn)': AI, 'H (ĐT%)': H
})
print("\n=== DỮ LIỆU ĐẦU VÀO ===")
print(df_input.to_string(index=False))

# ═══════════════════════════════════════════════════════════════
# CÂU 1.4.1 — Ước lượng TFP A_t bằng cách giải ngược hàm sản xuất
# Công thức: Y = A × K^α × L^β × D^γ × AI^δ × H^θ
# => A_t = Y_t / (K_t^α × L_t^β × D_t^γ × AI_t^δ × H_t^θ)
# ═══════════════════════════════════════════════════════════════

A = Y / (K**alpha * L**beta * D**gamma * AI**delta * H**theta)

# Bảng kết quả
df_tfp = pd.DataFrame({
    'Năm'  : years,
    'GDP thực Y (nghìn tỷ)': Y,
    'TFP A_t': A.round(6)
})
print("=" * 50)
print("CÂU 1.4.1 — TFP TỪNG NĂM")
print("=" * 50)
print(df_tfp.to_string(index=False))

# ── Vẽ đồ thị ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Đồ thị 1: TFP theo năm
ax1 = axes[0]
ax1.plot(years, A, marker='o', color='steelblue',
         linewidth=2.5, markersize=9, zorder=3)
ax1.fill_between(years, A.min()*0.99, A,
                 alpha=0.12, color='steelblue')
for yr, a in zip(years, A):
    ax1.annotate(f'{a:.4f}', xy=(yr, a),
                 xytext=(0, 13), textcoords='offset points',
                 ha='center', fontsize=9, color='navy', fontweight='bold')
ax1.set_title('TFP (A_t) theo năm\nViệt Nam 2020–2025',
              fontsize=12, fontweight='bold')
ax1.set_xlabel('Năm'); ax1.set_ylabel('TFP A_t')
ax1.grid(alpha=0.3); ax1.set_xticks(years)

# Đồ thị 2: Tốc độ tăng TFP
growth_A = np.diff(A) / A[:-1] * 100
ax2 = axes[1]
colors_g = ['#4CE882' if g > 0 else '#E84C4C' for g in growth_A]
bars = ax2.bar(years[1:], growth_A, color=colors_g,
               edgecolor='white', linewidth=1.2)
ax2.axhline(y=0, color='gray', linewidth=1)
for bar, val in zip(bars, growth_A):
    ax2.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.1 if val > 0 else bar.get_height() - 0.4,
             f'{val:.2f}%', ha='center', fontsize=9, fontweight='bold',
             color='darkgreen' if val > 0 else 'darkred')
ax2.set_title('Tốc độ tăng TFP hàng năm (%)',
              fontsize=12, fontweight='bold')
ax2.set_xlabel('Năm'); ax2.set_ylabel('Tăng trưởng TFP (%)')
ax2.grid(axis='y', alpha=0.3); ax2.set_xticks(years[1:])

plt.tight_layout()
plt.savefig('bai1_cau1_TFP.png', dpi=150, bbox_inches='tight')
plt.show()

# ── Bình luận xu hướng ───────────────────────────────────────
A_trend = np.polyfit(range(len(A)), A, 1)
trend_txt = "TĂNG 📈" if A_trend[0] > 0 else "GIẢM 📉"
print(f"\n📊 BÌNH LUẬN XU HƯỚNG TFP:")
print(f"   • TFP năm 2020 = {A[0]:.4f}")
print(f"   • TFP năm 2025 = {A[-1]:.4f}")
print(f"   • Xu hướng tổng thể: {trend_txt}")
print(f"   • TFP tăng → tăng trưởng có chất lượng,")
print(f"     không chỉ dựa vào tích lũy vốn và lao động")

# ═══════════════════════════════════════════════════════════════
# CÂU 1.4.2 — Dự báo GDP với A_t = trung bình, tính MAPE
# ═══════════════════════════════════════════════════════════════

A_mean = A.mean()
print(f"A_mean (TFP trung bình 2020–2025) = {A_mean:.6f}")

# Tính GDP dự báo
Y_pred = A_mean * (K**alpha * L**beta * D**gamma * AI**delta * H**theta)

# Tính MAPE
MAPE = np.mean(np.abs((Y - Y_pred) / Y)) * 100

# Bảng so sánh
df_compare = pd.DataFrame({
    'Năm'           : years,
    'GDP thực Y'    : Y.round(1),
    'GDP dự báo Ŷ'  : Y_pred.round(1),
    'Sai số tuyệt đối': np.abs(Y - Y_pred).round(1),
    'Sai số %'      : (np.abs((Y - Y_pred) / Y) * 100).round(3)
})
print("\n" + "=" * 65)
print("CÂU 1.4.2 — SO SÁNH GDP THỰC TẾ vs DỰ BÁO")
print("=" * 65)
print(df_compare.to_string(index=False))
print(f"\n  ➜ MAPE = {MAPE:.4f}%", end="   →   ")
if   MAPE < 1:  print("Mô hình XUẤT SẮC ✅✅✅")
elif MAPE < 3:  print("Mô hình RẤT TỐT ✅✅")
elif MAPE < 5:  print("Mô hình TỐT ✅")
else:            print("Mô hình CHẤP NHẬN ĐƯỢC ⚠️")

# ── Vẽ đồ thị ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Đồ thị 1: So sánh đường GDP
ax1 = axes[0]
ax1.plot(years, Y,      'o-', color='steelblue', linewidth=2.5,
         markersize=8, label='GDP thực tế')
ax1.plot(years, Y_pred, 's--', color='tomato', linewidth=2.5,
         markersize=8, label=f'GDP dự báo (MAPE={MAPE:.3f}%)')
ax1.fill_between(years, Y, Y_pred, alpha=0.12, color='orange')
ax1.set_title('GDP Thực tế vs Dự báo\n(Cobb-Douglas mở rộng)',
              fontsize=12, fontweight='bold')
ax1.set_xlabel('Năm'); ax1.set_ylabel('GDP (nghìn tỷ VND)')
ax1.legend(fontsize=9); ax1.grid(alpha=0.3); ax1.set_xticks(years)
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(
    lambda x, _: f'{x:,.0f}'))

# Đồ thị 2: Sai số % từng năm
ax2 = axes[1]
err_pct = (np.abs((Y - Y_pred) / Y) * 100)
colors_e = ['#4C9BE8'] * len(years)
bars = ax2.bar(years, err_pct, color=colors_e,
               edgecolor='white', linewidth=1.2)
ax2.axhline(y=MAPE, color='tomato', linewidth=2,
            linestyle='--', label=f'MAPE = {MAPE:.3f}%')
for bar, val in zip(bars, err_pct):
    ax2.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.005,
             f'{val:.3f}%', ha='center', fontsize=9.5, fontweight='bold')
ax2.set_title('Sai số dự báo từng năm (%)',
              fontsize=12, fontweight='bold')
ax2.set_xlabel('Năm'); ax2.set_ylabel('|Sai số| (%)')
ax2.legend(); ax2.grid(axis='y', alpha=0.3); ax2.set_xticks(years)

plt.tight_layout()
plt.savefig('bai1_cau2_MAPE.png', dpi=150, bbox_inches='tight')
plt.show()

# ═══════════════════════════════════════════════════════════════
# CÂU 1.4.3 — Phân rã tăng trưởng GDP 2020–2025
# Công thức: Δln(Y) = ΔlnA + α·ΔlnK + β·ΔlnL
#                   + γ·ΔlnD + δ·ΔlnAI + θ·ΔlnH
# ═══════════════════════════════════════════════════════════════

# Tính đóng góp từng yếu tố (Δln = tăng trưởng logarit)
contrib = {
    'Vốn K'      : alpha * np.diff(np.log(K)),
    'Lao động L' : beta  * np.diff(np.log(L)),
    'Số hóa D'   : gamma * np.diff(np.log(D)),
    'AI'         : delta * np.diff(np.log(AI)),
    'Nhân lực H' : theta * np.diff(np.log(H)),
    'TFP (A)'    : np.diff(np.log(A)),
}
g_Y = np.diff(np.log(Y))   # tổng tăng trưởng GDP log

# Bảng chi tiết từng năm
years_diff = [f'{years[i]}→{years[i+1]}' for i in range(len(years)-1)]
df_detail = pd.DataFrame({k: (v*100).round(3) for k, v in contrib.items()},
                          index=years_diff)
df_detail['Tổng Δln(Y)'] = (g_Y * 100).round(3)
print("=" * 80)
print("CÂU 1.4.3 — PHÂN RÃ TĂNG TRƯỞNG GDP TỪNG NĂM (%/năm, log scale)")
print("=" * 80)
print(df_detail.to_string())

# Bảng bình quân toàn giai đoạn
means = {k: v.mean()*100 for k, v in contrib.items()}
total_mean = g_Y.mean() * 100
tytrongpct = {k: v/total_mean*100 for k, v in means.items()}

df_summary = pd.DataFrame({
    'Yếu tố'              : list(means.keys()),
    'Đóng góp BQ (%/năm)' : [round(v, 4) for v in means.values()],
    'Tỷ trọng (%)'        : [round(v, 2) for v in tytrongpct.values()]
})
print(f"\n{'='*55}")
print(f"BẢNG TỔNG HỢP BÌNH QUÂN TOÀN GIAI ĐOẠN 2020–2025")
print(f"Tổng tăng trưởng GDP BQ = {total_mean:.4f}%/năm")
print(f"{'='*55}")
print(df_summary.to_string(index=False))

# ── Vẽ biểu đồ cột ───────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

colors_bar = ['#4C9BE8','#E87A4C','#4CE882',
               '#E8D84C','#C44CE8','#E84C4C']

# Biểu đồ 1: Đóng góp bình quân
ax1 = axes[0]
bars = ax1.bar(list(means.keys()),
               list(means.values()),
               color=colors_bar, edgecolor='white', linewidth=1.5)
for bar, val in zip(bars, means.values()):
    ypos = bar.get_height() + 0.001 if val >= 0 else bar.get_height() - 0.005
    ax1.text(bar.get_x() + bar.get_width()/2, ypos,
             f'{val:.4f}%', ha='center', fontsize=9.5,
             fontweight='bold', color='#2C2C2A')
ax1.axhline(y=0, color='gray', linewidth=0.8)
ax1.set_title('Đóng góp bình quân vào tăng trưởng GDP\n2020–2025 (%/năm)',
              fontsize=11, fontweight='bold')
ax1.set_ylabel('Đóng góp (%/năm)')
ax1.grid(axis='y', alpha=0.3)
plt.setp(ax1.xaxis.get_majorticklabels(), rotation=15, ha='right')

# Biểu đồ 2: Tỷ trọng (pie)
ax2 = axes[1]
vals_pos = [max(v, 0) for v in means.values()]  # chỉ lấy dương cho pie
wedges, texts, autotexts = ax2.pie(
    vals_pos,
    labels=list(means.keys()),
    autopct='%1.1f%%',
    colors=colors_bar,
    startangle=90,
    wedgeprops={'edgecolor': 'white', 'linewidth': 2},
    pctdistance=0.75
)
for autotext in autotexts:
    autotext.set_fontsize(9)
ax2.set_title('Tỷ trọng đóng góp vào tăng trưởng GDP\n2020–2025',
              fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig('bai1_cau3_GrowthAccounting.png', dpi=150, bbox_inches='tight')
plt.show()

# ═══════════════════════════════════════════════════════════════
# CÂU 1.4.4 — Kịch bản dự báo GDP Việt Nam đến 2030
# Giả định: K, L tăng 6%/năm | TFP tăng 1.2%/năm
#           D → 30% | AI → 100 nghìn DN | H → 35%
# ═══════════════════════════════════════════════════════════════

n_years = 6   # 2025 → 2030 (5 bước nhưng 6 điểm: 2025,26,27,28,29,30)
future_years = np.arange(2025, 2031)

# Khởi điểm = giá trị năm 2025
K_f   = [K[-1]]
L_f   = [L[-1]]
A_f   = [A[-1]]
D_f   = np.linspace(D[-1],  30.0,  n_years)   # 19.5% → 30%
AI_f  = np.linspace(AI[-1], 100.0, n_years)   # 80.1  → 100 nghìn DN
H_f   = np.linspace(H[-1],  35.0,  n_years)   # 29.2% → 35%

# Tính K, L, A cho 2026–2030 (tăng theo tỷ lệ cố định)
for _ in range(n_years - 1):
    K_f.append(K_f[-1] * 1.06)
    L_f.append(L_f[-1] * 1.06)
    A_f.append(A_f[-1] * 1.012)

K_f = np.array(K_f)
L_f = np.array(L_f)
A_f = np.array(A_f)

# Tính GDP dự báo
Y_f = A_f * (K_f**alpha * L_f**beta * D_f**gamma * AI_f**delta * H_f**theta)

# Bảng kết quả
toc_do = [0] + [(Y_f[i]/Y_f[i-1]-1)*100 for i in range(1, n_years)]
df_fc = pd.DataFrame({
    'Năm'                   : future_years,
    'K (nghìn tỷ)'          : K_f.round(1),
    'L (triệu)'             : L_f.round(2),
    'D (%)'                 : D_f.round(1),
    'AI (nghìn DN)'         : AI_f.round(1),
    'H (%)'                 : H_f.round(1),
    'TFP A'                 : A_f.round(5),
    'GDP (nghìn tỷ VND)'    : Y_f.round(1),
    'Tăng trưởng (%)'       : [round(t, 2) for t in toc_do]
})
print("=" * 90)
print("CÂU 1.4.4 — DỰ BÁO GDP VIỆT NAM 2025–2030")
print("=" * 90)
print(df_fc.to_string(index=False))

# Quy đổi sang USD
Y_2030_USD = Y_f[-1] * 1000 / 24500
print(f"\n  ➜ GDP dự báo năm 2030 = {Y_f[-1]:,.1f} nghìn tỷ VND")
print(f"     ≈ {Y_2030_USD:,.0f} tỷ USD (tỷ giá 24,500 VND/USD)")
target = 1000
print(f"     Mục tiêu 1.000 tỷ USD: {'✅ ĐẠT' if Y_2030_USD >= target else '❌ CHƯA ĐẠT'}")

# ── Vẽ đồ thị ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Đồ thị 1: Đường GDP thực tế + dự báo
ax1 = axes[0]
ax1.plot(years, Y, 'o-', color='steelblue',
         linewidth=2.5, markersize=9, label='Thực tế 2020–2025', zorder=3)
ax1.plot(future_years, Y_f, 's--', color='tomato',
         linewidth=2.5, markersize=9, label='Dự báo 2025–2030', zorder=3)
ax1.axvspan(2025, 2030, alpha=0.06, color='tomato')
ax1.axvline(x=2025, color='gray', linewidth=1.5, linestyle=':')

# Ghi giá trị năm 2025 và 2030
for yr, y, col in [(2025, Y_f[0], 'steelblue'), (2030, Y_f[-1], 'tomato')]:
    ax1.annotate(f'{y:,.0f}\nnghìn tỷ',
                 xy=(yr, y), xytext=(20, 15),
                 textcoords='offset points',
                 arrowprops=dict(arrowstyle='->', color=col, lw=1.5),
                 fontsize=9, color=col, fontweight='bold')

ax1.set_title('Dự báo GDP Việt Nam đến 2030\n(Kịch bản chuyển đổi số tích cực)',
              fontsize=12, fontweight='bold')
ax1.set_xlabel('Năm')
ax1.set_ylabel('GDP (nghìn tỷ VND)')
ax1.legend(fontsize=10)
ax1.grid(alpha=0.3)
ax1.set_xticks(list(years) + list(future_years[1:]))
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(
    lambda x, _: f'{x:,.0f}'))

# Đồ thị 2: Tốc độ tăng trưởng GDP dự báo
ax2 = axes[1]
growth_hist = df['GDP_growth_pct'].values
growth_all  = np.concatenate([growth_hist, toc_do[1:]])
yrs_all     = np.concatenate([years, future_years[1:]])
colors_all  = ['steelblue']*len(years) + ['tomato']*5

bars = ax2.bar(yrs_all, growth_all,
               color=colors_all, edgecolor='white', linewidth=1.2, width=0.7)
ax2.axvline(x=2025.5, color='gray', linewidth=1.5, linestyle=':')
ax2.axhline(y=growth_all.mean(), color='purple', linewidth=1.5,
            linestyle='--', label=f'BQ = {growth_all.mean():.1f}%')

for bar, val in zip(bars, growth_all):
    ax2.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.1,
             f'{val:.1f}%', ha='center', fontsize=8.5, fontweight='bold')

ax2.text(2022.5, max(growth_all)*0.92, 'Thực tế',
         ha='center', color='steelblue', fontsize=10, fontweight='bold')
ax2.text(2027.5, max(growth_all)*0.92, 'Dự báo',
         ha='center', color='tomato', fontsize=10, fontweight='bold')
ax2.set_title('Tốc độ tăng trưởng GDP\n2020–2030 (%)',
              fontsize=12, fontweight='bold')
ax2.set_xlabel('Năm')
ax2.set_ylabel('Tăng trưởng (%)')
ax2.legend(fontsize=10)
ax2.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('bai1_cau4_DuBao2030.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ HOÀN THÀNH BÀI 1 — Tất cả 4 câu!")