# -*- coding: utf-8 -*-
"""Bai10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aivnc0AtFyPSRV73fog0-rNKQGfbD9KE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pyomo.environ as pyo

# ═══════════════════════════════════════════════════════════════
# DỮ LIỆU BÀI 10 — từ Bảng 10.2 và 10.4 đề bài
# ═══════════════════════════════════════════════════════════════

# Hạng mục đầu tư
J = ['I', 'D', 'AI', 'H']
ten_hang_muc = {
    'I' : 'Hạ tầng số',
    'D' : 'Chuyển đổi số',
    'AI': 'Trí tuệ nhân tạo',
    'H' : 'Nhân lực số'
}

# Kịch bản bất định
S = ['s1', 's2', 's3', 's4']
ten_kich_ban = {
    's1': 'Lạc quan',
    's2': 'Cơ sở',
    's3': 'Bi quan',
    's4': 'Khủng hoảng'
}

# Xác suất từng kịch bản — Bảng 10.2
p = {'s1': 0.30, 's2': 0.45, 's3': 0.20, 's4': 0.05}

# Hệ số β cơ bản giai đoạn 1
beta = {'I': 1.00, 'D': 1.10, 'AI': 1.25, 'H': 0.95}

# Hệ số β theo kịch bản giai đoạn 2 — Bảng 10.4
beta_s = {
    ('s1','I'): 1.25, ('s1','D'): 1.35, ('s1','AI'): 1.55, ('s1','H'): 1.05,
    ('s2','I'): 1.00, ('s2','D'): 1.10, ('s2','AI'): 1.25, ('s2','H'): 0.95,
    ('s3','I'): 0.75, ('s3','D'): 0.85, ('s3','AI'): 0.90, ('s3','H'): 1.00,
    ('s4','I'): 0.40, ('s4','D'): 0.50, ('s4','AI'): 0.55, ('s4','H'): 1.10,
}

# Ngân sách
NS_1   = 65000   # giai đoạn 1
NS_2   = 15000   # giai đoạn 2
NS_TOT = 80000   # tổng

# ── In kiểm tra ──────────────────────────────────────────────
print("=" * 55)
print("DỮ LIỆU BÀI 10 — Quy hoạch ngẫu nhiên 2 giai đoạn")
print("=" * 55)

print(f"\nTổng xác suất = {sum(p.values()):.2f} ✅")

print("\n=== BẢNG KỊCH BẢN (Bảng 10.2) ===")
df_kb = pd.DataFrame({
    'Kịch bản' : [ten_kich_ban[s] for s in S],
    'Xác suất' : [p[s]            for s in S],
    'β_I'      : [beta_s[s,'I']   for s in S],
    'β_D'      : [beta_s[s,'D']   for s in S],
    'β_AI'     : [beta_s[s,'AI']  for s in S],
    'β_H'      : [beta_s[s,'H']   for s in S],
}, index=S)
print(df_kb.to_string())

print("\n=== HỆ SỐ β CƠ BẢN (Giai đoạn 1) ===")
for j in J:
    print(f"  β_{j:2s} = {beta[j]:.2f}  ({ten_hang_muc[j]})")

print(f"\n=== NGÂN SÁCH ===")
print(f"  Giai đoạn 1 (here-and-now) : {NS_1:,} tỷ VND")
print(f"  Giai đoạn 2 (recourse)     : {NS_2:,} tỷ VND")
print(f"  Tổng 5 năm                 : {NS_TOT:,} tỷ VND")
print(f"\n✅ Cell 1 hoàn thành — sẵn sàng chạy Cell 2!")

# ═══════════════════════════════════════════════════════════════
# CÂU 10.5.1 — Pyomo với Set, Param, Var rõ ràng
# Mô hình hóa first-stage VÀ second-stage tường minh
# ═══════════════════════════════════════════════════════════════

m = pyo.ConcreteModel(name="Stochastic_SP_Bai10")

# ── SETS ─────────────────────────────────────────────────────
m.J = pyo.Set(initialize=J,
              doc="Tập hạng mục đầu tư: I, D, AI, H")
m.S = pyo.Set(initialize=S,
              doc="Tập kịch bản: s1, s2, s3, s4")

# ── PARAMS ───────────────────────────────────────────────────
m.p = pyo.Param(
    m.S, initialize=p,
    doc="Xác suất từng kịch bản")

m.beta = pyo.Param(
    m.J, initialize=beta,
    doc="Hệ số GDP giai đoạn 1 (first-stage)")

m.beta_s = pyo.Param(
    m.S, m.J, initialize=beta_s,
    doc="Hệ số GDP giai đoạn 2 theo kịch bản")

m.NS1 = pyo.Param(
    initialize=NS_1,
    doc="Ngân sách giai đoạn 1 = 65.000 tỷ")

m.NS2 = pyo.Param(
    initialize=NS_2,
    doc="Ngân sách giai đoạn 2 = 15.000 tỷ")

# ── VARIABLES ────────────────────────────────────────────────
m.x = pyo.Var(
    m.J,
    within=pyo.NonNegativeReals,
    doc="FIRST-STAGE: x[j] = đầu tư hạng mục j giai đoạn 1")

m.y = pyo.Var(
    m.S, m.J,
    within=pyo.NonNegativeReals,
    doc="SECOND-STAGE: y[s,j] = đầu tư bổ sung kịch bản s")

# ── HÀM MỤC TIÊU ─────────────────────────────────────────────
# max Σβⱼ·xⱼ + Σₛ pₛ·Σⱼ βⱼˢ·yⱼˢ
def obj_rule(m):
    first_stage = sum(m.beta[j] * m.x[j] for j in m.J)
    second_stage = sum(
        m.p[s] * sum(m.beta_s[s,j] * m.y[s,j] for j in m.J)
        for s in m.S
    )
    return first_stage + second_stage

m.obj = pyo.Objective(
    rule=obj_rule,
    sense=pyo.maximize,
    doc="Tối đa hóa GDP kỳ vọng 2 giai đoạn")

# ── RÀNG BUỘC ────────────────────────────────────────────────
# R1: Ngân sách giai đoạn 1
m.R1_budget1 = pyo.Constraint(
    expr=sum(m.x[j] for j in m.J) <= m.NS1,
    doc="NS giai đoạn 1 ≤ 65.000 tỷ")

# R2: Ngân sách giai đoạn 2 mỗi kịch bản
def R2_budget2(m, s):
    return sum(m.y[s,j] for j in m.J) <= m.NS2
m.R2_budget2 = pyo.Constraint(
    m.S, rule=R2_budget2,
    doc="NS giai đoạn 2 ≤ 15.000 tỷ mỗi kịch bản")

# R3: AI cần nhân lực — yᴬᴵˢ ≤ 0.5·x_H
def R3_ai_labor(m, s):
    return m.y[s,'AI'] <= 0.5 * m.x['H']
m.R3_ai_labor = pyo.Constraint(
    m.S, rule=R3_ai_labor,
    doc="Đầu tư AI stage 2 ≤ 50% nhân lực stage 1")

# ── GIẢI ─────────────────────────────────────────────────────
solver = pyo.SolverFactory('glpk')
result = solver.solve(m, tee=False)
status = str(result.solver.termination_condition)

print("=" * 60)
print("CÂU 10.5.1 — KẾT QUẢ STOCHASTIC PROGRAMMING")
print("=" * 60)
print(f"\n  Solver : GLPK")
print(f"  Trạng thái: {status}")
print(f"  Z* (SP) = {pyo.value(m.obj):,.4f}")

# Lưu kết quả SP
x_SP  = {j: pyo.value(m.x[j]) for j in J}
y_SP  = {(s,j): pyo.value(m.y[s,j]) for s in S for j in J}
Z_SP  = pyo.value(m.obj)

# Báo cáo FIRST-STAGE
print("\n=== QUYẾT ĐỊNH FIRST-STAGE TỐI ƯU ===")
print(f"  {'Hạng mục':20s} | {'x* (tỷ VND)':>12} | {'Tỷ trọng':>10}")
print("  " + "─" * 48)
tong_x = sum(x_SP.values())
for j in J:
    print(f"  {ten_hang_muc[j]:20s} | "
          f"{x_SP[j]:>12.2f} | "
          f"{x_SP[j]/tong_x*100:>9.1f}%")
print("  " + "─" * 48)
print(f"  {'Tổng':20s} | {tong_x:>12.2f} | {'100.0%':>10}")

# Báo cáo SECOND-STAGE
print("\n=== QUYẾT ĐỊNH SECOND-STAGE THEO KỊCH BẢN ===")
print(f"  {'Kịch bản':12s} | "
      + " | ".join(f"{ten_hang_muc[j]:>12s}" for j in J)
      + f" | {'Tổng':>8}")
print("  " + "─" * 72)
for s in S:
    tong_y = sum(y_SP[s,j] for j in J)
    print(f"  {ten_kich_ban[s]:12s} | "
          + " | ".join(f"{y_SP[s,j]:>12.2f}" for j in J)
          + f" | {tong_y:>8.2f}")

# Kiểm tra ràng buộc
print("\n=== KIỂM TRA RÀNG BUỘC ===")
print(f"  R1 NS giai đoạn 1: {tong_x:,.2f} ≤ {NS_1:,} "
      f"{'✅' if tong_x <= NS_1+0.01 else '❌'}")
for s in S:
    tong_y = sum(y_SP[s,j] for j in J)
    ok_ns  = tong_y <= NS_2 + 0.01
    ok_ai  = y_SP[s,'AI'] <= 0.5*x_SP['H'] + 0.01
    print(f"  R2 NS s={s}: {tong_y:,.2f} ≤ {NS_2:,} "
          f"{'✅' if ok_ns else '❌'}  |  "
          f"R3 AI≤0.5H: {y_SP[s,'AI']:,.2f} ≤ "
          f"{0.5*x_SP['H']:,.2f} "
          f"{'✅' if ok_ai else '❌'}")

# ═══════════════════════════════════════════════════════════════
# CÂU 10.5.2 — Giải xác định từng kịch bản riêng rẽ
# ═══════════════════════════════════════════════════════════════

def giai_deterministic(kich_ban):
    """
    Giải bài toán xác định với 1 kịch bản cố định.
    Biết trước kịch bản → dùng β_s trực tiếp.
    """
    m_det = pyo.ConcreteModel()
    m_det.J = pyo.Set(initialize=J)

    # Params
    m_det.beta   = pyo.Param(m_det.J, initialize=beta)
    m_det.beta_s = pyo.Param(
        m_det.J,
        initialize={j: beta_s[kich_ban, j] for j in J})
    m_det.NS1 = pyo.Param(initialize=NS_1)
    m_det.NS2 = pyo.Param(initialize=NS_2)

    # Vars
    m_det.x = pyo.Var(m_det.J, within=pyo.NonNegativeReals)
    m_det.y = pyo.Var(m_det.J, within=pyo.NonNegativeReals)

    # Objective
    m_det.obj = pyo.Objective(
        expr=sum(m_det.beta[j]*m_det.x[j] for j in J)
           + sum(m_det.beta_s[j]*m_det.y[j] for j in J),
        sense=pyo.maximize)

    # Constraints
    m_det.R1 = pyo.Constraint(
        expr=sum(m_det.x[j] for j in J) <= m_det.NS1)
    m_det.R2 = pyo.Constraint(
        expr=sum(m_det.y[j] for j in J) <= m_det.NS2)
    m_det.R3 = pyo.Constraint(
        expr=m_det.y['AI'] <= 0.5 * m_det.x['H'])

    solver = pyo.SolverFactory('glpk')
    solver.solve(m_det, tee=False)

    return {
        'x'  : {j: pyo.value(m_det.x[j]) for j in J},
        'y'  : {j: pyo.value(m_det.y[j]) for j in J},
        'Z'  : pyo.value(m_det.obj)
    }

# ── Giải từng kịch bản riêng rẽ ─────────────────────────────
print("=" * 60)
print("CÂU 10.5.2 — GIẢI XÁC ĐỊNH TỪNG KỊCH BẢN")
print("=" * 60)

res_det = {}
for s in S:
    res_det[s] = giai_deterministic(s)

# In bảng first-stage từng kịch bản
print("\n=== QUYẾT ĐỊNH FIRST-STAGE THEO TỪNG KỊCH BẢN ===")
print(f"  {'':12s} | "
      + " | ".join(f"{ten_hang_muc[j]:>12s}" for j in J)
      + f" | {'Z*':>10}")
print("  " + "─" * 72)
for s in S:
    print(f"  {ten_kich_ban[s]:12s} | "
          + " | ".join(
              f"{res_det[s]['x'][j]:>12.2f}" for j in J)
          + f" | {res_det[s]['Z']:>10.4f}")

# ── Tính EV (Expected Value solution) ───────────────────────
# EV: dùng β trung bình có trọng số xác suất
print("\n=== TÍNH EV (Expected Value) ===")
beta_ev = {
    j: sum(p[s] * beta_s[s,j] for s in S)
    for j in J
}
print("  β kỳ vọng (β̄ = Σₛ pₛ·βˢ):")
for j in J:
    print(f"    β̄_{j} = {beta_ev[j]:.4f}")

m_ev = pyo.ConcreteModel()
m_ev.J    = pyo.Set(initialize=J)
m_ev.beta  = pyo.Param(m_ev.J, initialize=beta)
m_ev.beta_ev = pyo.Param(m_ev.J, initialize=beta_ev)
m_ev.x    = pyo.Var(m_ev.J, within=pyo.NonNegativeReals)
m_ev.y    = pyo.Var(m_ev.J, within=pyo.NonNegativeReals)

m_ev.obj  = pyo.Objective(
    expr=sum(m_ev.beta[j]*m_ev.x[j] for j in J)
       + sum(m_ev.beta_ev[j]*m_ev.y[j] for j in J),
    sense=pyo.maximize)
m_ev.R1   = pyo.Constraint(
    expr=sum(m_ev.x[j] for j in J) <= NS_1)
m_ev.R2   = pyo.Constraint(
    expr=sum(m_ev.y[j] for j in J) <= NS_2)
m_ev.R3   = pyo.Constraint(
    expr=m_ev.y['AI'] <= 0.5 * m_ev.x['H'])

pyo.SolverFactory('glpk').solve(m_ev, tee=False)

x_EV = {j: pyo.value(m_ev.x[j]) for j in J}
y_EV = {j: pyo.value(m_ev.y[j]) for j in J}
Z_EV = pyo.value(m_ev.obj)

# ── So sánh EV vs SP ─────────────────────────────────────────
print("\n=== SO SÁNH FIRST-STAGE: EV vs SP ===")
print(f"  {'Hạng mục':20s} | {'x_EV (tỷ)':>10} | "
      f"{'x_SP (tỷ)':>10} | {'Δ (SP-EV)':>10}")
print("  " + "─" * 58)
for j in J:
    delta = x_SP[j] - x_EV[j]
    sign  = '+' if delta >= 0 else ''
    print(f"  {ten_hang_muc[j]:20s} | "
          f"{x_EV[j]:>10.2f} | "
          f"{x_SP[j]:>10.2f} | "
          f"{sign}{delta:>9.2f}")
print("  " + "─" * 58)
print(f"  {'Tổng':20s} | "
      f"{sum(x_EV.values()):>10.2f} | "
      f"{sum(x_SP.values()):>10.2f} |")

print(f"\n  Z_EV (kịch bản TB) = {Z_EV:>12,.4f}")
print(f"  Z_SP (Stochastic)  = {Z_SP:>12,.4f}")
print(f"\n  📌 Nhận xét:")
print(f"  SP phân bổ H = {x_SP['H']:,.2f} tỷ "
      f"({'nhiều hơn' if x_SP['H']>x_EV['H'] else 'ít hơn'} EV)")
print(f"  Vì SP tính đến kịch bản xấu (s4) cần H làm bảo hiểm")

# ═══════════════════════════════════════════════════════════════
# CÂU 10.5.3 — VSS và EVPI
#
# Định nghĩa chuẩn:
#   EEV = kỳ vọng khi dùng nghiệm x_EV vào thực tế
#   VSS = Z_SP - EEV
#   WS  = Σₛ pₛ × Z*_s (biết trước kịch bản)
#   EVPI = WS - Z_SP
# ═══════════════════════════════════════════════════════════════

print("=" * 60)
print("CÂU 10.5.3 — VSS VÀ EVPI")
print("=" * 60)

# ── Bước 1: Tính EEV ─────────────────────────────────────────
# Cố định x = x_EV, giải second-stage tối ưu từng kịch bản
def tinh_second_stage(x_fixed, s):
    """
    Giải bài toán second-stage với x cố định,
    kịch bản s đã xảy ra.
    """
    m2 = pyo.ConcreteModel()
    m2.J = pyo.Set(initialize=J)
    m2.y = pyo.Var(m2.J, within=pyo.NonNegativeReals)
    m2.obj = pyo.Objective(
        expr=sum(beta_s[s,j] * m2.y[j] for j in J),
        sense=pyo.maximize)
    m2.R2 = pyo.Constraint(
        expr=sum(m2.y[j] for j in J) <= NS_2)
    m2.R3 = pyo.Constraint(
        expr=m2.y['AI'] <= 0.5 * x_fixed['H'])
    pyo.SolverFactory('glpk').solve(m2, tee=False)
    return {j: pyo.value(m2.y[j]) for j in J}

# Tính EEV = Σₛ pₛ × [Σⱼ βⱼ·x_EV + Σⱼ βⱼˢ·y*ˢ(x_EV)]
first_EV  = sum(beta[j] * x_EV[j] for j in J)
EEV_parts = {}
for s in S:
    y2 = tinh_second_stage(x_EV, s)
    second_s = sum(beta_s[s,j] * y2[j] for j in J)
    EEV_parts[s] = first_EV + second_s

EEV = sum(p[s] * EEV_parts[s] for s in S)

# ── Bước 2: Tính WS ──────────────────────────────────────────
# WS = Σₛ pₛ × Z*_s (mỗi kịch bản giải tối ưu độc lập)
WS_parts = {s: res_det[s]['Z'] for s in S}
WS = sum(p[s] * WS_parts[s] for s in S)

# ── Bước 3: VSS và EVPI ──────────────────────────────────────
VSS  = Z_SP - EEV
EVPI = WS - Z_SP

# In chi tiết
print("\n=== CHI TIẾT TÍNH EEV ===")
print(f"  First-stage value (x_EV) = {first_EV:,.4f}")
print(f"\n  {'Kịch bản':12s} | {'pₛ':>6} | "
      f"{'Z(x_EV,s)':>12} | {'pₛ × Z':>12}")
print("  " + "─" * 48)
for s in S:
    print(f"  {ten_kich_ban[s]:12s} | {p[s]:>6.2f} | "
          f"{EEV_parts[s]:>12.4f} | "
          f"{p[s]*EEV_parts[s]:>12.4f}")
print("  " + "─" * 48)
print(f"  {'EEV':12s} | {'':>6} | {'':>12} | "
      f"{EEV:>12.4f}")

print("\n=== CHI TIẾT TÍNH WS ===")
print(f"  {'Kịch bản':12s} | {'pₛ':>6} | "
      f"{'Z*_s':>12} | {'pₛ × Z*_s':>12}")
print("  " + "─" * 48)
for s in S:
    print(f"  {ten_kich_ban[s]:12s} | {p[s]:>6.2f} | "
          f"{WS_parts[s]:>12.4f} | "
          f"{p[s]*WS_parts[s]:>12.4f}")
print("  " + "─" * 48)
print(f"  {'WS':12s} | {'':>6} | {'':>12} | "
      f"{WS:>12.4f}")

print(f"\n{'═'*60}")
print(f"  EEV  = {EEV:>15,.4f}  (dùng nghiệm EV vào thực tế)")
print(f"  Z_SP = {Z_SP:>15,.4f}  (nghiệm Stochastic tối ưu)")
print(f"  WS   = {WS:>15,.4f}  (biết trước kịch bản)")
print(f"{'─'*60}")
print(f"  VSS  = Z_SP - EEV = {VSS:>10,.4f}")
print(f"  EVPI = WS - Z_SP  = {EVPI:>10,.4f}")
print(f"{'═'*60}")

print(f"""
📌 Ý NGHĨA:

   VSS = {VSS:,.4f}
   → Lợi ích của tư duy xác suất khi ra quyết định
   → SP tốt hơn EV {VSS:,.4f} đơn vị GDP kỳ vọng
   → {'VSS > 0 ✅ → Đáng dùng mô hình SP!' if VSS > 0
      else 'VSS = 0 → SP và EV cho kết quả như nhau'}

   EVPI = {EVPI:,.4f}
   → Giá trị của thông tin hoàn hảo (biết trước tương lai)
   → Tối đa nên chi {EVPI:,.4f} để có thông tin dự báo tốt hơn
   → {'EVPI > VSS ✅ → Thông tin hoàn hảo quý hơn mô hình SP'
      if EVPI > VSS else 'EVPI ≤ VSS'}

   Bất đẳng thức chuẩn: EEV ≤ Z_SP ≤ WS
   {EEV:.4f} ≤ {Z_SP:.4f} ≤ {WS:.4f}
   {'✅ Thỏa mãn!' if EEV <= Z_SP <= WS + 0.001
    else '❌ Kiểm tra lại!'}
""")

# ═══════════════════════════════════════════════════════════════
# CÂU 10.5.4 — ROBUST OPTIMIZATION (Minimax Regret)
# Mục tiêu: minimize max_s [Z*_s - Z(x, y_s, s)]
# ═══════════════════════════════════════════════════════════════

print("=" * 60)
print("CÂU 10.5.4 — ROBUST OPTIMIZATION (Minimax Regret)")
print("=" * 60)

m_rob = pyo.ConcreteModel(name="Robust_Minimax")

# Sets & Params
m_rob.J      = pyo.Set(initialize=J)
m_rob.S      = pyo.Set(initialize=S)
m_rob.beta   = pyo.Param(m_rob.J, initialize=beta)
m_rob.beta_s = pyo.Param(m_rob.S, m_rob.J, initialize=beta_s)
m_rob.NS1    = pyo.Param(initialize=NS_1)
m_rob.NS2    = pyo.Param(initialize=NS_2)

# Variables
m_rob.x      = pyo.Var(m_rob.J,
                        within=pyo.NonNegativeReals,
                        doc="First-stage robust")
m_rob.y      = pyo.Var(m_rob.S, m_rob.J,
                        within=pyo.NonNegativeReals,
                        doc="Second-stage robust")
m_rob.theta  = pyo.Var(within=pyo.NonNegativeReals,
                        doc="Max regret (biến phụ)")

# Minimize max regret
m_rob.obj = pyo.Objective(
    expr=m_rob.theta,
    sense=pyo.minimize,
    doc="Minimize worst-case regret")

# Ràng buộc ngân sách
m_rob.R1 = pyo.Constraint(
    expr=sum(m_rob.x[j] for j in J) <= m_rob.NS1)

def R2_rule(m, s):
    return sum(m.y[s,j] for j in J) <= m.NS2
m_rob.R2 = pyo.Constraint(m_rob.S, rule=R2_rule)

def R3_rule(m, s):
    return m.y[s,'AI'] <= 0.5 * m.x['H']
m_rob.R3 = pyo.Constraint(m_rob.S, rule=R3_rule)

# Ràng buộc regret:
# θ ≥ Z*_s - [Σβⱼxⱼ + Σβⱼˢyⱼˢ]  ∀s
def regret_rule(m, s):
    Z_xs = (sum(m.beta[j]   * m.x[j]    for j in J)
          + sum(m.beta_s[s,j] * m.y[s,j] for j in J))
    return m.theta >= WS_parts[s] - Z_xs
m_rob.regret_con = pyo.Constraint(
    m_rob.S, rule=regret_rule,
    doc="Regret ≥ Z*_s - Z(x,y,s) cho mọi s")

# Giải
pyo.SolverFactory('glpk').solve(m_rob, tee=False)

x_rob     = {j: pyo.value(m_rob.x[j]) for j in J}
y_rob     = {(s,j): pyo.value(m_rob.y[s,j])
             for s in S for j in J}
theta_val = pyo.value(m_rob.theta)

# Tính Z_rob kỳ vọng để so sánh
Z_rob = (sum(beta[j]*x_rob[j] for j in J)
       + sum(p[s]*sum(beta_s[s,j]*y_rob[s,j]
                      for j in J)
             for s in S))

# ── Bảng so sánh 3 phương pháp ──────────────────────────────
print("\n=== SO SÁNH FIRST-STAGE: EV vs SP vs ROBUST ===")
print(f"  {'Hạng mục':20s} | {'x_EV':>8} | "
      f"{'x_SP':>8} | {'x_Rob':>8} | "
      f"{'SP-EV':>8} | {'Rob-SP':>8}")
print("  " + "─" * 72)
for j in J:
    d1 = x_SP[j]  - x_EV[j]
    d2 = x_rob[j] - x_SP[j]
    print(f"  {ten_hang_muc[j]:20s} | "
          f"{x_EV[j]:>8.1f} | "
          f"{x_SP[j]:>8.1f} | "
          f"{x_rob[j]:>8.1f} | "
          f"{d1:>+8.1f} | "
          f"{d2:>+8.1f}")
print("  " + "─" * 72)
print(f"  {'Tổng':20s} | "
      f"{sum(x_EV.values()):>8.1f} | "
      f"{sum(x_SP.values()):>8.1f} | "
      f"{sum(x_rob.values()):>8.1f} |")

# Regret từng kịch bản
print("\n=== REGRET TỪNG KỊCH BẢN ===")
print(f"  {'Kịch bản':12s} | {'Z*_s':>10} | "
      f"{'Z(Rob,s)':>10} | {'Regret':>10} | {'pₛ':>6}")
print("  " + "─" * 55)
for s in S:
    Z_robs = (sum(beta[j]*x_rob[j] for j in J)
            + sum(beta_s[s,j]*y_rob[s,j] for j in J))
    regret_s = WS_parts[s] - Z_robs
    print(f"  {ten_kich_ban[s]:12s} | "
          f"{WS_parts[s]:>10.4f} | "
          f"{Z_robs:>10.4f} | "
          f"{regret_s:>10.4f} | "
          f"{p[s]:>6.2f}")

print(f"\n  Max Regret (θ*)     = {theta_val:>12,.4f}")
print(f"\n=== TỔNG KẾT SO SÁNH ===")
print(f"  {'Phương pháp':15s} | {'Z kỳ vọng':>12} | "
      f"{'Max Regret':>12} | {'Chiến lược':>20}")
print("  " + "─" * 68)

# Tính max regret của EV và SP
def tinh_max_regret(x_fixed):
    max_reg = 0
    for s in S:
        y2 = tinh_second_stage(x_fixed, s)
        Z_xs = (sum(beta[j]*x_fixed[j] for j in J)
              + sum(beta_s[s,j]*y2[j] for j in J))
        reg  = WS_parts[s] - Z_xs
        max_reg = max(max_reg, reg)
    return max_reg

mr_EV  = tinh_max_regret(x_EV)
mr_SP  = tinh_max_regret(x_SP)
mr_Rob = theta_val

rows = [
    ('EV (xác định)',  EEV,   mr_EV,  'Đơn giản, rủi ro cao'),
    ('SP (ngẫu nhiên)',Z_SP,  mr_SP,  'Cân bằng kỳ vọng'),
    ('Robust (minimax)',Z_rob, mr_Rob, 'An toàn nhất'),
]
for name, z, mr, chien_luoc in rows:
    print(f"  {name:15s} | {z:>12,.4f} | "
          f"{mr:>12,.4f} | {chien_luoc:>20}")

print(f"""
📌 NHẬN XÉT SO SÁNH:
   • EV   : Z kỳ vọng thấp nhất, regret cao nhất
             → Không nên dùng khi có bất định cao
   • SP   : Cân bằng tốt giữa kỳ vọng và rủi ro
             → Phù hợp hoạch định chính sách VN
   • Robust: Z kỳ vọng thấp hơn SP {Z_SP-Z_rob:,.4f}
             nhưng đảm bảo regret ≤ {theta_val:,.4f}
             → Phù hợp khi lo ngại kịch bản s4 (Khủng hoảng)
""")

# ═══════════════════════════════════════════════════════════════
# BIỂU ĐỒ TỔNG HỢP — 4 biểu đồ
# ═══════════════════════════════════════════════════════════════
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle(
    'Bài 10 — Quy hoạch ngẫu nhiên 2 giai đoạn\n'
    'So sánh EV vs SP vs Robust',
    fontsize=14, fontweight='bold')

mau_s = {'s1':'#4CE882','s2':'#4C9BE8',
         's3':'#E8D84C','s4':'#E84C4C'}

# ── Biểu đồ 1: First-stage 3 phương pháp ────────────────────
ax1 = axes[0, 0]
x_pos = np.arange(len(J))
w_bar = 0.25
data_pp = [
    ('EV',     x_EV,  '#E84C4C'),
    ('SP',     x_SP,  '#4C9BE8'),
    ('Robust', x_rob, '#4CE882'),
]
for k, (name, xv, col) in enumerate(data_pp):
    vals = [xv[j] for j in J]
    ax1.bar(x_pos + (k-1)*w_bar, vals, w_bar,
            label=name, color=col,
            edgecolor='white', linewidth=1.2)

ax1.set_xticks(x_pos)
ax1.set_xticklabels([ten_hang_muc[j] for j in J],
                    fontsize=9, rotation=10)
ax1.set_title('First-Stage x*\nEV vs SP vs Robust',
              fontsize=11, fontweight='bold')
ax1.set_ylabel('Ngân sách (tỷ VND)')
ax1.legend(fontsize=10)
ax1.grid(axis='y', alpha=0.3)

# ── Biểu đồ 2: EEV, Z_SP, WS ────────────────────────────────
ax2 = axes[0, 1]
metrics = ['EEV\n(dùng x_EV)', 'Z_SP\n(Stochastic)', 'WS\n(Hoàn hảo)']
values  = [EEV, Z_SP, WS]
colors  = ['#E84C4C', '#4C9BE8', '#4CE882']
bars2   = ax2.bar(metrics, values, color=colors,
                  edgecolor='white', linewidth=1.5, width=0.5)

for bar, val in zip(bars2, values):
    ax2.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + max(values)*0.01,
             f'{val:,.2f}', ha='center',
             fontsize=10, fontweight='bold')

# VSS annotation
ax2.annotate('', xy=(1, Z_SP), xytext=(1, EEV),
             arrowprops=dict(arrowstyle='<->',
                             color='navy', lw=2.5))
ax2.text(1.3, (EEV+Z_SP)/2,
         f'VSS={VSS:,.2f}',
         color='navy', fontsize=9, fontweight='bold')

# EVPI annotation
ax2.annotate('', xy=(2, WS), xytext=(2, Z_SP),
             arrowprops=dict(arrowstyle='<->',
                             color='darkgreen', lw=2.5))
ax2.text(2.3, (Z_SP+WS)/2,
         f'EVPI={EVPI:,.2f}',
         color='darkgreen', fontsize=9, fontweight='bold')

ax2.set_title('VSS và EVPI\nEEV ≤ Z_SP ≤ WS',
              fontsize=11, fontweight='bold')
ax2.set_ylabel('Giá trị mục tiêu')
ax2.grid(axis='y', alpha=0.3)

# ── Biểu đồ 3: WS từng kịch bản ─────────────────────────────
ax3 = axes[1, 0]
ws_list = [WS_parts[s] for s in S]
ten_kb  = [ten_kich_ban[s] for s in S]
p_list  = [p[s] for s in S]

bars3 = ax3.bar(ten_kb, ws_list,
                color=[mau_s[s] for s in S],
                edgecolor='white', linewidth=1.5,
                alpha=0.85)
for bar, val, prob in zip(bars3, ws_list, p_list):
    ax3.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + max(ws_list)*0.01,
             f'{val:,.1f}\n(p={prob})',
             ha='center', fontsize=9, fontweight='bold')

ax3.axhline(y=Z_SP, color='steelblue', linewidth=2,
            linestyle='--', label=f'Z_SP={Z_SP:,.1f}')
ax3.axhline(y=WS, color='darkgreen', linewidth=2,
            linestyle='-.', label=f'WS={WS:,.1f}')
ax3.set_title('Z* từng kịch bản (WS)\nvà tổng kỳ vọng',
              fontsize=11, fontweight='bold')
ax3.set_ylabel('Giá trị Z*_s')
ax3.legend(fontsize=9)
ax3.grid(axis='y', alpha=0.3)

print("\n✅ Biểu đồ tổng hợp hoàn thành!")
print(f"  Biểu đồ 1: First-stage 3 phương pháp ✅")
print(f"  Biểu đồ 2: VSS={VSS:,.2f} | EVPI={EVPI:,.2f} ✅")
print(f"  Biểu đồ 3: WS từng kịch bản ✅")