# -*- coding: utf-8 -*-
"""Bai11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JaH9oYcHYF2rKXlsiscyoCEvAi-rkfR2
"""

# ============================================================
# CELL 1 — IMPORT & THAM SỐ BÀI 11
# Không cần file CSV
# ============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import gymnasium as gym
from gymnasium import spaces
import warnings
warnings.filterwarnings("ignore")

np.random.seed(42)

# ── Tên hành động và trạng thái ────────────────────────────
ACTION_NAMES = [
    'a0: Truyền thống',
    'a1: Cân bằng',
    'a2: Số hóa nhanh',
    'a3: AI dẫn dắt',
    'a4: Bao trùm',
]
STATE_DIMS  = ['GDP growth', 'Digital', 'AI capacity', 'Unemp risk']
LEVEL_NAMES = ['Thấp', 'Trung bình', 'Cao']

# Phân bổ ngân sách theo từng hành động [K, D, AI, H]
ALLOCATION = {
    0: np.array([0.70, 0.10, 0.10, 0.10]),
    1: np.array([0.40, 0.25, 0.15, 0.20]),
    2: np.array([0.25, 0.45, 0.15, 0.15]),
    3: np.array([0.20, 0.20, 0.45, 0.15]),
    4: np.array([0.30, 0.20, 0.10, 0.40]),
}

# Trọng số reward
W = np.array([0.40, 0.25, 0.20, 0.15])

# Tham số Cobb-Douglas (từ Bài 1)
ALPHA, BETA_L = 0.33, 0.42
GAMMA_D, DELTA_AI, THETA_H = 0.10, 0.08, 0.07

# A0 calibrate từ dữ liệu 2025
Y2025  = 12847.6
K2025, L2025 = 25900, 53.4
D2025, AI2025, H2025 = 19.5, 80.1, 29.2
A0 = Y2025 / (K2025**ALPHA * L2025**BETA_L *
               D2025**GAMMA_D * AI2025**DELTA_AI * H2025**THETA_H)

BUDGET   = 1000    # nghìn tỷ VND/năm
L_FIXED  = 54.0
TFP_RATE = 0.015   # TFP tăng 1.5%/năm

COLORS = {
    'qlearn': '#1B4F72',
    'a1':     '#1E8449',
    'a3':     '#E74C3C',
    'random': '#D35400',
}

print("✅ Import & tham số xong!")
print(f"   A0 calibrated = {A0:.4f}")
print(f"   Tổng trạng thái MDP: 3^4 = {3**4}")
print(f"   Số hành động: {len(ALLOCATION)}")

# ============================================================
# CELL 2 — CÂU 11.3.1
# Cài đặt môi trường VietnamEconomyEnv kế thừa gymnasium.Env
# T=10 năm là một episode
# ============================================================
print("=" * 65)
print("CÂU 11.3.1 — MÔI TRƯỜNG GYMNASIUM VietnamEconomyEnv")
print("=" * 65)

class VietnamEconomyEnv(gym.Env):
    """
    Môi trường MDP mô phỏng kinh tế Việt Nam 2026-2035.

    Trạng thái: [gdp_growth, digital, ai_capacity, unemp_risk]
                mỗi chiều: 0=low, 1=medium, 2=high
    Hành động : 0-4 (5 chiến lược phân bổ ngân sách)
    Reward    : R = w1*ΔGDP - w2*Δunemp - w3*CyberRisk - w4*Emission
    Episode   : T=10 bước (2026-2035)
    """

    metadata = {"render_modes": []}

    def __init__(self):
        super().__init__()
        self.action_space      = spaces.Discrete(5)
        self.observation_space = spaces.MultiDiscrete([3, 3, 3, 3])
        self.T = 10

    def _digitize_state(self, K, D, AI, H, gdp_growth):
        """Chuyển giá trị liên tục → trạng thái rời rạc."""
        g  = 0 if gdp_growth < 5 else (1 if gdp_growth < 8 else 2)
        d  = 0 if D < 15        else (1 if D < 25        else 2)
        ai = 0 if AI < 80       else (1 if AI < 120      else 2)
        # Unemployment risk: proxy ngược H
        # H<25% → rủi ro cao (2), 25-35% → trung bình (1), >35% → thấp (0)
        u  = 2 if H < 25        else (1 if H < 35        else 0)
        return np.array([g, d, ai, u], dtype=np.int64)

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        # Điều kiện ban đầu VN 2026 (từ đề bài)
        self.K    = 27500.0
        self.D    = 20.3
        self.AI   = 86.0
        self.H    = 30.0
        self.A    = A0
        self.t    = 0
        # Trạng thái VN 2026: GDP=medium(7%), D=medium(20%), AI=medium(86k), U=medium
        self.state = self._digitize_state(self.K, self.D, self.AI, self.H, 7.0)
        return self.state.copy(), {}

    def step(self, action):
        a    = ALLOCATION[action]

        # ── Cập nhật trạng thái ────────────────────────────
        I_K  = a[0] * BUDGET
        I_D  = a[1] * BUDGET / 100     # → đơn vị % GDP
        I_AI = a[2] * BUDGET / 20      # → nghìn DN số
        I_H  = a[3] * BUDGET / 200     # → % lao động

        Y_old = (self.A * self.K**ALPHA * L_FIXED**BETA_L *
                 self.D**GAMMA_D * self.AI**DELTA_AI * self.H**THETA_H)

        self.K  = (1 - 0.05)  * self.K  + I_K
        self.D  = (1 - 0.12)  * self.D  + I_D
        self.AI = (1 - 0.15)  * self.AI + I_AI
        self.H  = self.H + 0.8 * I_H - 0.02 * self.H
        self.A  = self.A * (1 + TFP_RATE)

        Y_new = (self.A * self.K**ALPHA * L_FIXED**BETA_L *
                 self.D**GAMMA_D * self.AI**DELTA_AI * self.H**THETA_H)

        gdp_growth = (Y_new - Y_old) / Y_old * 100

        # ── Tính reward ────────────────────────────────────
        delta_gdp   = gdp_growth
        delta_unemp = max(0.0, 25.0 - self.H) * 0.1
        cyber_risk  = a[2] * 0.5
        emission    = (a[0] + a[2]) * 0.3

        reward = (W[0] * delta_gdp
                  - W[1] * delta_unemp
                  - W[2] * cyber_risk
                  - W[3] * emission)

        # ── Chuyển trạng thái ─────────────────────────────
        self.state = self._digitize_state(
            self.K, self.D, self.AI, self.H, gdp_growth
        )

        self.t += 1
        terminated = self.t >= self.T
        return self.state.copy(), reward, terminated, False, {
            'Y': Y_new, 'gdp_growth': gdp_growth,
            'K': self.K, 'D': self.D, 'AI': self.AI, 'H': self.H
        }

# ── Kiểm tra môi trường ────────────────────────────────────
env = VietnamEconomyEnv()
s, _ = env.reset()
print(f"\nTrạng thái VN 2026: {s}")
print(f"  GDP growth → {LEVEL_NAMES[s[0]]}")
print(f"  Digital    → {LEVEL_NAMES[s[1]]}")
print(f"  AI cap     → {LEVEL_NAMES[s[2]]}")
print(f"  Unemp risk → {LEVEL_NAMES[s[3]]}")

# Chạy thử 1 episode với hành động cân bằng
s, _ = env.reset()
total_r = 0
print(f"\nThử 1 episode (luôn a=1 Cân bằng):")
for t in range(env.T):
    s2, r, done, _, info = env.step(1)
    total_r += r
    if t < 3:
        print(f"  t={t}: s'={s2}, r={r:.4f}, Y={info['Y']:.1f}")
    s = s2
print(f"  Tổng reward: {total_r:.4f}")
print("\n✅ Môi trường hoạt động đúng!")

# ============================================================
# CELL 3 — CÂU 11.3.2
# Q-learning: α=0.1, γ=0.95, ε từ 1.0→0.05 qua 10.000 eps
# ============================================================
print("=" * 65)
print("CÂU 11.3.2 — HUẤN LUYỆN Q-LEARNING (10.000 episodes)")
print("=" * 65)

# Tham số Q-learning
LR      = 0.1    # learning rate α
GAMMA   = 0.95   # discount factor
EPS_START = 1.0
EPS_END   = 0.05
N_EPISODES = 10000

# Bảng Q: shape (3,3,3,3,5) = 81 trạng thái × 5 hành động
Q = np.zeros((3, 3, 3, 3, 5))

# Lưu reward mỗi episode để vẽ learning curve
episode_rewards = []

print(f"\n⏳ Đang huấn luyện {N_EPISODES} episodes...\n")

for ep in range(N_EPISODES):
    # Epsilon giảm tuyến tính từ EPS_START → EPS_END
    eps = max(EPS_END, EPS_START - ep / 5000)

    s, _ = env.reset()
    total_r = 0.0

    while True:
        # Epsilon-greedy
        if np.random.rand() < eps:
            a = env.action_space.sample()
        else:
            a = int(np.argmax(Q[tuple(s)]))

        s2, r, done, _, _ = env.step(a)

        # Cập nhật Q-table
        Q[tuple(s) + (a,)] += LR * (
            r + GAMMA * Q[tuple(s2)].max() - Q[tuple(s) + (a,)]
        )

        total_r += r
        s = s2
        if done:
            break

    episode_rewards.append(total_r)

    # In tiến độ mỗi 2000 episodes
    if (ep + 1) % 2000 == 0:
        avg = np.mean(episode_rewards[-200:])
        print(f"  Episode {ep+1:>6} | ε={eps:.3f} | avg reward (200 eps) = {avg:.4f}")

print(f"\n✅ Huấn luyện xong!")
print(f"   Avg reward 1000 eps cuối : {np.mean(episode_rewards[-1000:]):.4f}")
print(f"   Avg reward 1000 eps đầu  : {np.mean(episode_rewards[:1000]):.4f}")

# ============================================================
# CELL 4 — CÂU 11.3.3
# Trích xuất π*(s) = argmax_a Q(s,a)
# Báo cáo hành động tại VN 2026 và 4 trạng thái giả định
# ============================================================
print("=" * 65)
print("CÂU 11.3.3 — CHÍNH SÁCH TỐI ƯU π*(s)")
print("=" * 65)

# ── Trích xuất π* cho toàn bộ Q-table ─────────────────────
pi_star = np.argmax(Q, axis=-1)   # shape (3,3,3,3)

# ── Báo cáo 5 trạng thái quan trọng ───────────────────────
test_states = {
    "VN 2026 (thực tế)"               : np.array([1, 1, 1, 1]),
    "Khủng hoảng (GDP↓, D↓, AI↓, U↑)": np.array([0, 0, 0, 2]),
    "Đang phát triển (GDP↑, D↑, U↓)"  : np.array([2, 2, 1, 0]),
    "GDP cao, AI cao, U thấp"          : np.array([2, 1, 2, 0]),
    "GDP thấp, D thấp, U cao"          : np.array([0, 0, 0, 2]),
}

print(f"\n{'Trạng thái':<42} {'s':<14} {'π*(s)':<5} {'Chiến lược'}")
print("─" * 80)
for name, s in test_states.items():
    a = pi_star[tuple(s)]
    q_vals = Q[tuple(s)]
    print(f"{name:<42} {str(s):<14} a={a}    {ACTION_NAMES[a]}")
    print(f"   Q-values: {np.round(q_vals, 3)}")

# ── Mô phỏng 1 episode đầy đủ theo π* ─────────────────────
s, _ = env.reset()
print(f"\n📊 Episode đầy đủ theo π* (bắt đầu từ VN 2026):")
print(f"{'Năm':<6} {'State':<16} {'Action':<22} {'Reward':>8} {'GDP%':>7} {'H':>6}")
print("─" * 70)

total_r = 0
for t in range(env.T):
    a = pi_star[tuple(s)]
    s2, r, done, _, info = env.step(a)
    total_r += r
    print(f"{2026+t:<6} {str(s):<16} {ACTION_NAMES[a]:<22} "
          f"{r:>8.4f} {info['gdp_growth']:>6.2f}% {info['H']:>6.2f}")
    s = s2

print(f"{'TỔNG':>48} {total_r:>8.4f}")

# ── Heatmap Q-values tại một lát cắt trạng thái ───────────
fig, axes = plt.subplots(1, 3, figsize=(16, 4), facecolor='#F4F6F9')

# Lát cắt: AI=1(medium), U=1(medium) → GDP × Digital
q_slice = Q[:, :, 1, 1, :]   # shape (3,3,5)

for ai_idx, (ax, title) in enumerate(zip(axes, [
    'AI=Low (0)', 'AI=Medium (1)', 'AI=High (2)'
])):
    q_show = Q[:, :, ai_idx, 1, :]   # GDP×Digital, U=medium
    # Hành động tối ưu
    best_a = np.argmax(q_show, axis=-1)
    best_q = np.max(q_show, axis=-1)

    im = ax.imshow(best_q, cmap='YlOrRd', aspect='auto')
    for i in range(3):
        for j in range(3):
            ax.text(j, i, f"a={best_a[i,j]}\n{best_q[i,j]:.2f}",
                    ha='center', va='center', fontsize=8.5, fontweight='bold')
    ax.set_xticks([0,1,2]); ax.set_xticklabels(['D:Low','D:Med','D:High'])
    ax.set_yticks([0,1,2]); ax.set_yticklabels(['GDP:Low','GDP:Med','GDP:High'])
    ax.set_title(f"π*(s) khi {title}, U=Med\n(số = hành động tối ưu)",
                 fontsize=10, fontweight='bold', color='#1B4F72')
    plt.colorbar(im, ax=ax, shrink=0.8)

plt.suptitle("CÂU 11.3.3 — Heatmap chính sách π*(s) theo trạng thái (U=Medium)",
             fontsize=12, fontweight='bold', color='#1B4F72')
plt.tight_layout()
plt.show()

# ============================================================
# CELL 5 — CÂU 11.3.4
# So sánh π* với: (a) luôn a1, (b) luôn a3, (c) random
# Vẽ learning curve
# ============================================================
print("=" * 65)
print("CÂU 11.3.4 — SO SÁNH π* vs RULE-BASED + LEARNING CURVE")
print("=" * 65)

N_EVAL = 200   # số episode đánh giá mỗi chính sách

def evaluate_policy(policy, n_ep=N_EVAL):
    """
    Đánh giá chính sách.
    policy: 'qlearn' | 0~4 (fixed) | 'random'
    """
    rewards = []
    for _ in range(n_ep):
        s, _ = env.reset()
        total = 0.0
        for _ in range(env.T):
            if policy == 'qlearn':
                a = int(np.argmax(Q[tuple(s)]))
            elif policy == 'random':
                a = env.action_space.sample()
            else:
                a = int(policy)
            s, r, done, _, _ = env.step(a)
            total += r
            if done: break
        rewards.append(total)
    return np.array(rewards)

# Đánh giá 4 chính sách
r_qlearn = evaluate_policy('qlearn')
r_a1     = evaluate_policy(1)
r_a3     = evaluate_policy(3)
r_random = evaluate_policy('random')

# ── Bảng so sánh ───────────────────────────────────────────
print(f"\n{'Chính sách':<28} {'Mean':>8} {'Std':>7} {'Min':>8} {'Max':>8}")
print("─" * 65)
for label, rewards in [
    ('π* Q-learning',    r_qlearn),
    ('(a) Luôn a1 Cân bằng', r_a1),
    ('(b) Luôn a3 AI dẫn dắt', r_a3),
    ('(c) Random',       r_random),
]:
    print(f"{label:<28} {rewards.mean():>8.4f} {rewards.std():>7.4f} "
          f"{rewards.min():>8.4f} {rewards.max():>8.4f}")

print(f"\n► π* vượt trội hơn a1 : +{r_qlearn.mean()-r_a1.mean():.4f}")
print(f"► π* vượt trội hơn a3 : +{r_qlearn.mean()-r_a3.mean():.4f}")
print(f"► π* vượt trội hơn rnd: +{r_qlearn.mean()-r_random.mean():.4f}")

# ── Vẽ biểu đồ ─────────────────────────────────────────────
fig = plt.figure(figsize=(16, 10), facecolor='#F4F6F9')
gs  = gridspec.GridSpec(2, 2, figure=fig, hspace=0.4, wspace=0.35)

# Panel 1: Learning curve (smoothed)
ax1 = fig.add_subplot(gs[0, :])
window = 200
smoothed = np.convolve(episode_rewards,
                       np.ones(window)/window, mode='valid')
x_smooth = np.arange(window//2, len(episode_rewards) - window//2 + 1)
ax1.plot(episode_rewards, alpha=0.15, color=COLORS['qlearn'], linewidth=0.5)
ax1.plot(x_smooth, smoothed, color=COLORS['qlearn'], linewidth=2,
         label=f'Smoothed (window={window})')
ax1.axhline(r_a1.mean(),     color=COLORS['a1'],
            ls='--', lw=1.5, label=f'a1 Cân bằng = {r_a1.mean():.3f}')
ax1.axhline(r_a3.mean(),     color=COLORS['a3'],
            ls='--', lw=1.5, label=f'a3 AI dẫn dắt = {r_a3.mean():.3f}')
ax1.axhline(r_random.mean(), color=COLORS['random'],
            ls=':',  lw=1.5, label=f'Random = {r_random.mean():.3f}')
ax1.set_xlabel('Episode', fontsize=10)
ax1.set_ylabel('Tổng reward / episode', fontsize=10)
ax1.set_title('Learning Curve — Q-learning (10.000 episodes)',
              fontsize=12, fontweight='bold', color='#1B4F72')
ax1.legend(fontsize=9, loc='lower right')
ax1.grid(alpha=0.3)
ax1.set_facecolor('#F4F6F9')

# Panel 2: Box plot so sánh
ax2 = fig.add_subplot(gs[1, 0])
data_box  = [r_qlearn, r_a1, r_a3, r_random]
labels_box = ['π* Q-learn', 'a1 Cân bằng', 'a3 AI', 'Random']
bp = ax2.boxplot(data_box, labels=labels_box, patch_artist=True,
                 medianprops={'color': 'white', 'lw': 2})
box_colors = [COLORS['qlearn'], COLORS['a1'], COLORS['a3'], COLORS['random']]
for patch, color in zip(bp['boxes'], box_colors):
    patch.set_facecolor(color); patch.set_alpha(0.8)
ax2.set_title('Phân phối reward (200 episodes)',
              fontsize=11, fontweight='bold', color='#1B4F72')
ax2.set_ylabel('Tổng reward', fontsize=9)
ax2.grid(axis='y', alpha=0.3)
ax2.set_facecolor('#F4F6F9')

# Panel 3: Bar chart mean reward
ax3 = fig.add_subplot(gs[1, 1])
means = [r_qlearn.mean(), r_a1.mean(), r_a3.mean(), r_random.mean()]
stds  = [r_qlearn.std(),  r_a1.std(),  r_a3.std(),  r_random.std()]
bars  = ax3.bar(labels_box, means, color=box_colors,
                yerr=stds, capsize=5, edgecolor='white', width=0.55)
for bar, val in zip(bars, means):
    ax3.text(bar.get_x() + bar.get_width()/2,
             val + max(stds)*0.05,
             f'{val:.4f}', ha='center', fontsize=9, fontweight='bold')
ax3.set_title('Mean reward ± std',
              fontsize=11, fontweight='bold', color='#1B4F72')
ax3.set_ylabel('Mean reward', fontsize=9)
ax3.grid(axis='y', alpha=0.3)
ax3.set_facecolor('#F4F6F9')

plt.suptitle("CÂU 11.3.4 — So sánh π* Q-learning vs 3 chính sách rule-based",
             fontsize=13, fontweight='bold', color='#1B4F72')
plt.show()

# ============================================================
# CELL 6 — CÂU 11.3.5 (MỞ RỘNG)
# DQN với Stable-Baselines3, 2 hidden layers 64 units
# ============================================================
import warnings
warnings.filterwarnings("ignore")
# Cài thư viện trước
!pip install stable-baselines3 torch -q

import numpy as np
import matplotlib.pyplot as plt
from stable_baselines3 import DQN
import gymnasium as gym
from gymnasium import spaces

print("=" * 65)
print("CÂU 11.3.5 (MỞ RỘNG) — DQN với Stable-Baselines3")
print("=" * 65)

# ── Wrapper đổi MultiDiscrete → Box (SB3 yêu cầu) ─────────
class FlattenObsWrapper(gym.ObservationWrapper):
    """Chuyển MultiDiscrete(3,3,3,3) → Box(4,) float32"""
    def __init__(self, env):
        super().__init__(env)
        self.observation_space = spaces.Box(
            low=0.0, high=2.0, shape=(4,), dtype=np.float32
        )
    def observation(self, obs):
        return obs.astype(np.float32)

# ── Tạo môi trường bọc ─────────────────────────────────────
env_dqn = FlattenObsWrapper(VietnamEconomyEnv())

# ── Tạo mô hình DQN ────────────────────────────────────────
model_dqn = DQN(
    "MlpPolicy",
    env_dqn,
    learning_rate=1e-3,
    buffer_size=10000,
    learning_starts=500,
    batch_size=64,
    gamma=0.95,
    exploration_fraction=0.5,
    exploration_final_eps=0.05,
    policy_kwargs=dict(net_arch=[64, 64]),  # 2 hidden layers 64 units
    verbose=0,
    seed=42,
)

print("\n⏳ Đang huấn luyện DQN (100.000 bước)... (~2-3 phút)\n")
model_dqn.learn(total_timesteps=100_000)
print("✅ DQN huấn luyện xong!")

# ── Đánh giá DQN ───────────────────────────────────────────
N_EVAL = 200
r_dqn = []
for _ in range(N_EVAL):
    s, _ = env_dqn.reset()
    total = 0.0
    for _ in range(10):
        a, _ = model_dqn.predict(s, deterministic=True)
        s, r, done, _, _ = env_dqn.step(int(a))
        total += r
        if done:
            break
    r_dqn.append(total)
r_dqn = np.array(r_dqn)

# ── Bảng so sánh ───────────────────────────────────────────
print(f"\n{'Phương pháp':<28} {'Mean reward':>12} {'Std':>8}")
print("─" * 52)
for label, rewards in [
    ('Q-learning tabular', r_qlearn),
    ('DQN (SB3, 64×64)',   r_dqn),
    ('Luôn a1 Cân bằng',  r_a1),
    ('Luôn a3 AI dẫn dắt', r_a3),
    ('Random',             r_random),
]:
    print(f"{label:<28} {rewards.mean():>12.4f} {rewards.std():>8.4f}")

improve = r_dqn.mean() - r_qlearn.mean()
print(f"\n► DQN {'CẢI THIỆN ✅' if improve > 0 else 'KHÔNG cải thiện ❌'} "
      f"so với Q-learning tabular: {improve:+.4f} điểm reward")

# ── Biểu đồ so sánh ────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5), facecolor='#F4F6F9')

# Box plot
labels_b = ['Q-learn\n(tabular)', 'DQN\n(64×64)', 'a1\nCân bằng',
            'a3\nAI dẫn dắt', 'Random']
data_b   = [r_qlearn, r_dqn, r_a1, r_a3, r_random]
cols_b   = ['#1B4F72', '#8E44AD', '#1E8449', '#E74C3C', '#D35400']

bp = axes[0].boxplot(data_b, labels=labels_b, patch_artist=True,
                     medianprops={'color': 'white', 'lw': 2})
for patch, c in zip(bp['boxes'], cols_b):
    patch.set_facecolor(c)
    patch.set_alpha(0.85)
axes[0].set_title('Phân phối reward (200 episodes)',
                  fontsize=11, fontweight='bold', color='#1B4F72')
axes[0].set_ylabel('Tổng reward / episode', fontsize=9)
axes[0].grid(axis='y', alpha=0.3)
axes[0].set_facecolor('#F4F6F9')

# Bar chart mean ± std
means = [r.mean() for r in data_b]
stds  = [r.std()  for r in data_b]
bars  = axes[1].bar(labels_b, means, color=cols_b,
                    yerr=stds, capsize=5,
                    edgecolor='white', width=0.55)
for bar, val in zip(bars, means):
    axes[1].text(bar.get_x() + bar.get_width()/2,
                 val + max(stds)*0.05,
                 f'{val:.3f}', ha='center',
                 fontsize=9, fontweight='bold')
axes[1].set_title('Mean reward ± std',
                  fontsize=11, fontweight='bold', color='#1B4F72')
axes[1].set_ylabel('Mean reward', fontsize=9)
axes[1].set_ylim(min(means) * 0.97, max(means) * 1.05)
axes[1].grid(axis='y', alpha=0.3)
axes[1].set_facecolor('#F4F6F9')

plt.suptitle("CÂU 11.3.5 — So sánh Q-learning Tabular vs DQN vs Rule-based",
             fontsize=12, fontweight='bold', color='#1B4F72')
plt.tight_layout()
plt.show()